### ISSUE TITLE
Can't run fairseq plugins with multiple GPUs.

### ISSUE THREAD

**Issue by philip30** [facebookresearch/fairseq#3299]
## 🐛 Bug
I followed the tutorial on building the plugins. Everything seems fine until I want to try to work with multiple GPUs. I tried few things and made sure that my module is not in sys.path by default. Please advice!

### To Reproduce

```
CUDA_VISIBLE_DEVICES=0,1 fairseq-train \
  --user-dir $MY_USER_DIRECTORY \
  --arch my_arch \
  --task my_task \
  --criterion my_loss \
  --batch-size 32 --num-workers 8 \ 
  --optimizer adam \
  --lr-scheduler inverse_sqrt --lr 5e-4 --warmup-init-lr 1e-6 --warmup-updates 8000 \
  --update-freq 1 --log-interval 1
```

#### Code sample

In ```$MY_USER_DIRECTORY/__init__.py```
```
from . import models
from . import criterions
from . import tasks
```

### Expected behavior

```MY_USER_DIRECTORY=/home/parthur/tools/bert/spanBERT-doc/spanbert_doc```
This is the error message. I include the real name of the architecture, criterions, and tasks in the real error message

```
2021-03-03 07:30:05 | INFO | fairseq.distributed_utils | distributed init (rank 0): tcp://localhost:17810
2021-03-03 07:30:05 | INFO | fairseq.distributed_utils | distributed init (rank 1): tcp://localhost:17810
2021-03-03 07:30:05 | INFO | fairseq.distributed_utils | initialized host krylov-ws-rc-byn6lgn-d0lenoip6yck8kbpftzibivz1ryumld9q6c-9g9tv as rank 1
2021-03-03 07:30:05 | INFO | fairseq.distributed_utils | initialized host krylov-ws-rc-byn6lgn-d0lenoip6yck8kbpftzibivz1ryumld9q6c-9g9tv as rank 0
Traceback (most recent call last):
  File "/home/parthur/miniconda3/bin/fairseq-train", line 8, in <module>
    sys.exit(cli_main())
  File "/home/parthur/miniconda3/lib/python3.8/site-packages/fairseq_cli/train.py", line 352, in cli_main
    distributed_utils.call_main(args, main)
  File "/home/parthur/miniconda3/lib/python3.8/site-packages/fairseq/distributed_utils.py", line 283, in call_main
    torch.multiprocessing.spawn(
  File "/home/parthur/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/parthur/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/parthur/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/parthur/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/home/parthur/miniconda3/lib/python3.8/site-packages/fairseq/distributed_utils.py", line 270, in distributed_main
    main(args, **kwargs)
  File "/home/parthur/miniconda3/lib/python3.8/site-packages/fairseq_cli/train.py", line 43, in main
    utils.import_user_module(args)
  File "/home/parthur/miniconda3/lib/python3.8/site-packages/fairseq/utils.py", line 458, in import_user_module
    raise ImportError(
ImportError: Failed to import --user-dir=/home/parthur/tools/bert/spanBERT-doc/spanbert_doc because the corresponding module name (spanbert_doc) is not globally unique. Please rename the directory to something unique and try again.
```

### Environment

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0): 1.6.0
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): conda
 - Python version: 3.8.
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration:Tesla V100-SXM2
 - Any other relevant information:

**Comment by philip30** [comment]
It works fine with single GPU (```CUDA_VISIBLE_DEVICES=0```). When I add ```--distributed-no-spawn``` the software hangs and even ctrl+c can not work.

**Comment by philip30** [comment]
Would appreciate some comments :)
