### ISSUE TITLE
Error while training mt model with a large dataset (863M sent pairs) 

### ISSUE THREAD

**Issue by sunilitggu** [facebookresearch/fairseq#3904]
Error: 
------
2021-09-22 13:37:07 | INFO | fairseq_cli.train | task: TranslationTask
2021-09-22 13:37:07 | INFO | fairseq_cli.train | model: TransformerModel
2021-09-22 13:37:07 | INFO | fairseq_cli.train | criterion: LabelSmoothedCrossEntropyCriterion
2021-09-22 13:37:07 | INFO | fairseq_cli.train | num. shared model params: 307,171,328 (num. trained: 307,171,328)
2021-09-22 13:37:07 | INFO | fairseq_cli.train | num. expert model params: 0 (num. trained: 0)
2021-09-22 13:37:07 | INFO | fairseq.data.data_utils | loaded 50,000 examples from: dataset/eu-en/eu2en/bin_eu2en/valid.eu-en.eu
2021-09-22 13:37:08 | INFO | fairseq.data.data_utils | loaded 50,000 examples from: dataset/eu-en/eu2en/bin_eu2en/valid.eu-en.en
2021-09-22 13:37:08 | INFO | fairseq.tasks.translation | dataset/eu-en/eu2en/bin_eu2en valid eu-en 50000 examples
2021-09-22 13:37:10 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:2 to store for rank: 0
2021-09-22 13:37:10 | INFO | torch.distributed.distributed_c10d | Rank 0: Completed store-based barrier for 8 nodes.
2021-09-22 13:37:11 | INFO | fairseq.utils | ***********************CUDA enviroments for all 8 workers***********************
2021-09-22 13:37:11 | INFO | fairseq.utils | rank   0: capabilities =  7.0  ; total memory = 31.749 GB ; name = Tesla V100-SXM2-32GB                    
2021-09-22 13:37:11 | INFO | fairseq.utils | rank   1: capabilities =  7.0  ; total memory = 31.749 GB ; name = Tesla V100-SXM2-32GB                    
2021-09-22 13:37:11 | INFO | fairseq.utils | rank   2: capabilities =  7.0  ; total memory = 31.749 GB ; name = Tesla V100-SXM2-32GB                    
2021-09-22 13:37:11 | INFO | fairseq.utils | rank   3: capabilities =  7.0  ; total memory = 31.749 GB ; name = Tesla V100-SXM2-32GB                    
2021-09-22 13:37:11 | INFO | fairseq.utils | rank   4: capabilities =  7.0  ; total memory = 31.749 GB ; name = Tesla V100-SXM2-32GB                    
2021-09-22 13:37:11 | INFO | fairseq.utils | rank   5: capabilities =  7.0  ; total memory = 31.749 GB ; name = Tesla V100-SXM2-32GB                    
2021-09-22 13:37:11 | INFO | fairseq.utils | rank   6: capabilities =  7.0  ; total memory = 31.749 GB ; name = Tesla V100-SXM2-32GB                    
2021-09-22 13:37:11 | INFO | fairseq.utils | rank   7: capabilities =  7.0  ; total memory = 31.749 GB ; name = Tesla V100-SXM2-32GB                    
2021-09-22 13:37:11 | INFO | fairseq.utils | ***********************CUDA enviroments for all 8 workers***********************
2021-09-22 13:37:11 | INFO | fairseq_cli.train | training on 8 devices (GPUs/TPUs)
2021-09-22 13:37:11 | INFO | fairseq_cli.train | max tokens per device = 3584 and max sentences per device = None
2021-09-22 13:37:11 | INFO | fairseq.trainer | Preparing to load checkpoint saved_models/eu2en/trans_eu2en/checkpoint_last.pt
2021-09-22 13:37:11 | INFO | fairseq.trainer | No existing checkpoint found saved_models/eu2en/trans_eu2en/checkpoint_last.pt
2021-09-22 13:37:11 | INFO | fairseq.trainer | loading train data for epoch 1
2021-09-22 13:40:57 | INFO | fairseq.data.data_utils | loaded 863,460,876 examples from: dataset/eu-en/eu2en/bin_eu2en/train.eu-en.eu
2021-09-22 13:43:27 | INFO | fairseq.data.data_utils | loaded 863,460,876 examples from: dataset/eu-en/eu2en/bin_eu2en/train.eu-en.en
2021-09-22 13:43:27 | INFO | fairseq.tasks.translation | dataset/eu-en/eu2en/bin_eu2en train eu-en 863460876 examples
2021-09-22 13:56:20 | INFO | fairseq.trainer | begin training epoch 1
2021-09-22 13:56:20 | INFO | fairseq_cli.train | Start iterating over samples

Traceback (most recent call last):
  File "/home/ss1/anaconda3/envs/torch1.9/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/home/ss1/library/fairseq/fairseq_cli/train.py", line 507, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/ss1/library/fairseq/fairseq/distributed/utils.py", line 351, in call_main
    join=True,
  File "/home/ss1/anaconda3/envs/torch1.9/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/ss1/anaconda3/envs/torch1.9/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/ss1/anaconda3/envs/torch1.9/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 136, in join
    signal_name=name
torch.multiprocessing.spawn.ProcessExitedException: process 6 terminated with signal SIGKILL

####  Code used to train
---------------------------
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 fairseq-train \
	$DATAPATH \
	--arch transformer_wmt_en_de_big_t2t \
	--optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
	--lr 0.0005 --lr-scheduler inverse_sqrt --warmup-updates 4000 --warmup-init-lr 1e-07 \
	--dropout 0.3 --weight-decay 0 \
	--criterion label_smoothed_cross_entropy --label-smoothing 0.1 \
	--max-tokens 3584 \
	--save-dir $MODELPATH \
	--fp16 \
	--log-interval 100 \
	--max-epoch 10 \
	--save-interval 1 \
	--skip-invalid-size-inputs-valid-test \
	--eval-bleu \
	--eval-bleu-args '{"beam": 5, "max_len_a": 1.2, "max_len_b": 10}' \
	--eval-bleu-detok moses \
	--eval-bleu-remove-bpe \
	--eval-bleu-print-samples \
	--no-epoch-checkpoints \
	--best-checkpoint-metric bleu --maximize-best-checkpoint-metric
 

#### What have you tried?
I have tried using different tmp directory as suggested by [Myle Ott  ](https://github.com/pytorch/fairseq/issues/2166#issuecomment-634191329)

CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 
TMPDIR=/home/ss1/project/mt_en_2021/tmp fairseq-train \
	$DATAPATH \
	--arch transformer_wmt_en_de_big_t2t \
	--optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
	--lr 0.0005 --lr-scheduler inverse_sqrt --warmup-updates 4000 --warmup-init-lr 1e-07 \
	--dropout 0.3 --weight-decay 0 \
	--criterion label_smoothed_cross_entropy --label-smoothing 0.1 \
	--max-tokens 3584 \
	--save-dir $MODELPATH \
	--fp16 \
	--log-interval 100 \
	--max-epoch 10 \
	--save-interval 1 \
	--skip-invalid-size-inputs-valid-test \
	--eval-bleu \
	--eval-bleu-args '{"beam": 5, "max_len_a": 1.2, "max_len_b": 10}' \
	--eval-bleu-detok moses \
	--eval-bleu-remove-bpe \
	--eval-bleu-print-samples \
	--no-epoch-checkpoints \
	--best-checkpoint-metric bleu --maximize-best-checkpoint-metric

#### What's your environment?

 - fairseq Version (e.g., 1.0 or main):  1.0.0a0+cb84694
 - PyTorch Version (e.g., 1.0): 1.9.0
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: python 3.7
 - CUDA/cuDNN version: 11.3
 - GPU models and configuration: DGX-1
 - Any other relevant information: I also have tried it with lower pytorch versions e.g. 1.7.1 and 1.8.0

**Comment by sunilitggu** [comment]
It's working with _--num-workers 0_
