### ISSUE TITLE
Error in inference of Hindi Model

### ISSUE THREAD

**Issue by MrityunjoyS** [facebookresearch/fairseq#3929]
I've finetuned wav2vec2.0 model using custom hindi dataset and dict file.
My dict.ltr.txt file :
ँ 221552
ं 2532935
ः 7964
अ 743852
आ 486561
इ 228473
ई 147737
उ 574563
ऊ 37016
ऋ 8300
ए 986893
ऐ 22905
ऑ 22600
ओ 74015
औ 692314
क 5256799
ख 515586
ग 965339
घ 147515
च 854760
छ 331551
ज 1024320
झ 140483
ञ 7963
ट 420346
ठ 125848
ड 552437
ढ 66851
ण 95966
त 2128375
थ 847606
द 1237555
ध 265262
न 2562397
प 1958588
फ 257928
ब 1311026
भ 493523
म 2415669
य 1620380
र 4351756
ल 1804089
व 1192983
श 559844
ष 199197
स 2783472
ह 3549070
़ 494196
ा 6052649
ि 2356618
ी 2555418
ु 1068016
ू 596680
ृ 73764
ॅ 7511
े 5044035
ै 1443480
ॉ 74500
ो 1627689
ौ 111129
् 2224056

**After my model is trained I'm trying on inferecing my model but getting below error :-**

```
INFO:__main__:| decoding with criterion ctc
INFO:__main__:| loading model(s) from /root/model_and_dict_hi/checkpoint_best.pt
INFO:fairseq.data.audio.raw_audio_dataset:loaded 496, skipped 0 samples
Traceback (most recent call last):
  File "examples/speech_recognition/infer.py", line 427, in <module>
    cli_main()
  File "examples/speech_recognition/infer.py", line 423, in cli_main
    main(args)
  File "examples/speech_recognition/infer.py", line 239, in main
    task.load_dataset(args.gen_subset, task_cfg=saved_cfg.task)
  File "/root/fairseq/fairseq/tasks/audio_pretraining.py", line 220, in load_dataset
    line for i, line in enumerate(f)
  File "/root/fairseq/fairseq/tasks/audio_pretraining.py", line 220, in <listcomp>
    line for i, line in enumerate(f)
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 0: ordinal not in range(128)
```
So I'm using **hindi character's which are obviously not ascii**, So what configuration changes must be done.
Please suggest what I might be doing wrong. Thank you in advance .

**Comment by MrityunjoyS** [comment]
found a workaround
