### ISSUE TITLE
Pretraining HuBERT

### ISSUE THREAD

**Issue by maevdokimov** [facebookresearch/fairseq#3930]
Hi,

I tried to pretrain HuBERT on LibriSpeech960. I followed this [guide](https://github.com/pytorch/fairseq/blob/main/examples/hubert/simple_kmeans/README.md) and created {train, valid}.tsv files and {train, valid}.km k-means labels. After running 

`$ HYDRA_FULL_ERROR=1 python fairseq_cli/hydra_train.py \
  --config-dir /path/to/fairseq-py/examples/hubert/config/pretrain \
  --config-name hubert_base_librispeech \
  task.data=/path/to/data task.label_dir=/path/to/labels model.label_rate=100`

I meet

Traceback (most recent call last):
  File "fairseq_cli/hydra_train.py", line 88, in <module>
    cli_main()
  File "fairseq_cli/hydra_train.py", line 84, in cli_main
    hydra_main()
  File "/opt/conda/lib/python3.8/site-packages/hydra/main.py", line 48, in decorated_main
    _run_hydra(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 377, in _run_hydra
    run_and_report(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 111, in run
    _ = ret.return_value
  File "/opt/conda/lib/python3.8/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/opt/conda/lib/python3.8/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "fairseq_cli/hydra_train.py", line 28, in hydra_main
    _hydra_main(cfg)
  File "fairseq_cli/hydra_train.py", line 53, in _hydra_main
    distributed_utils.call_main(cfg, pre_main, **kwargs)
  File "/root/fairseq/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "/root/fairseq/fairseq_cli/train.py", line 97, in main
    model = task.build_model(cfg.model)
  File "/root/fairseq/fairseq/tasks/fairseq_task.py", line 320, in build_model
    model = models.build_model(cfg, self)
  File "/root/fairseq/fairseq/models/__init__.py", line 107, in build_model
    return model.build_model(cfg, task)
  File "/root/fairseq/fairseq/models/hubert/hubert.py", line 320, in build_model
    model = HubertModel(cfg, task.cfg, task.dictionaries)
  File "/root/fairseq/fairseq/tasks/hubert_pretraining.py", line 142, in dictionaries
    return self.state.dictionaries
  File "/root/fairseq/fairseq/tasks/fairseq_task.py", line 42, in \_\_getattr\_\_
    self._state[name] = self._factories\[name]()
  File "/root/fairseq/fairseq/tasks/hubert_pretraining.py", line 152, in load_dictionaries
    dictionaries = [Dictionary.load(f"{label_dir}/dict.{label}.txt") for label in self.cfg.labels]
  File "/root/fairseq/fairseq/tasks/hubert_pretraining.py", line 152, in <listcomp>
    dictionaries = [Dictionary.load(f"{label_dir}/dict.{label}.txt") for label in self.cfg.labels]
  File "/root/fairseq/fairseq/data/dictionary.py", line 226, in load
    d.add_from_file(f)
  File "/root/fairseq/fairseq/data/dictionary.py", line 239, in add_from_file
    raise fnfe
  File "/root/fairseq/fairseq/data/dictionary.py", line 236, in add_from_file
    with open(PathManager.get_local_path(f), "r", encoding="utf-8") as fd:
FileNotFoundError: [Errno 2] No such file or directory: 'examples/hubert/simple_kmeans/data/labels/dict.ltr.txt'

[There](https://github.com/pytorch/fairseq/blob/main/examples/hubert/README.md) is no info about this txt file. How can i fix it?

**Comment by Yingfang-Yang** [comment]
You can download here https://dl.fbaipublicfiles.com/fairseq/wav2vec/dict.ltr.txt
