### ISSUE TITLE
Why am I getting a segfault when trying to import the data.Dictionary?

### ISSUE THREAD

**Issue by cinjon** [facebookresearch/fairseq#3976]
## 🐛 Bug

When I run `from fairseq.data import Dictionary` from inside a module, I get a segmentation fault. 
However, when I run it from the same conda environment, but inside of a python shell, it loads just fine.
I am getting very little feedback on what's going wrong from the segfault, just `Segmentation fault (core dumped)`. Any idea what could be causing this?

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Put `from fairseq.data import Dictionary` into the module.
2. Run that module and observe the error.

### Expected behavior

The expected behavior is that this loads no problem like it does in the shell.

### Environment

 - fairseq Version (e.g., 1.0 or main): I tried both the version from the repo via `pip install --editable` as well as from the pip package - `pip install fairseq`.
 - PyTorch Version (e.g., 1.0): 1.10.0
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed fairseq (`pip`, source): Both from repo and from pip package.
 - Build command you used (if compiling from source):
 - Python version: 3.6.13
 - CUDA/cuDNN version: CUDA 11.0
 - GPU models and configuration: Tesla T4
 - Any other relevant information:

**Comment by cinjon** [comment]
This is really frustrating. In ipython, roughly the same thing happens when I try to import the Dictionary:

```
In [1]: from fairseq.data import Dictionary
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/carla/lib/python3.6/site-packages/IPython/terminal/ptutils.py", line 113, in get_completions
    yield from self._get_completions(body, offset, cursor_position, self.ipy_completer)
  File "/home/ubuntu/anaconda3/envs/carla/lib/python3.6/site-packages/IPython/terminal/ptutils.py", line 126, in _get_completions
    for c in completions:
  File "/home/ubuntu/anaconda3/envs/carla/lib/python3.6/site-packages/IPython/core/completer.py", line 438, in _deduplicate_completions
    completions = list(completions)
  File "/home/ubuntu/anaconda3/envs/carla/lib/python3.6/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/home/ubuntu/anaconda3/envs/carla/lib/python3.6/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/home/ubuntu/anaconda3/envs/carla/lib/python3.6/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/home/ubuntu/anaconda3/envs/carla/lib/python3.6/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/home/ubuntu/anaconda3/envs/carla/lib/python3.6/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/carla/bin/ipython", line 8, in <module>
    sys.exit(start_ipython())
  File "/home/ubuntu/anaconda3/envs/carla/lib/python3.6/site-packages/IPython/__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/ubuntu/anaconda3/envs/carla/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/home/ubuntu/anaconda3/envs/carla/lib/python3.6/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/home/ubuntu/anaconda3/envs/carla/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 563, in mainloop
    self.interact()
  File "/home/ubuntu/anaconda3/envs/carla/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 546, in interact
    code = self.prompt_for_code()
  File "/home/ubuntu/anaconda3/envs/carla/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 474, in prompt_for_code
    **self._extra_prompt_options())
  File "/home/ubuntu/anaconda3/envs/carla/lib/python3.6/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1021, in prompt
    set_exception_handler=set_exception_handler, in_thread=in_thread
  File "/home/ubuntu/anaconda3/envs/carla/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 891, in run
    self.run_async(pre_run=pre_run, set_exception_handler=set_exception_handler)
  File "/home/ubuntu/anaconda3/envs/carla/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "/home/ubuntu/anaconda3/envs/carla/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 815, in run_async
    return await _run_async2()
  File "/home/ubuntu/anaconda3/envs/carla/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 797, in _run_async2
    await self.cancel_and_wait_for_background_tasks()
  File "/home/ubuntu/anaconda3/envs/carla/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 1000, in cancel_and_wait_for_background_tasks
    await task
  File "/home/ubuntu/anaconda3/envs/carla/lib/python3.6/site-packages/prompt_toolkit/buffer.py", line 1909, in new_coroutine
    await coroutine(*a, **kw)
  File "/home/ubuntu/anaconda3/envs/carla/lib/python3.6/site-packages/prompt_toolkit/buffer.py", line 1739, in async_completer
    document, complete_event
  File "/home/ubuntu/anaconda3/envs/carla/lib/python3.6/site-packages/prompt_toolkit/completion/base.py", line 272, in get_completions_async
    document, complete_event
  File "/home/ubuntu/anaconda3/envs/carla/lib/python3.6/site-packages/prompt_toolkit/completion/base.py", line 198, in get_completions_async
    for item in self.get_completions(document, complete_event):
  File "/home/ubuntu/anaconda3/envs/carla/lib/python3.6/site-packages/IPython/terminal/ptutils.py", line 116, in get_completions
    print_tb(e)
  File "/home/ubuntu/anaconda3/envs/carla/lib/python3.6/traceback.py", line 53, in print_tb
    print_list(extract_tb(tb, limit=limit), file=file)
  File "/home/ubuntu/anaconda3/envs/carla/lib/python3.6/traceback.py", line 72, in extract_tb
    return StackSummary.extract(walk_tb(tb), limit=limit)
  File "/home/ubuntu/anaconda3/envs/carla/lib/python3.6/traceback.py", line 345, in extract
    for f, lineno in frame_gen:
  File "/home/ubuntu/anaconda3/envs/carla/lib/python3.6/traceback.py", line 310, in walk_tb
    yield tb.tb_frame, tb.tb_lineno
AttributeError: 'TypeError' object has no attribute 'tb_frame'

If you suspect this is an IPython 7.16.1 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

When I use just python, it works no problem:

```
Python 3.6.13 | packaged by conda-forge | (default, Sep 23 2021, 07:56:31) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from fairseq.data import Dictionary
>>> Dictionary.
Dictionary.add_file_to_dictionary(  Dictionary.bos(                     Dictionary.eos(                     Dictionary.load(                    Dictionary.pad_to_multiple_(        Dictionary.unk(
Dictionary.add_from_file(           Dictionary.dummy_sentence(          Dictionary.finalize(                Dictionary.mro(                     Dictionary.save(                    Dictionary.unk_string(
Dictionary.add_symbol(              Dictionary.encode_line(             Dictionary.index(                   Dictionary.pad(                     Dictionary.string(                  Dictionary.update(
>>> Dictionary.
```

**Comment by cinjon** [comment]
This is an import issue. I needed to do the Fairseq imports in the main module rather than a downstream one.
