### ISSUE TITLE
Recipe doesnt work for Wav2Vec

### ISSUE THREAD

**Issue by bngcode** [facebookresearch/fairseq#3990]
## 📚 Documentation

In the readme the following recipe is provided:
```import torch
import fairseq

cp_path = '/path/to/wav2vec.pt'
model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([cp_path])
model = model[0]
model.eval()

wav_input_16khz = torch.randn(1,10000)
z = model.feature_extractor(wav_input_16khz)
c = model.feature_aggregator(z)
```

when downloading the corresponding wav2vec_large.pt file from here (https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_large.pt) and executing the recipe from above, then an error raises:

> Traceback (most recent call last):
  File "/export/home/lay/Programme/professional pycharm/pycharm-2021.2.1/plugins/python/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/export/home/lay/Programme/professional pycharm/pycharm-2021.2.1/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/export/home/lay/PycharmProjects/df-conformer/toywav2vec.py", line 12, in <module>
    model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([cp_path])
  File "/export/home/lay/PycharmProjects/df-conformer/venv/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 279, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/export/home/lay/PycharmProjects/df-conformer/venv/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 232, in load_checkpoint_to_cpu
    state = _upgrade_state_dict(state)
  File "/export/home/lay/PycharmProjects/df-conformer/venv/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 434, in _upgrade_state_dict
    registry.set_defaults(state["args"], tasks.TASK_REGISTRY[state["args"].task])
KeyError: 'speech_pretraining'

Process finished with exit code 1

**Comment by wantt** [comment]
same problem need to fix
