### ISSUE TITLE
distribute training on muiti-nodes

### ISSUE THREAD

**Issue by liu-x-p** [facebookresearch/fairseq#4051]
Hi, i'm trying to train a wav2vec 2.0 model on 8 nodes(4 GPUs each node) and totally 32 GPUs.(with slurm clusters)

Firstly I used srun to submitted the task with the command
`srun -N 8  fairseq-hydra-train     task.data=/mnt/ieu-fs/fairseqforgiga/manifest/giga/seg/     --config-dir ./examples/wav2vec/config/pretraining     --config-name wav2vec2_base_librispeech`
but it got error `world size is 32 but have 4 available devices`. I changed _world size_ to 4 but I think the 8 nodes will run the experiment independently in this way.

I found the commands in getting_started.rst and the command I used is
`srun -N 8 fairseq-train  --distributed-port 12345   task.data=/mnt/ieu-fs/fairseqforgiga/manifest/giga/seg/     --config-dir ./examples/wav2vec/config/pretraining     --config-name wav2vec2_base_librispeech`
and the error
```
Traceback (most recent call last):
  File "/mnt/ieu-fs/opt/anaconda3/envs/s3prlmaster/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq==1.0.0a0', 'console_scripts', 'fairseq-train')())
  File "/mnt/ieu-fs/opt/anaconda3/envs/s3prlmaster/lib/python3.8/site-packages/fairseq-1.0.0a0-py3.8-linux-x86_64.egg/fairseq_cli/train.py", line 432, in cli_main
    args = options.parse_args_and_arch(parser, modify_parser=modify_parser)
  File "/mnt/ieu-fs/opt/anaconda3/envs/s3prlmaster/lib/python3.8/site-packages/fairseq-1.0.0a0-py3.8-linux-x86_64.egg/fairseq/options.py", line 142, in parse_args_and_arch
    raise RuntimeError()
RuntimeError
srun: error: node01: task 0: Exited with exit code 1
srun: error: node08: task 6: Exited with exit code 1
srun: error: node04: task 3: Exited with exit code 1
srun: error: node07: task 5: Exited with exit code 1
srun: error: node03: task 2: Exited with exit code 1
srun: error: node09: task 7: Exited with exit code 1
srun: error: node02: task 1: Exited with exit code 1
srun: error: node06: task 4: Exited with exit code 1
```
and if I use  `srun -N 8 fairseq-hydra-train  --distributed-port 12345   task.data=/mnt/ieu-fs/fairseqforgiga/manifest/giga/seg/     --config-dir ./examples/wav2vec/config/pretraining     --config-name wav2vec2_base_librispeech` it will report `unrecognized arguments: --distributed-port`

Could you help me with it?
I use fairseq-1.0.0a0 and python 3.8 and torch 1.7.1.

**Comment by liu-x-p** [comment]
I used  `srun -N 8 fairseq-hydra-train distributed_training.distributed-port=12345 task.data=/mnt/ieu-fs/fairseqforgiga/manifest/giga/seg/ --config-dir ./examples/wav2vec/config/pretraining --config-name wav2vec2_base_librispeech` and it works.
