### ISSUE TITLE
Problem about parameter "--iter-decode-with-beam"

### ISSUE THREAD

**Issue by Rexbalaeniceps** [facebookresearch/fairseq#4063]
## 🐛 Can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first

After training the CMLM Model which is a NAT model, I try to translate the test data. I added `--iter-decode-with-beam 5`  hoping the length beam search, but I got the following error:
```
TypeError: Can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first
```

My `translate.sh` script is :
```bash
CUDA_VISIBLE_DEVICES=3 fairseq-generate \
    /data/wbxu/fairseq-main/data-bin/wmt14.tokenized.de-en \
    --gen-subset test \
    --task translation_lev \
    --path /data/wbxu/fairseq-main/mp2_checkpoints/checkpoint_best.pt \
    --iter-decode-max-iter 12 \
    --iter-decode-force-max-iter \
    --iter-decode-with-beam 5 \
    --iter-decode-eos-penalty 0 \
    --remove-bpe \
    --print-step \
    --batch-size 200
```

Details:
```
2021-12-07 09:58:04 | INFO | fairseq.tasks.translation | [de] dictionary: 33664 types
2021-12-07 09:58:04 | INFO | fairseq.tasks.translation | [en] dictionary: 33664 types
2021-12-07 09:58:04 | INFO | fairseq_cli.generate | loading model(s) from /data/wbxu/fairseq-main/mp2_checkpoints/checkpoint_best.pt
2021-12-07 09:58:09 | INFO | fairseq.data.data_utils | loaded 3,003 examples from: /data/wbxu/fairseq-main/data-bin/wmt14.tokenized.de-en/test.de-en.de
2021-12-07 09:58:09 | INFO | fairseq.data.data_utils | loaded 3,003 examples from: /data/wbxu/fairseq-main/data-bin/wmt14.tokenized.de-en/test.de-en.en
2021-12-07 09:58:09 | INFO | fairseq.tasks.translation | /data/wbxu/fairseq-main/data-bin/wmt14.tokenized.de-en test de-en 3003 examples
Traceback (most recent call last):
  File "/home/wbxu/anaconda3/envs/fairseq_main/bin/fairseq-generate", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-generate')())
  File "/data/wbxu/fairseq-main/fairseq_cli/generate.py", line 413, in cli_main
    main(args)
  File "/data/wbxu/fairseq-main/fairseq_cli/generate.py", line 50, in main
    return _main(cfg, sys.stdout)
  File "/data/wbxu/fairseq-main/fairseq_cli/generate.py", line 206, in _main
    constraints=constraints,
  File "/data/wbxu/fairseq-main/fairseq/tasks/fairseq_task.py", line 538, in inference_step
    models, sample, prefix_tokens=prefix_tokens, constraints=constraints
  File "/home/wbxu/anaconda3/envs/fairseq_main/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/data/wbxu/fairseq-main/fairseq/iterative_refinement_generator.py", line 327, in generate
    for i in range(len(finalized) // self.beam_size)
  File "/data/wbxu/fairseq-main/fairseq/iterative_refinement_generator.py", line 327, in <listcomp>
    for i in range(len(finalized) // self.beam_size)
  File "<__array_function__ internals>", line 6, in argmax
  File "/home/wbxu/anaconda3/envs/fairseq_main/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 1195, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "/home/wbxu/anaconda3/envs/fairseq_main/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/home/wbxu/anaconda3/envs/fairseq_main/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
  File "/home/wbxu/anaconda3/envs/fairseq_main/lib/python3.7/site-packages/torch/_tensor.py", line 678, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```

### Environment

 - fairseq Version : 1.0.0a0
 - PyTorch Version : 1.10.0
 - OS (e.g., Linux): Linux
 - How you installed fairseq : source
 - Build command you used : pip install --editable ./
 - Python version: 3.7.11
 - CUDA/cuDNN version: a GPU 3090 with cuda 10.0

**Comment by zareami10** [comment]
Facing the same issue using bleu (beam) when using multiple GPUs.

**Comment by BaohaoLiao** [comment]
You only need to change this [line](https://github.com/facebookresearch/fairseq/blob/ad0e69cd99e1ff884041fbd8467d1404bd09847a/fairseq/iterative_refinement_generator.py#L302) to
`finalized[self.beam_size * i + j][0]["score"].cpu()`
