### ISSUE TITLE
error when loading model from downloaded hubert_large_ll60k.pt

### ISSUE THREAD

**Issue by housebaby** [facebookresearch/fairseq#4070]
python
import fairseq
ckpt_path="/home/storage15/user/tools/espnet-newest/egs2/librispeech/asr1/hub/hubert_large_ll60k.pt"
models, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([ckpt_path])

Python 3.8.12 (default, Oct 12 2021, 13:49:34) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fairseq; ckpt_path=/home/storage15/huangying/tools/espnet-newest/egs2/librispeech/asr1/hub/hubert_large_ll60k.pt; models, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([ckpt_path])
  File "<stdin>", line 1
    import fairseq; ckpt_path=/home/storage15/huangying/tools/espnet-newest/egs2/librispeech/asr1/hub/hubert_large_ll60k.pt; models, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([ckpt_path])
                              ^
SyntaxError: invalid syntax
>>> import fairseq; ckpt_path="/home/storage15/huangying/tools/espnet-newest/egs2/librispeech/asr1/hub/hubert_large_ll60k.pt"; models, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([ckpt_path])
2021-12-10 13:54:30 | INFO | fairseq.tasks.hubert_pretraining | current directory is /home/storage15/huangying/tools/espnet-newest/tools/fairseq
2021-12-10 13:54:30 | INFO | fairseq.tasks.hubert_pretraining | HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': '/checkpoint/wnhsu/data/librivox', 'fine_tuning': False, 'labels': ['lyr9.km500'], 'label_dir': '/checkpoint/wnhsu/experiments/hubert/kmeans_20210121/km_dataset_librivox.model_iter_2.all', 'label_rate': 50, 'sample_rate': 16000, 'normalize': True, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
2021-12-10 13:54:30 | INFO | fairseq.models.hubert.hubert | HubertModel Config: {'_name': 'hubert', 'label_rate': 50, 'extractor_mode': layer_norm, 'encoder_layers': 24, 'encoder_embed_dim': 1024, 'encoder_ffn_embed_dim': 4096, 'encoder_attention_heads': 16, 'activation_fn': gelu, 'dropout': 0.0, 'attention_dropout': 0.0, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.0, 'dropout_input': 0.0, 'dropout_features': 0.0, 'final_dim': 768, 'untie_final_proj': True, 'layer_norm_first': True, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 1.0, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': True}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/storage15/huangying/tools/espnet-newest/tools/fairseq/fairseq/checkpoint_utils.py", line 462, in load_model_ensemble_and_task
    model = task.build_model(cfg.model)
  File "/home/storage15/huangying/tools/espnet-newest/tools/fairseq/fairseq/tasks/fairseq_task.py", line 335, in build_model
    model = models.build_model(cfg, self)
  File "/home/storage15/huangying/tools/espnet-newest/tools/fairseq/fairseq/models/__init__.py", line 105, in build_model
    return model.build_model(cfg, task)
  File "/home/storage15/huangying/tools/espnet-newest/tools/fairseq/fairseq/models/hubert/hubert.py", line 302, in build_model
    model = HubertModel(cfg, task.cfg, task.dictionaries)
  File "/home/storage15/huangying/tools/espnet-newest/tools/fairseq/fairseq/models/hubert/hubert.py", line 265, in __init__
    self.encoder = TransformerEncoder(cfg)
  File "/home/storage15/huangying/tools/espnet-newest/tools/fairseq/fairseq/models/wav2vec/wav2vec2.py", line 857, in __init__
    if args.checkpoint_activations:
  File "/home/storage15/huangying/tools/anaconda3/envs/espnet/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 305, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/home/storage15/huangying/tools/anaconda3/envs/espnet/lib/python3.8/site-packages/omegaconf/base.py", line 95, in _format_and_raise
    format_and_raise(
  File "/home/storage15/huangying/tools/anaconda3/envs/espnet/lib/python3.8/site-packages/omegaconf/_utils.py", line 629, in format_and_raise
    _raise(ex, cause)
  File "/home/storage15/huangying/tools/anaconda3/envs/espnet/lib/python3.8/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
  File "/home/storage15/huangying/tools/anaconda3/envs/espnet/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 303, in __getattr__
    return self._get_impl(key=key, default_value=DEFAULT_VALUE_MARKER)
  File "/home/storage15/huangying/tools/anaconda3/envs/espnet/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 361, in _get_impl
    node = self._get_node(key=key)
  File "/home/storage15/huangying/tools/anaconda3/envs/espnet/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 383, in _get_node
    self._validate_get(key)
  File "/home/storage15/huangying/tools/anaconda3/envs/espnet/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 135, in _validate_get
    self._format_and_raise(
  File "/home/storage15/huangying/tools/anaconda3/envs/espnet/lib/python3.8/site-packages/omegaconf/base.py", line 95, in _format_and_raise
    format_and_raise(
  File "/home/storage15/huangying/tools/anaconda3/envs/espnet/lib/python3.8/site-packages/omegaconf/_utils.py", line 694, in format_and_raise
    _raise(ex, cause)
  File "/home/storage15/huangying/tools/anaconda3/envs/espnet/lib/python3.8/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ConfigAttributeError: Key 'checkpoint_activations' not in 'HubertConfig'
	full_key: checkpoint_activations
	reference_type=Optional[HubertConfig]
	object_type=HubertConfig

**Comment by LinaSunny** [comment]
+1

**Comment by wnhsu** [comment]
The current branch with [this commit] (https://github.com/pytorch/fairseq/commit/272c4c5197250997148fb12c0db6306035f166a4) should fix the bug of requiring to load pre-training dict when loading a fine-tuned checkpoint, and several issues introduced by recent commits (miss config, etc.)
