### ISSUE TITLE
error     raise ex  # set end OC_CAUSE=1 for full backtrace omegaconf.errors.ConfigAttributeError: Key 'crop_seq_to_multiple' is not in struct 	full_key: model.crop_seq_to_multiple 	reference_type=Any 	object_type=dict

### ISSUE THREAD

**Issue by h770347** [facebookresearch/fairseq#4079]
import fairseq
import torch
import torchaudio
import matplotlib.pyplot as plt
from scipy.spatial.distance import cdist
wav2vec2_checkpoint_path = "xlsr_53_56k.pt"
checkpoint = torch.load(wav2vec2_checkpoint_path)
wav2vec2_encoder = fairseq.models.wav2vec.Wav2Vec2Model.build_model(checkpoint['cfg']['model'])
wav2vec2_encoder.load_state_dict(checkpoint['model'])
q_dat, q_sr = torchaudio.load("hello.wav")
r_dat, r_sr = torchaudio.load("goodbye-hello-goodbye.wav")
q_dat = torchaudio.transforms.Resample(q_sr, 16000)(q_dat)
r_dat = torchaudio.transforms.Resample(r_sr, 16000)(r_dat)
query_wav2vec2     = wav2vec2_encoder(q_dat, features_only=True, mask=False)['x'].detach().numpy().squeeze()
reference_wav2vec2 = wav2vec2_encoder(r_dat, features_only=True, mask=False)['x'].detach().numpy().squeeze()
qr_dists_w2v2 = cdist(query_wav2vec2, reference_wav2vec2, 'euclidean', V = None)                    # Calculate distance matrix
qr_dists_w2v2 = ((qr_dists_w2v2 - qr_dists_w2v2.min())/(qr_dists_w2v2.max() - qr_dists_w2v2.min())) # Normalized to [0, 1]
plt.imshow(qr_dists_w2v2, interpolation='none')
plt.show()

# i have this error

**C:\Users\SA\anaconda3\envs\wav2vec_large.pt\lib\site-packages\torch\cuda\__init__.py:80: UserWarning: CUDA initialization: CUDA driver initialization failed, you might not have a CUDA gpu. (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:112.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "C:/Users/SA/PycharmProjects/wav2vec_large.pt/main3.py", line 11, in <module>
    wav2vec2_encoder = fairseq.models.wav2vec.Wav2Vec2Model.build_model(checkpoint['cfg']['model'])
  File "C:\Users\SA\PycharmProjects\wav2vec_large.pt\fairseq\fairseq\models\wav2vec\wav2vec2.py", line 371, in build_model
    return cls(cfg)
  File "C:\Users\SA\PycharmProjects\wav2vec_large.pt\fairseq\fairseq\models\wav2vec\wav2vec2.py", line 277, in __init__
    self.crop_seq_to_multiple = cfg.crop_seq_to_multiple
  File "C:\Users\SA\anaconda3\envs\wav2vec_large.pt\lib\site-packages\omegaconf\dictconfig.py", line 305, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "C:\Users\SA\anaconda3\envs\wav2vec_large.pt\lib\site-packages\omegaconf\base.py", line 101, in _format_and_raise
    type_override=type_override,
  File "C:\Users\SA\anaconda3\envs\wav2vec_large.pt\lib\site-packages\omegaconf\_utils.py", line 629, in format_and_raise
    _raise(ex, cause)
  File "C:\Users\SA\anaconda3\envs\wav2vec_large.pt\lib\site-packages\omegaconf\_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
  File "C:\Users\SA\anaconda3\envs\wav2vec_large.pt\lib\site-packages\omegaconf\dictconfig.py", line 303, in __getattr__
    return self._get_impl(key=key, default_value=DEFAULT_VALUE_MARKER)
  File "C:\Users\SA\anaconda3\envs\wav2vec_large.pt\lib\site-packages\omegaconf\dictconfig.py", line 361, in _get_impl
    node = self._get_node(key=key)
  File "C:\Users\SA\anaconda3\envs\wav2vec_large.pt\lib\site-packages\omegaconf\dictconfig.py", line 383, in _get_node
    self._validate_get(key)
  File "C:\Users\SA\anaconda3\envs\wav2vec_large.pt\lib\site-packages\omegaconf\dictconfig.py", line 136, in _validate_get
    key=key, value=value, cause=ConfigAttributeError(msg)
  File "C:\Users\SA\anaconda3\envs\wav2vec_large.pt\lib\site-packages\omegaconf\base.py", line 101, in _format_and_raise
    type_override=type_override,
  File "C:\Users\SA\anaconda3\envs\wav2vec_large.pt\lib\site-packages\omegaconf\_utils.py", line 694, in format_and_raise
    _raise(ex, cause)
  File "C:\Users\SA\anaconda3\envs\wav2vec_large.pt\lib\site-packages\omegaconf\_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ConfigAttributeError: Key 'crop_seq_to_multiple' is not in struct
	full_key: model.crop_seq_to_multiple
	reference_type=Any
	object_type=dict

Process finished with exit code 1
**

**Comment by kunyao2015** [comment]
same problem ，have you solved it?

**Comment by bpnayak** [comment]
same issue, can someone help me out please

**Comment by Jihyun-mun** [comment]
same issue..
