### ISSUE TITLE
AttributeError: 'Index' object has no attribute '_bin_buffer_mmap' during inference with M2M-100

### ISSUE THREAD

**Issue by ajesujoba** [facebookresearch/fairseq#4096]
I got the above name error while trying to do inference with a finetuned M2M-100.

```
    datasets, data_param_list = self.load_split_datasets(                                                                                                                 File "/home/alabi/anaconda3/envs/py38/lib/python3.8/site-packages/fairseq/data/multilingual/multilingual_data_manager.py", line 993, in load_split_datasets               datasets = [
  File "/home/alabi/anaconda3/envs/py38/lib/python3.8/site-packages/fairseq/data/multilingual/multilingual_data_manager.py", line 996, in <listcomp>
    self.load_a_dataset(
  File "/home/alabi/anaconda3/envs/py38/lib/python3.8/site-packages/fairseq/data/multilingual/multilingual_data_manager.py", line 728, in load_a_dataset
    langpair_ds = self.load_langpair_dataset(
  File "/home/alabi/anaconda3/envs/py38/lib/python3.8/site-packages/fairseq/data/multilingual/multilingual_data_manager.py", line 575, in load_langpair_dataset
    src_dataset, tgt_dataset, align_dataset = self.load_lang_dataset(
  File "/home/alabi/anaconda3/envs/py38/lib/python3.8/site-packages/fairseq/data/multilingual/multilingual_data_manager.py", line 481, in load_lang_dataset
    src_dataset = self.load_data(prefix + src, src_dict, dataset_impl)
  File "/home/alabi/anaconda3/envs/py38/lib/python3.8/site-packages/fairseq/data/multilingual/multilingual_data_manager.py", line 434, in load_data
    dataset = data_utils.load_indexed_dataset(path, vdict, impl)
  File "/home/alabi/anaconda3/envs/py38/lib/python3.8/site-packages/fairseq/data/data_utils.py", line 94, in load_indexed_dataset
    dataset = indexed_dataset.make_dataset(
  File "/home/alabi/anaconda3/envs/py38/lib/python3.8/site-packages/fairseq/data/indexed_dataset.py", line 68, in make_dataset
    return MMapIndexedDataset(path)
  File "/home/alabi/anaconda3/envs/py38/lib/python3.8/site-packages/fairseq/data/indexed_dataset.py", line 468, in __init__
    self._do_init(path)
  File "/home/alabi/anaconda3/envs/py38/lib/python3.8/site-packages/fairseq/data/indexed_dataset.py", line 478, in _do_init
    self._index = self.Index(index_file_path(self._path))
  File "/home/alabi/anaconda3/envs/py38/lib/python3.8/site-packages/fairseq/data/indexed_dataset.py", line 422, in __init__
    self._dtype = dtypes[dtype_code]
KeyError: 9
Exception ignored in: <function MMapIndexedDataset.Index.__del__ at 0x7fef5d2f31f0>
Traceback (most recent call last):
  File "/home/alabi/anaconda3/envs/py38/lib/python3.8/site-packages/fairseq/data/indexed_dataset.py", line 443, in __del__
    self._bin_buffer_mmap._mmap.close()
AttributeError: 'Index' object has no attribute '_bin_buffer_mmap'
Exception ignored in: <function MMapIndexedDataset.__del__ at 0x7fef5d2f3700>
Traceback (most recent call last):
  File "/home/alabi/anaconda3/envs/py38/lib/python3.8/site-packages/fairseq/data/indexed_dataset.py", line 487, in __del__
    self._bin_buffer_mmap._mmap.close()
  File "/home/alabi/anaconda3/envs/py38/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 83, in __getattr__
    raise AttributeError
AttributeError:
```

How do I resolve it?

**Comment by zhengkangjie** [comment]
I have meet the same problem. Is there any solution now?

**Comment by nikhiljaiswal** [comment]
any updates on this?

**Comment by gayanechilingar** [comment]
I had the same issue. You can debug the code. Maybe your path doesn't correct.

**Comment by learnercat** [comment]
I also had the same issue, "AttributeError: 'MMapIndexedDataset' object has no attribute '_bin_buffer_mmap'". Any update solution?

**Comment by telmop** [comment]
I recently ran into the same issue. In my case, the problem was that the binarized data from `fairseq-preprocess` had been generated with an older version of `fairseq`. Regenerating with the same version as that of the training script fixed the problem.
