### ISSUE TITLE
wav2vec_ctc is not found in MODEL_REGISTRY

### ISSUE THREAD

**Issue by ishalyminov** [facebookresearch/fairseq#4128]
## 🐛 Bug

When running a wav2vec2 fine-tuning task with fairseq-hydra-train, an error arises that (as I confirmed in pdb) model name `wav2vec_ctc` is not found in MODEL_REGISTRY

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run `fairseq-hydra-train     --config-dir /home/ec2-user/SageMaker/fairseq/examples/wav2vec/config/finetuning     --config-name commonvoice_10h`
2. Model section from my config `commonvoice_10h`: 
```
model:
  _name: wav2vec_ctc
  w2v_path: /home/ishalyminov/data/fairseq/examples/wav2vec/xlsr_53_56k.pt
  apply_mask: true
  mask_prob: 0.75
  mask_channel_prob: 0.25
  mask_channel_length: 64
  layerdrop: 0.1
  activation_dropout: 0.1
  feature_grad_mult: 0.0
  freeze_finetune_updates: 10000
```
3. See error:
```
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/fairseq/fairseq_cli/hydra_train.py", line 27, in hydra_main
    _hydra_main(cfg)
  File "/home/ec2-user/SageMaker/fairseq/fairseq_cli/hydra_train.py", line 56, in _hydra_main
    distributed_utils.call_main(cfg, pre_main, **kwargs)
  File "/home/ec2-user/SageMaker/fairseq/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "/home/ec2-user/SageMaker/fairseq/fairseq_cli/train.py", line 94, in main
    model = task.build_model(cfg.model)
  File "/home/ec2-user/SageMaker/fairseq/fairseq/tasks/audio_finetuning.py", line 193, in build_model
    model = super().build_model(model_cfg)
  File "/home/ec2-user/SageMaker/fairseq/fairseq/tasks/audio_pretraining.py", line 197, in build_model
    model = super().build_model(model_cfg)
  File "/home/ec2-user/SageMaker/fairseq/fairseq/tasks/fairseq_task.py", line 335, in build_model
    model = models.build_model(cfg, self)
  File "/home/ec2-user/SageMaker/fairseq/fairseq/models/__init__.py", line 100, in build_model
    f"Could not infer model type from {cfg}. "
KeyError: "'_name'"
```
### Expected behavior

Model trains

### Environment

 - fairseq Version (e.g., 1.0 or main): main
 - PyTorch Version (e.g., 1.0) 1.10.1
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): pip install -e .
 - Build command you used (if compiling from source):
 - Python version: 3.9
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration:
 - Any other relevant information:

**Comment by ishalyminov** [comment]
Looks like it was something to do with the conda/Python environment - after I re-created it, the problem went away.
Still, it doesn't quite make sense why I was seeing this error and not python/conda/cuda-related errors.
