### ISSUE TITLE
train crashes with numpy.ndarray size changed, binary incompatibility

### ISSUE THREAD

**Issue by jlquinn** [facebookresearch/fairseq#4173]
## 🐛 Bug

I'm trying to train a model for the first time with fairseq, preparing to do some model arch development.  I suspect an installation issue:

2022-02-01 12:49:23 | INFO | fairseq.tasks.translation | data-bin/data-preproc train zh-en 14017695 examples
2022-02-01 12:49:28 | WARNING | fairseq.tasks.fairseq_task | 6 samples have invalid sizes and will be skipped, max_positions=(1024, 1024), first few sample ids=[13606376, 8062677, 5575106, 13042508, 2327215, 2181534]
Traceback (most recent call last):
  File "/u/jlquinn/jlquinn-mt/gaama/conda.x86/envs/pt110/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/dccstor/jlquinn-mt/fairseq/fairseq_cli/train.py", line 352, in cli_main
    distributed_utils.call_main(args, main)
  File "/dccstor/jlquinn-mt/fairseq/fairseq/distributed_utils.py", line 301, in call_main
    main(args, **kwargs)
  File "/dccstor/jlquinn-mt/fairseq/fairseq_cli/train.py", line 110, in main
    extra_state, epoch_itr = checkpoint_utils.load_checkpoint(
  File "/dccstor/jlquinn-mt/fairseq/fairseq/checkpoint_utils.py", line 212, in load_checkpoint
    epoch_itr = trainer.get_train_iterator(
  File "/dccstor/jlquinn-mt/fairseq/fairseq/trainer.py", line 363, in get_train_iterator
    batch_iterator = self.task.get_batch_iterator(
  File "/dccstor/jlquinn-mt/fairseq/fairseq/tasks/fairseq_task.py", line 232, in get_batch_iterator
    batch_sampler = dataset.batch_by_size(
  File "/dccstor/jlquinn-mt/fairseq/fairseq/data/fairseq_dataset.py", line 132, in batch_by_size
    return data_utils.batch_by_size(
  File "/dccstor/jlquinn-mt/fairseq/fairseq/data/data_utils.py", line 303, in batch_by_size
    from fairseq.data.data_utils_fast import (
  File "fairseq/data/data_utils_fast.pyx", line 1, in init fairseq.data.data_utils_fast
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 80 from PyObject

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd '....'
2. See error

### Environment

fairseq installed with `pip install -e ./
(pt110) [jlquinn@cccxc525 fairseq]$ git branch
* (HEAD detached at v0.10.2)

(pt110) [jlquinn@cccxc525 base]$ conda list
# packages in environment at /u/jlquinn/jlquinn-mt/gaama/conda.x86/envs/pt110:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
antlr4-python3-runtime    4.8                      pypi_0    pypi
blas                      1.0                         mkl  
ca-certificates           2021.10.26           h06a4308_2  
certifi                   2021.10.8        py38h06a4308_2  
cffi                      1.15.0                   pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
cudatoolkit               11.3.1               h2bc3f7f_2  
cython                    0.29.27                  pypi_0    pypi
dataclasses               0.6                      pypi_0    pypi
fairseq                   0.10.2                    dev_0    <develop>
hydra-core                1.1.1                    pypi_0    pypi
importlib-resources       5.4.0                    pypi_0    pypi
intel-openmp              2022.0.1          h06a4308_3633  
ld_impl_linux-64          2.35.1               h7274673_9  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgomp                   9.3.0               h5101ec6_17  
libstdcxx-ng              9.3.0               hd4cf53a_17  
libuv                     1.40.0               h7b6447c_0  
mkl                       2020.2                      256  
mkl-service               2.3.0            py38he904b0f_0  
mkl_fft                   1.3.0            py38h54f3939_0  
mkl_random                1.1.1            py38h0573a6f_0  
ncurses                   6.3                  h7f8727e_2  
numpy                     1.19.2           py38h54aff64_0  
numpy-base                1.19.2           py38hfa32c7d_0  
omegaconf                 2.1.1                    pypi_0    pypi
openssl                   1.1.1m               h7f8727e_0  
pip                       21.2.4           py38h06a4308_0  
portalocker               2.3.2                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
python                    3.8.12               h12debd9_0  
pytorch                   1.10.2          py3.8_cuda11.3_cudnn8.2.0_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pyyaml                    6.0                      pypi_0    pypi
readline                  8.1.2                h7f8727e_1  
regex                     2022.1.18                pypi_0    pypi
sacrebleu                 2.0.0                    pypi_0    pypi
setuptools                58.0.4           py38h06a4308_0  
six                       1.16.0             pyhd3eb1b0_0  
sqlite                    3.37.0               hc218d9a_0  
tabulate                  0.8.9                    pypi_0    pypi
tk                        8.6.11               h1ccaba5_0  
torch                     1.10.2                   pypi_0    pypi
tqdm                      4.62.3                   pypi_0    pypi
typing-extensions         4.0.1                    pypi_0    pypi
typing_extensions         3.10.0.2           pyh06a4308_0  
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
zipp                      3.7.0                    pypi_0    pypi
zlib                      1.2.11               h7f8727e_4  

OS:  RHEL 8.5
NV driver: | NVIDIA-SMI 495.29.05    Driver Version: 495.29.05    CUDA Version: 11.5     |
GPU: 87:00.0 3D controller: NVIDIA Corporation GA100 [A100 SXM4 40GB] (rev a1)
  8 GPUs in shared system, I'm assigned to 1

I first tried with python 3.9 (what I got by default), but fairseq fails to read the num-tokens argument with an argument type issue reported elsewhere.

I first convert the data that is already tokenized and BPE'd as follows:

fairseq-preprocess -s zh -t en --destdir data-bin/data-preproc/ --tokenizer space --trainpref train.2.bpe.uniq --validpref newstest2018.txt.bpe,newstest2018.txt.bpe.rbm --testpref newstest2019-zhen.txt.bpe,newstest2019-zhen.txt.bpe.rbm

Then I ran training with:

fairseq-train data-bin/data-preproc -s zh -t en --fp16 --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --lr 0.0005 --lr-scheduler inverse_sqrt --warmup-updates 4000 --warmup-init-lr 1e-07 --dropout 0.3 --weight-decay 0.0 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --tokenizer space --validate-interval-updates 1000 -a transformer_wmt_en_de --save-dir try1/ --save-interval-updates 10000 --max-tokens 4000

This is an initial kick-the-tires run.

 - fairseq Version (e.g., 1.0 or main):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by jlquinn** [comment]
v0.9.0 works.  v0.10.0 doesn't install.  v0.10.1 has the same issue as v0.10.2.

**Comment by jlquinn** [comment]
OK, I don't know exactly what I did differently.  However, I did the following:
pip uninstall numpy
conda install --force-reinstall numpy
git checkout v0.10.2
pip pinstall -e ./

This last pulled in numpy 1.22.1.  Now, my installation works without crashing.

**Comment by jlquinn** [comment]
Apparently, conda doesn't have a numpy 1.22 build yet.
