### ISSUE TITLE
install issue a100

### ISSUE THREAD

**Issue by brando90** [facebookresearch/fairseq#4176]
```
Collecting fairseq
  Downloading fairseq-0.10.2.tar.gz (938 kB)
     |████████████████████████████████| 938 kB 136.8 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/miranda9/miniconda3/envs/meta_learning_a100/bin/python /home/miranda9/miniconda3/envs/meta_learning_a100/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp66m6bz1d
       cwd: /tmp/pip-install-wardjzl2/fairseq_3c7e083893384825aafa47c25fee117a
  Complete output (31 lines):
  Traceback (most recent call last):
    File "setup.py", line 214, in <module>
      do_setup(package_data)
    File "setup.py", line 136, in do_setup
      setup(
    File "/tmp/pip-build-env-01hn89rg/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 154, in setup
      _install_setup_requires(attrs)
    File "/tmp/pip-build-env-01hn89rg/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 148, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "/tmp/pip-build-env-01hn89rg/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 61, in fetch_build_eggs
      raise SetupRequirementsError(specifier_list)
  setuptools.build_meta.SetupRequirementsError: ['cython', 'numpy', 'setuptools>=18.0']
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/home/miranda9/miniconda3/envs/meta_learning_a100/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/home/miranda9/miniconda3/envs/meta_learning_a100/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/miranda9/miniconda3/envs/meta_learning_a100/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 117, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-01hn89rg/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-01hn89rg/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-01hn89rg/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 217, in <module>
      os.unlink(fairseq_examples)
  IsADirectoryError: [Errno 21] Is a directory: 'fairseq/examples'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/02/59/1f466d82d64482e2809a167e0067979c23057b3752e668537d5ff24453c9/fairseq-0.10.2.tar.gz#sha256=45b90d8ccc3f5a4623a523fe2d0465f54413d03fd1ec9a9d7af0461148ca1a68 (from https://pypi.org/simple/fairseq/). Command errored out with exit status 1: /home/miranda9/miniconda3/envs/meta_learning_a100/bin/python /home/miranda9/miniconda3/envs/meta_learning_a100/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp66m6bz1d Check the logs for full command output.
  Downloading fairseq-0.10.1.tar.gz (924 kB)
     |████████████████████████████████| 924 kB 97.2 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/miranda9/miniconda3/envs/meta_learning_a100/bin/python /home/miranda9/miniconda3/envs/meta_learning_a100/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp_em9w888
       cwd: /tmp/pip-install-wardjzl2/fairseq_edfe4db42eee4997aaa9e0407d849fde
  Complete output (31 lines):
  Traceback (most recent call last):
    File "setup.py", line 214, in <module>
      do_setup(package_data)
    File "setup.py", line 136, in do_setup
      setup(
    File "/tmp/pip-build-env-0e99j5dd/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 154, in setup
      _install_setup_requires(attrs)
    File "/tmp/pip-build-env-0e99j5dd/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 148, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "/tmp/pip-build-env-0e99j5dd/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 61, in fetch_build_eggs
      raise SetupRequirementsError(specifier_list)
  setuptools.build_meta.SetupRequirementsError: ['cython', 'numpy', 'setuptools>=18.0']
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/home/miranda9/miniconda3/envs/meta_learning_a100/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/home/miranda9/miniconda3/envs/meta_learning_a100/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/miranda9/miniconda3/envs/meta_learning_a100/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 117, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-0e99j5dd/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-0e99j5dd/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-0e99j5dd/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 217, in <module>
      os.unlink(fairseq_examples)
  IsADirectoryError: [Errno 21] Is a directory: 'fairseq/examples'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/52/00/8668312a50a607d1ceb4a6f0804662a04f7b029857679f518a2ec4777d75/fairseq-0.10.1.tar.gz#sha256=05b9e6bea4fc974b33e0ee5c154ec4069c6996be30c53d3ea8dd6d13113170f2 (from https://pypi.org/simple/fairseq/). Command errored out with exit status 1: /home/miranda9/miniconda3/envs/meta_learning_a100/bin/python /home/miranda9/miniconda3/envs/meta_learning_a100/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp_em9w888 Check the logs for full command output.
```

**Comment by genesith** [comment]
Exact same issue, also working with A100

**Comment by brando90** [comment]
I just did pip install again and it worked. Did you try that?

**Comment by brando90** [comment]
now I am getting an issue in my new mac book pro m1 max:
```
Collecting fairseq
  Using cached fairseq-0.10.2.tar.gz (938 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      Traceback (most recent call last):
        File "setup.py", line 214, in <module>
          do_setup(package_data)
        File "setup.py", line 136, in do_setup
          setup(
        File "/private/var/folders/ym/nmb6wx4n4g1c61lp9hwx4h4c0000gn/T/pip-build-env-_ltsgd6x/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 154, in setup
          _install_setup_requires(attrs)
        File "/private/var/folders/ym/nmb6wx4n4g1c61lp9hwx4h4c0000gn/T/pip-build-env-_ltsgd6x/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 148, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/private/var/folders/ym/nmb6wx4n4g1c61lp9hwx4h4c0000gn/T/pip-build-env-_ltsgd6x/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 61, in fetch_build_eggs
          raise SetupRequirementsError(specifier_list)
      setuptools.build_meta.SetupRequirementsError: ['cython', 'numpy', 'setuptools>=18.0']
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Users/brandomiranda/opt/anaconda3/envs/meta_learning_cpu2/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/brandomiranda/opt/anaconda3/envs/meta_learning_cpu2/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/brandomiranda/opt/anaconda3/envs/meta_learning_cpu2/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/ym/nmb6wx4n4g1c61lp9hwx4h4c0000gn/T/pip-build-env-_ltsgd6x/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/private/var/folders/ym/nmb6wx4n4g1c61lp9hwx4h4c0000gn/T/pip-build-env-_ltsgd6x/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/ym/nmb6wx4n4g1c61lp9hwx4h4c0000gn/T/pip-build-env-_ltsgd6x/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 217, in <module>
          os.unlink(fairseq_examples)
      PermissionError: [Errno 1] Operation not permitted: 'fairseq/examples'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by genesith** [comment]
> I just did pip install again and it worked. Did you try that?

what did you change? I've been experimenting for a few days and I can't get pip install to work. I'm using 
`setup.py build develop`

**Comment by Dobatymo** [comment]
This is the same issue, just for Windows https://github.com/pytorch/fairseq/issues/3194

**Comment by xunshengliuyin** [comment]
Try to run this    pip install -v --no-cache-dir fairseq
