### ISSUE TITLE
ImportError: fused_layer_norm_cuda.cpython-38-x86_64-linux-gnu.so: undefined symbol

### ISSUE THREAD

**Issue by clumsy** [facebookresearch/fairseq#4246]
## 🐛 Bug

`ImportError: /usr/local/lib/python3.8/dist-packages/fused_layer_norm_cuda.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail14torchCheckFailEPKcS2_jRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE` when fine-tuning __bart_large__ model using translation task with the latest v0.11.0

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd using a __custom__ dataset:
```
python -m torch.distributed.launch --nproc_per_node=4 \
    --nnodes=1 --node_rank=0 \
    --master_addr=$ip \
    --master_port=12345 \
    $(which fairseq-train) $DATA \
    --max-tokens $MAX_TOKENS \
    --task translation \
    --source-lang iq --target-lang oq \
    --truncate-source \
    --layernorm-embedding \
    --share-all-embeddings \
    --share-decoder-input-output-embed \
    --reset-optimizer --reset-dataloader --reset-meters \
    --required-batch-size-multiple 1 \
    --arch bart_large \
    --criterion label_smoothed_cross_entropy \
    --label-smoothing 0.1 \
    --dropout 0.1 --attention-dropout 0.1 \
    --weight-decay 0.01 --optimizer adam --adam-betas "(0.9, 0.999)" --adam-eps 1e-08 \
    --clip-norm 0.1 \
    --lr-scheduler polynomial_decay --lr $LR --total-num-update $TOTAL_NUM_UPDATES --warmup-updates $WARMUP_UPDATES \
    --fp16 --update-freq $UPDATE_FREQ \
    --skip-invalid-size-inputs-valid-test \
    --find-unused-parameters;
```
3. See error
```
Traceback (most recent call last):
  File "/usr/local/bin/fairseq-train", line 8, in <module>
    sys.exit(cli_main())
  File "/usr/local/lib/python3.8/dist-packages/fairseq_cli/train.py", line 535, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/usr/local/lib/python3.8/dist-packages/fairseq/distributed/utils.py", line 354, in call_main
    distributed_main(cfg.distributed_training.device_id, main, cfg, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/fairseq/distributed/utils.py", line 328, in distributed_main
    main(cfg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/fairseq_cli/train.py", line 94, in main
    model = fsdp_wrap(task.build_model(cfg.model))
  File "/usr/local/lib/python3.8/dist-packages/fairseq/tasks/translation.py", line 369, in build_model
    model = super().build_model(cfg, from_checkpoint)
  File "/usr/local/lib/python3.8/dist-packages/fairseq/tasks/fairseq_task.py", line 335, in build_model
    model = models.build_model(cfg, self, from_checkpoint)
  File "/usr/local/lib/python3.8/dist-packages/fairseq/models/__init__.py", line 106, in build_model
    return model.build_model(cfg, task)
  File "/usr/local/lib/python3.8/dist-packages/fairseq/models/transformer/transformer_legacy.py", line 133, in build_model
    return super().build_model(cfg, task)
  File "/usr/local/lib/python3.8/dist-packages/fairseq/models/transformer/transformer_base.py", line 97, in build_model
    encoder = cls.build_encoder(cfg, src_dict, encoder_embed_tokens)
  File "/usr/local/lib/python3.8/dist-packages/fairseq/models/transformer/transformer_legacy.py", line 143, in build_encoder
    return super().build_encoder(
  File "/usr/local/lib/python3.8/dist-packages/fairseq/models/transformer/transformer_base.py", line 119, in build_encoder
    return TransformerEncoderBase(cfg, src_dict, embed_tokens)
  File "/usr/local/lib/python3.8/dist-packages/fairseq/models/transformer/transformer_encoder.py", line 79, in __init__
    self.layernorm_embedding = LayerNorm(embed_dim, export=cfg.export)
  File "/usr/local/lib/python3.8/dist-packages/fairseq/modules/layer_norm.py", line 32, in LayerNorm
    return FusedLayerNorm(normalized_shape, eps, elementwise_affine)
  File "/usr/local/lib/python3.8/dist-packages/apex/normalization/fused_layer_norm.py", line 166, in __init__
    fused_layer_norm_cuda = importlib.import_module("fused_layer_norm_cuda")
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1166, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /usr/local/lib/python3.8/dist-packages/fused_layer_norm_cuda.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail14torchCheckFailEPKcS2_jRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

### Expected behavior

This works fine on 0.10.2, but I would like to start using `--ddp-backend fully_sharded` mode thus switching to (unreleased) 0.11.0

### Environment

 - fairseq Version (e.g., 1.0 or main): `0.11.0`
 - PyTorch Version (e.g., 1.0): `1.10.0`
 - OS (e.g., Linux): `Linux x86_64`
 - How you installed fairseq (`pip`, source): `pip3 install of v0.11.0`
 - Build command you used (if compiling from source): `pip3 install --no-dependencies . (PyTorch installation details below)`
 - Python version: `3.8.12`
 - CUDA/cuDNN version: `11.3`
 - GPU models and configuration: `Tesla V100-SXM2-16GB`
 - Any other relevant information: `Using Apex fork: https://github.com/szhengac/apex using --global-option="--cpp_ext" --global-option="--cuda_ext"`

### Additional context

Build as part of a Docker image base on `nvidia/cuda:11.3.0-devel-ubuntu20.04`.

Compiling PyTorch from source:
```DS_BUILD_OPS=1 TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0 7.5 8.0" pip3 install -v . --global-option="build_ext" --global-option="-j$(nproc)"```

Not sure, but it might be related to https://discuss.pytorch.org/t/undefined-symbol-when-import-lltm-cpp-extension/32627

**Comment by clumsy** [comment]
I believe it's because of ABI, same issue as in https://github.com/pytorch/pytorch/issues/13541.
It appears I had `GLIBCXX_USE_CXX11_ABI`/`_GLIBCXX_USE_CXX11_ABI` set to 0 for both PyTorch and Fairseq, but Apex had 1.
Rebuilding with `GLIBCXX_USE_CXX11_ABI`/`_GLIBCXX_USE_CXX11_ABI` set to 1 everywhere __didn't help__.
Trying with 0 everywhere.

**Comment by clumsy** [comment]
Found the problem, one of Fairseq's dependencies in v0.11.0 branch, torchaudio was pulling the latest torch and uninstalling my locally built from source one.

**Comment by ggrantrowberry** [comment]
@clumsy How did you end up fixing this?

**Comment by clumsy** [comment]
@ggrantrowberry I had to use a specific version of PyTorch I compiled for my hardware from source. So I had to install Fairseq with `--no-deps` making sure I have all the dependencies installed beforehand.

**Comment by superhero-7** [comment]
hi, @clumsy  I have the same promblem. So you reinstall all of your environment, and when you was installing the fairseq, you use the `--no-deps` command?

**Comment by longxudou** [comment]
`pip uninstall apex` works for me.

**Comment by cgt-woailol** [comment]
> `pip uninstall apex`对我有用。
thanks! That also works for me!
