### ISSUE TITLE
NameError: name 'CriterionType' is not defined [wav2vec2 evaluation using stt.py]

### ISSUE THREAD

**Issue by 202015004** [facebookresearch/fairseq#4260]
## NameError: name 'CriterionType' is not defined [wav2vec2 evaluation using stt.py]

I'm still facing this issue. I have tried several techniques. Major attempts are listed below 
Installation Setup done using following link setup : 
- fairseq [https://github.com/mailong25/self-supervised-speech-recognition](url)
- python binding and wav2letter  [https://github.com/flashlight/wav2letter/wiki/Building-Python-bindings](url)

#### Code
from stt import Transcriber
transcriber = Transcriber( pretrain_model = 'baseline_trial/Pre-Trained_model/wav2vec_small.pt', finetune_model='outputs/2022-02-27/11-29-48/checkpoints/checkpoint_best.pt', dictionary = 'baseline_trial/dictionary/dict.ltr.txt', lm_type = 'kenlm', lm_lexicon = 'lm/lexicon.txt', lm_model = 'lm/lm.bin',lm_weight = 1.5, word_score = -1, beam_size = 50)
hypos = transcriber.transcribe(['/home/speechlab/Desktop/Shreya/TLT_2021/ETLT2021_CAMBRIDGE_EN_baseline/ETLT2021_ETS_EN/audio/dev/1000000000018212-VE648280.wav','/home/speechlab/Desktop/Shreya/TLT_2021/ETLT2021_CAMBRIDGE_EN_baseline/ETLT2021_ETS_EN/audio/dev/1000000000018212-VE654794.wav'])
print(hypos) 

#### Error
 /home/speechlab/self-supervised-speech-recognition/libs/fairseq/examples/speech_recognition/w2l_decoder.py:42: UserWarning: wav2letter python bindings are required to use this functionality. Please install from https://github.com/facebookresearch/wav2letter/wiki/Python-bindings
  "wav2letter python bindings are required to use this functionality. Please install from https://github.com/facebookresearch/wav2letter/wiki/Python-bindings"
Traceback (most recent call last):
  File "/home/speechlab/self-supervised-speech-recognition/testing1.py", line 12, in <module>
    transcriber = Transcriber( pretrain_model = 'baseline_trial/Pre-Trained_model/wav2vec_small.pt', finetune_model='outputs/2022-02-27/11-29-48/checkpoints/checkpoint_best.pt', dictionary = 'baseline_trial/dictionary/dict.ltr.txt', lm_type = 'kenlm', lm_lexicon = 'lm/lexicon.txt', lm_model = 'lm/lm.bin',lm_weight = 1.5, word_score = -1, beam_size = 50)
  File "/home/speechlab/self-supervised-speech-recognition/stt.py", line 254, in __init__
    self.transcribe([sample_audio_path])
  File "/home/speechlab/self-supervised-speech-recognition/stt.py", line 359, in transcribe
    generator = build_generator(args)
  File "/home/speechlab/self-supervised-speech-recognition/stt.py", line 347, in build_generator
    return W2lKenLMDecoder(args, task.target_dictionary)
  File "/home/speechlab/self-supervised-speech-recognition/libs/fairseq/examples/speech_recognition/w2l_decoder.py", line 133, in __init__
    super().__init__(args, tgt_dict)
  File "/home/speechlab/self-supervised-speech-recognition/libs/fairseq/examples/speech_recognition/w2l_decoder.py", line 56, in __init__
    self.criterion_type = CriterionType.CTC
NameError: name 'CriterionType' is not defined

#### What have you tried?
As mentioned in [https://github.com/flashlight/flashlight/issues/416#issuecomment-761728139](url); flashlight is installed, while all the modification mentioned for binding are not similar to the script I received after installation of fairseq 

#### What's your environment?
 - PyTorch Version (e.g., 1.0): 1.10.1+cu102
 - OS : Linux 18
 - How you installed fairseq (`pip`, source):  [https://github.com/mailong25/self-supervised-speech-recognition](url)
 - Python version: 3.6
 - CUDA/cuDNN version: 10.2

**Comment by Daeun-Yun** [comment]
I've also strruggled with this  "criteriontype definition"error.
to be honest, I don't know why it works..
but I can guess when cuperviterbipath importing is failed that block importing follwing import codes
we can fix it seperate the code  "from flashlight.lib.sequence.criterion import CpuViterbiPath, get_data_ptr_as_bytes
"from try importing block.
check the changes "#de"

(+)maybe, you can change the posions of the codes (cuperviterbi<->criterion,lexicon,..)

===========================================================

try:
    from flashlight.lib.text.dictionary import create_word_dict, load_words
    #from flashlight.lib.sequence.criterion import CpuViterbiPath, get_data_ptr_as_bytes #de : the problem!!!
    from flashlight.lib.text.decoder import (
        CriterionType,
        LexiconDecoderOptions,
        KenLM,
        LM,
        LMState,
        SmearingMode,
        Trie,
        LexiconDecoder,
    )
except:
    warnings.warn(
        "flashlight python bindings are required to use this functionality. Please install from https://github.com/facebookresearch/flashlight/tree/master/bindings/python"
    )
    LM = object
    LMState = object
try: #seperated problem
    from flashlight.lib.sequence.criterion import CpuViterbiPath, get_data_ptr_as_bytes
except:
    pass
