### ISSUE TITLE
MoE example for COPA/score fails in the moe branch

### ISSUE THREAD

**Issue by awan-10** [facebookresearch/fairseq#4279]
## 🐛 Bug

Trying to run the COPA example for a dense LM on this page (https://github.com/pytorch/fairseq/tree/main/examples/moe_lm) and it fails with the following stack trace. 

Also, there are no instructions to load an MoE checkpoint ([en_moe_lm_52b.tar.gz](https://dl.fbaipublicfiles.com/fairseq/models/lm/en_moe_lm_52b.tar.gz)) for this COPA example. Is that possible? I can create a separate issue/question for it too. 

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Save the COPA example in a file named copa.py
2. Run python copa.py

#### Code sample

**Contents of my copa.py**
```python
from fairseq.models.transformer_lm import TransformerLanguageModel
model_dir = '/home/amawa/downloads/en_dense_lm_125m'
lm = TransformerLanguageModel.from_pretrained(model_dir, bpe='gpt2')
lm = lm.eval();  # disable dropout
lm = lm.half();  # use FP16 for evaluation
lm = lm.cuda();  # move to GPU

def get_logprobs(prompt):
    import re
    prompt = re.sub('\n+' , '\n', prompt)  # collapse repeated newlines, which indicate separate documents
    return lm.score(prompt, replace_newlines_with_eos=True)['positional_scores']

# Zero-shot evaluation for the Choice of Plausible Alternatives (COPA) task.
# A return value of 1 indicates that the first alternative is more plausible,
# while 2 indicates that the second alternative is more plausible.
def COPA_eval(prompt, alternative1, alternative2):
    lprob1 = get_logprobs(prompt + "\n" + alternative1).sum()
    lprob2 = get_logprobs(prompt + "\n" + alternative2).sum()
    return 1 if lprob1 > lprob2 else 2

COPA_eval("The man broke his toe. What was the CAUSE of this?", "He got a hole in his sock.", "He dropped a hammer on his foot.")
COPA_eval("I tipped the bottle. What happened as a RESULT?", "The liquid in the bottle froze.", "The liquid in the bottle poured out.")
COPA_eval("I knocked on my neighbor's door. What happened as a RESULT?", "My neighbor invited me in.", "My neighbor left his house.")
```
**Stack trace:**
```
Traceback (most recent call last):
  File "copa.py", line 21, in <module>
    COPA_eval("The man broke his toe. What was the CAUSE of this?", "He got a hole in his sock.", "He dropped a hammer on his foot.")
  File "copa.py", line 17, in COPA_eval
    lprob1 = get_logprobs(prompt + "\n" + alternative1).sum()
  File "copa.py", line 11, in get_logprobs
    return lm.score(prompt, replace_newlines_with_eos=True)['positional_scores']
  File "/home/amawa/fairseq-moe/fairseq/hub_utils.py", line 170, in score
    return self.score([sentences], **kwargs)[0]
  File "/home/amawa/fairseq-moe/fairseq/hub_utils.py", line 175, in score
    for hypos in self.generate(
  File "/home/amawa/fairseq-moe/fairseq/hub_utils.py", line 201, in generate
    generator = self.task.build_generator(self.models, gen_args)
  File "/home/amawa/fairseq-moe/fairseq/tasks/fairseq_task.py", line 356, in build_generator
    return SequenceScorer(
TypeError: __init__() got an unexpected keyword argument 'compute_vocab_dist'
```

### Expected behavior

Expected output of the three COPA_eval lines are 2, 2, and 1 getting printed. This is the case when you run it for the main branch of fairseq but not for moe branch. 

### Environment

 - fairseq Version (moe):
 - PyTorch Version (1.10)
 - OS (e.g., Linux):
 - How you installed fairseq (source):
 - Build command you used (pip install -e . ):
 - Python version: 38
 - CUDA/cuDNN version: 11.3
 - GPU models and configuration: dense_lm_125m
 - Any other relevant information:

**Comment by tholop-msr** [comment]
I ran into the same problem and fixed it (?) by commenting out this line: https://github.com/facebookresearch/fairseq/blob/ebea0072062e2e8f4563644f27546df355357f5e/fairseq/tasks/fairseq_task.py#L359
