### ISSUE TITLE
Can not evaluate the simultaneous speech translation results

### ISSUE THREAD

**Issue by D-Keqi** [facebookresearch/fairseq#4292]
Hi all! When I try to reproduce the Must-C En-De results of the simultaneous translation model following the tutorial, I come into an issue related to JSON. https://github.com/pytorch/fairseq/blob/main/examples/speech_to_text/docs/simulst_mustc_example.md

Can I get some advice?

The error report is as follows:
Traceback (most recent call last):
  File "/root/anaconda3/envs/fairseq/bin/simuleval", line 33, in <module>
    sys.exit(load_entry_point('simuleval', 'console_scripts', 'simuleval')())
  File "/root/toolkits/SimulEval/simuleval/cli.py", line 165, in main
    _main(args.client_only)
  File "/root/toolkits/SimulEval/simuleval/cli.py", line 192, in _main
    evaluate(args, client, server_process)
  File "/root/toolkits/SimulEval/simuleval/cli.py", line 122, in evaluate
    info = client.corpus_info()
  File "/root/toolkits/SimulEval/simuleval/online/client.py", line 73, in corpus_info
    return r.json()
  File "/root/anaconda3/envs/fairseq/lib/python3.7/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/root/anaconda3/envs/fairseq/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/root/anaconda3/envs/fairseq/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/root/anaconda3/envs/fairseq/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by gowtham1997** [comment]
Did you manage to solve this?
