### ISSUE TITLE
FSDP mode can not continue training from last checkpoint.

### ISSUE THREAD

**Issue by SefaZeng** [facebookresearch/fairseq#4307]
### Before asking:
1. search the issues.
2. search the docs.

#### What is your question?
Under FSDP mode, continue training after the last checkpoint reports error model mismatch
#### Code
training scripts:
```
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
work_dir=/workspace
data_dir=$work_dir/data/${dataname}
  
fairseq_dir=$work_dir/fairseq-git
  
output_dir=$work_dir/checkpoints/baseline
LOG_FILE=$output_dir/log

OMP_NUM_THREADS=20 \
/home/user/miniconda/bin/python3 -m torch.distributed.launch --nproc_per_node=8 \
  --nnodes=${WORLD_SIZE} --node_rank=${RANK} --master_addr=$MASTER_ADDR \
  --master_port=$MASTER_PORT \
  $fairseq_dir/train.py \
  $data_dir \
 --task translation \
 --save-dir $output_dir \
 --arch transformer \
 --attention-dropout 0.1 \
 --activation-dropout 0.1 \
 --dropout 0.1 \
 --encoder-layers 500 \
 --decoder-layers 3 \ 
 --encoder-embed-dim 512 \
 --decoder-embed-dim 512 \
 --encoder-attention-heads 8 \ 
 --encoder-attention-heads 8 \ 
 --encoder-ffn-embed-dim 2048 \
 --decoder-ffn-embed-dim 2048 \
 --optimizer adam --adam-betas '(0.9, 0.98)' --adam-eps 1e-8 --clip-norm 0.0 \
 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 \
 --warmup-init-lr 1e-07 \
 --weight-decay 0.0001 \
 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 \
 --max-tokens 4096 \
 --update-freq 1 \                                                                                                           
 --log-interval 100 \
 --save-interval-updates 1000 \
 --skip-invalid-size-inputs-valid-test \
 --save-interval 100000000000 \
 --num-workers 1 \ 
 --seed 42 \
 --fp16  \
 --ddp-backend=fully_sharded \
 --checkpoint-activations \
 --no-reshard-after-forward \
 2>&1 |tee ${LOG_FILE}
```

Error message:
```
Traceback (most recent call last):
  File "/workspace/fairseq-git/fairseq/trainer.py", line 575, in load_checkpoint
    self.model.load_state_dict(
  File "/workspace/fairseq-git/fairseq/distributed/fully_sharded_data_parallel.py", line 73, in load_state_dict
    state_dict = dist_utils.broadcast_object(
  File "/workspace/fairseq-git/fairseq/distributed/utils.py", line 745, in broadcast_object
    tensors = broadcast_tensors(None, src_rank, group, dist_device)
  File "/workspace/fairseq-git/fairseq/distributed/utils.py", line 717, in broadcast_tensors
    broadcast(tensor, src=src_rank, group=group)
  File "/workspace/fairseq-git/fairseq/distributed/utils.py", line 514, in broadcast
    dist.broadcast(tensor, src=src, group=group)
  File "/home/user/miniconda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1163, in broadcast
    work = group.broadcast([tensor], opts)
RuntimeError: NCCL communicator was aborted on rank 1.  Original reason for failure was: NCCL error: unhandled system error, NCCL version 21.0.3
ncclSystemError: System call (socket, malloc, munmap, etc) failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/fairseq-git/train.py", line 14, in <module>
    cli_main()
  File "/workspace/fairseq-git/fairseq_cli/train.py", line 541, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/workspace/fairseq-git/fairseq/distributed/utils.py", line 354, in call_main
    distributed_main(cfg.distributed_training.device_id, main, cfg, kwargs)
  File "/workspace/fairseq-git/fairseq/distributed/utils.py", line 328, in distributed_main
    main(cfg, **kwargs)
  File "/workspace/fairseq-git/fairseq_cli/train.py", line 170, in main
    extra_state, epoch_itr = checkpoint_utils.load_checkpoint(
  File "/workspace/fairseq-git/fairseq/checkpoint_utils.py", line 248, in load_checkpoint
    extra_state = trainer.load_checkpoint(
  File "/workspace/fairseq-git/fairseq/trainer.py", line 588, in load_checkpoint
    raise Exception(
Exception: Cannot load model parameters from checkpoint /workspace/checkpoints/baseline/checkpoint_last.pt; please ensure that the architectures match.
```

#### What's your environment?

 - fairseq Version (e.g., 1.0 or main): main
 - PyTorch Version (e.g., 1.0) 1.10
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version: Python3.8
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by SefaZeng** [comment]
You need more Memory for loading the prev checkpoint than training from scratch.
