### ISSUE TITLE
Is constrained decoding supported in fairseq-genrate?

### ISSUE THREAD

**Issue by rangehow** [facebookresearch/fairseq#4332]
Dear @mjpost 
I tried to use `--constraints` which is provided in the [argument list](https://fairseq.readthedocs.io/en/latest/command_line_tools.html#fairseq-generate) of `fairseq-generate`. But there is an error occured,
> Traceback (most recent call last):
  File "fairseq-generate", line 8, in <module>
    sys.exit(cli_main())
  File "fairseq_cli/generate.py", line 381, in cli_main
    main(args)
  File "fairseq_cli/generate.py", line 41, in main
    return _main(args, sys.stdout)
  File "fairseq_cli/generate.py", line 198, in _main
    constraints=constraints,
  File "fairseq/tasks/fairseq_task.py", line 434, in inference_step
    models, sample, prefix_tokens=prefix_tokens, constraints=constraints
  File "torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "fairseq/sequence_generator.py", line 177, in generate
    return self._generate(sample, **kwargs)
  File "fairseq/sequence_generator.py", line 222, in _generate
    self.search.init_constraints(constraints, beam_size)
  File "fairseq/search.py", line 239, in init_constraints
    for constraint_tensor in batch_constraints:
TypeError: 'NoneType' object is not iterable

which is related to the code you PR ago [generate.py line 153-155](https://github.com/pytorch/fairseq/pull/2402/files#diff-a578021e44c909b13293bc52a591bceb2a5e33b3333f6b4dd6cd38bedde86d7eR153-R155), 
```python
constraints = None
        if "constraints" in sample:
            constraints = sample["constraints"]
```
here gets nothing so constraints remains None in the later infer step.

the step I made is:
1. join test.en (each line is an sentence) and constraint.de (each line consists of  '\tconstraint1\tconstraint2......')
=>test..en.c(each line likes "Two sets of lights so close to one another : intentional or just a silly error ?\tso\tbeieinander\tSchildbürgerstreich")
2. use bpe and fairseq-preprocess
3. run fairseq-generate
```shell
fairseq-generate \
  data-bin/wmt17_en_de \
  --path checkpoint.avg10.pt \
  --beam 10 --lenpen 0.6 --remove-bpe \
  --constraints ordered >data-bin/wmt17_en_de/gen.out

```
Sincerely hope to receive your help and thank you very much.

**Comment by rangehow** [comment]
After checking code in [`tasks/translation.py` L156-170](https://github.com/pytorch/fairseq/blob/31d94f556bd49bc7e61511adbda482b2c54652b5/fairseq/tasks/translation.py#L156)(here has nothing changed in [DBA PR)](https://github.com/pytorch/fairseq/pull/2402/files#diff-a578021e44c909b13293bc52a591bceb2a5e33b3333f6b4dd6cd38bedde86d7e) ,I guess answer is yes. In interactive.py raw input line can be split by '\t' into lines and constraints, but after fairseq-preprocess there is no clear dividing line to split sentence into two part so it's hard to implement this in fairseq-generate.
