### ISSUE TITLE
[Wav2Vec 2.0] Can't load Self-Training version of wav2vec 2.0

### ISSUE THREAD

**Issue by hank0316** [facebookresearch/fairseq#4348]
## 🐛 Bug

I'm trying to load "Wav2Vec 2.0 Large (LV-60) + Self Training" model (The version that fine-tuned for 100hr). 

[Wav2Vec 2.0 Models](https://github.com/pytorch/fairseq/tree/main/examples/wav2vec)
![image](https://user-images.githubusercontent.com/55573473/163137250-7a2ce8b7-18bc-4dc5-9867-3ea8652c57fe.png)

After download the .pt file, I run the code below:

```python
(test) dlhlp2022@jn4ur7ctr1649659392715-ftfcj:/work/dlhlp2022/hank$ python
Python 3.9.12 (main, Apr  5 2022, 06:56:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch, fairseq
>>> model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task(["/work/dlhlp2022/hank/wav2vec_vox_100h_pl.pt"])
```

And encounter this error: 
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dlhlp2022/.local/lib/python3.9/site-packages/fairseq/checkpoint_utils.py", line 447, in load_model_ensemble_and_task
    model = task.build_model(cfg.model)
  File "/home/dlhlp2022/.local/lib/python3.9/site-packages/fairseq/tasks/audio_pretraining.py", line 294, in build_model
    model = super().build_model(model_cfg)
  File "/home/dlhlp2022/.local/lib/python3.9/site-packages/fairseq/tasks/fairseq_task.py", line 320, in build_model
    model = models.build_model(cfg, self)
  File "/home/dlhlp2022/.local/lib/python3.9/site-packages/fairseq/models/__init__.py", line 107, in build_model
    return model.build_model(cfg, task)
  File "/home/dlhlp2022/.local/lib/python3.9/site-packages/fairseq/models/wav2vec/wav2vec2_asr.py", line 176, in build_model
    w2v_encoder = Wav2VecEncoder(cfg, len(task.target_dictionary))
  File "/home/dlhlp2022/.local/lib/python3.9/site-packages/fairseq/tasks/audio_pretraining.py", line 267, in target_dictionary
    return self.state.target_dictionary
  File "/home/dlhlp2022/.local/lib/python3.9/site-packages/fairseq/tasks/fairseq_task.py", line 42, in __getattr__
    self._state[name] = self._factories[name]()
  File "/home/dlhlp2022/.local/lib/python3.9/site-packages/fairseq/tasks/audio_pretraining.py", line 178, in load_target_dictionary
    return Dictionary.load(dict_path)
  File "/home/dlhlp2022/.local/lib/python3.9/site-packages/fairseq/data/dictionary.py", line 225, in load
    d.add_from_file(f)
  File "/home/dlhlp2022/.local/lib/python3.9/site-packages/fairseq/data/dictionary.py", line 238, in add_from_file
    raise fnfe
  File "/home/dlhlp2022/.local/lib/python3.9/site-packages/fairseq/data/dictionary.py", line 235, in add_from_file
    with open(PathManager.get_local_path(f), "r", encoding="utf-8") as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/private/home/qiantong/w2v/data/train_36s_short_100h_rescore/dict.ltr.txt'
```

I think that the error means the `dict.ltr.txt` file cannot be found. The file is actually not provided.

Is there anyone who successfully load the self-training version of wav2vec 2.0?

### Environment

 - fairseq Version (e.g., 1.0 or main): fairseq-1.0.0a0+f2146bd
 - PyTorch Version (e.g., 1.0): 1.11.0+cu102
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): `pip install fairseq@git+https://github.com//pytorch/fairseq.git@f2146bdc7abf293186de9449bfa2272775e39e1d#egg=fairseq`
 - Python version: 3.9.12
 - CUDA/cuDNN version: 11.1

**Comment by SeunghyunSEO** [comment]
you can download the dictionary file from [here](https://dl.fbaipublicfiles.com/fairseq/wav2vec/dict.ltr.txt)

this is official dictionary file that is used for wav2vec2 paper.
ltr means letter dictionary and you can make your own dictionary and preprocess data with your own dictionary

such as

```
dict.ltr.txt # char (letter)
dict.wrd.txt # word
dict.wordpiece.txt # wordpiece
dict.bpe.txt # byte-pair encoding
...
```
