### ISSUE TITLE
when i excute "fairseq_cli/hydra_train.py" have prompt missing import.

### ISSUE THREAD

**Issue by guobabaya** [facebookresearch/fairseq#4406]
python ${FAIRSEQ_ROOT}/fairseq_cli/hydra_train.py \
        task.data=${manifest_path} task.gpt_path=${gpt2_path} \
        model.w2v_path=${w2v_path} model.n_token=${n_token} model.reduction_factor=${reduction_factor} \
        model.gpt_path=${gpt2_path} model.freeze_finetune_updates=${freeze_finetune_updates} \
        checkpoint.save_dir=${save_dir} hydra.run.dir=${save_dir} \
        --config-dir ${config_dir} --config-name ${config_name} \
    2>&1 | tee ${save_dir}/train.log

Operation results:

Traceback (most recent call last):
  File "/home/pengtl/WavPrompt/fairseq/fairseq_cli/hydra_train.py", line 15, in <module>
    from fairseq import distributed_utils, metrics
  File "/home/pengtl/WavPrompt-main/fairseq/fairseq/__init__.py", line 33, in <module>
    import fairseq.criterions  # noqa
  File "/home/pengtl/WavPrompt-main/fairseq/fairseq/criterions/__init__.py", line 36, in <module>
    importlib.import_module("fairseq.criterions." + file_name)
  File "/home/pengtl/anaconda3/envs/wavprompt/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/pengtl/WavPrompt-main/fairseq/fairseq/criterions/ctc.py", line 18, in <module>
    from fairseq.data.data_utils import post_process
  File "/home/pengtl/WavPrompt-main/fairseq/fairseq/data/__init__.py", line 132, in <module>
    from .audio.file_audio_label_dataset import FileAudioLabelDataset
ModuleNotFoundError: No module named 'fairseq.data.audio.file_audio_label_dataset'

**Comment by guobabaya** [comment]
Rookies hope to get your guidance.

**Comment by guobabaya** [comment]
Rookies hope to get your guidance.
