### ISSUE TITLE
TypeError: tuple indices must be integers or slices, not str

### ISSUE THREAD

**Issue by salma-elshafey** [facebookresearch/fairseq#4415]
#### What is your question?
I am trying to pre-train a masked language model on an arabic dataset, but I have been getting this error "TypeError: tuple indices must be integers or slices, not str".

#### Code

# Data pre-processing command
`fairseq-preprocess --trainpref arabic_training_split.spm --validpref arabic_validation_split.spm --destdir data_bin_ar --bpe sentencepiece --only-source`

# Training command
`fairseq-train data_bin_ar/ --task masked_lm --encoder-layers 6 --encoder-attention-heads 16 --sample-break-mode eos --arch masked_lm --encoder-ffn-embed-dim 4096 --encoder-embed-dim 1024 --encoder-learned-pos --encoder-normalize-before --share-encoder-input-output-embed --activation-fn gelu --max-epoch 150 --max-tokens 8000 --optimizer adam --adam-betas '(0.9,0.98)' --lr 0.005 --warmup-init-lr '1e-07' --min-loss-scale 0.0 --lr-scheduler inverse_sqrt --warmup-updates 2500 --update-freq 6 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --dropout 0.1 --save-interval 5 --keep-last-epochs 5 --save-dir masked_lm_checkpoints --fp16 --ddp-backend=no_c10d`

This is what I get:
`Traceback (most recent call last):                                                                                                                              
  File "/home/met/.local/bin/fairseq-train", line 8, in <module>
    sys.exit(cli_main())
  File "/home/met/.local/lib/python3.8/site-packages/fairseq_cli/train.py", line 448, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/met/.local/lib/python3.8/site-packages/fairseq/distributed_utils.py", line 337, in call_main
    main(cfg, **kwargs)
  File "/home/met/.local/lib/python3.8/site-packages/fairseq_cli/train.py", line 144, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/met/.local/lib/python3.8/site-packages/fairseq_cli/train.py", line 244, in train
    log_output = trainer.train_step(samples)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/met/.local/lib/python3.8/site-packages/fairseq/trainer.py", line 532, in train_step
    loss, sample_size_i, logging_output = self.task.train_step(
  File "/home/met/.local/lib/python3.8/site-packages/fairseq/tasks/fairseq_task.py", line 428, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/home/met/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/met/.local/lib/python3.8/site-packages/fairseq/criterions/label_smoothed_cross_entropy.py", line 80, in forward
    loss, nll_loss = self.compute_loss(model, net_output, sample, reduce=reduce)
  File "/home/met/.local/lib/python3.8/site-packages/fairseq/criterions/label_smoothed_cross_entropy.py", line 110, in compute_loss
    lprobs, target = self.get_lprobs_and_target(model, net_output, sample)
  File "/home/met/.local/lib/python3.8/site-packages/fairseq/criterions/label_smoothed_cross_entropy.py", line 98, in get_lprobs_and_target
    lprobs = model.get_normalized_probs(net_output, log_probs=True)
  File "/home/met/.local/lib/python3.8/site-packages/fairseq/models/fairseq_model.py", line 547, in get_normalized_probs
    encoder_out = net_output["encoder_out"]
TypeError: tuple indices must be integers or slices, not str
`
#### What have you tried?
I tried a similar approach the solution proposed in [#2971 ](https://github.com/pytorch/fairseq/issues/2971#issue-753477876) but it did not work with my problem

#### What's your environment?
I cloned the repository from the main branch and used this command
`pip install fairseq/`
 - PyTorch Version: 1.11.0
 - OS (e.g., Linux): Linux
 - Python version: 3.8.10
 - GPU models and configuration: NVIDIA-SMI 470.103.01   Driver Version: 470.103.01   CUDA Version: 11.4

**Comment by smtnkc** [comment]
Same issue. Is this solved? @salma-elshafey @kahne

**Comment by smtnkc** [comment]
I tried with `--criterion masked_lm` and it worked.
