### ISSUE TITLE
Error when load Wav2Vec 2.0 Large (LV-60 + CV + SWBD + FSH)  AttributeError: 'NoneType' object has no attribute 'task'

### ISSUE THREAD

**Issue by Aria-K-Alethia** [facebookresearch/fairseq#4424]
## 🐛 Bug

I downloaded Wav2Vec 2.0 Large (LV-60 + CV + SWBD + FSH) from [https://dl.fbaipublicfiles.com/fairseq/wav2vec/w2v_large_lv_fsh_swbd_cv.pt](https://dl.fbaipublicfiles.com/fairseq/wav2vec/w2v_large_lv_fsh_swbd_cv.pt) and tried to load the checkpoint using fairseq, but I encountered the following error:
```python3
>>> model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble(['./fairseq/wav2vec_robust.pt'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/.local/lib/python3.7/site-packages/fairseq/checkpoint_utils.py", line 256, in load_model_ensemble
    num_shards,
  File "/home/.local/lib/python3.7/site-packages/fairseq/checkpoint_utils.py", line 279, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/home/.local/lib/python3.7/site-packages/fairseq/checkpoint_utils.py", line 231, in load_checkpoint_to_cpu
    setattr(args, arg_name, arg_val)
AttributeError: 'NoneType' object has no attribute 'task'

```
Actually I also load wav2vec small and wav2vec big, but only failed to load this model.

### To Reproduce

1.  download checkpoint from [here](https://dl.fbaipublicfiles.com/fairseq/wav2vec/w2v_large_lv_fsh_swbd_cv.pt)
2. run `model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble(['./fairseq/wav2vec_robust.pt'])`

#### Code sample
```python3
import fairseq
model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble(['./fairseq/wav2vec_robust.pt'])
```

### Expected behavior
The checkpoint should be loaded correctly.

### Environment

 - fairseq Version (0.10.2)
 - PyTorch Version (1.10.0)
 - OS (ubuntu):
 - How you installed fairseq (`pip`):
 - Python version: 3.7.5
 - CUDA/cuDNN version: 11.1

**Comment by renzeyu-ai** [comment]
I also encountered such a problem. I tried all versions and didn't solve it

**Comment by Aria-K-Alethia** [comment]
> I also encountered such a problem. I tried all versions and didn't solve it

I haven't solved the problem, but as a workaround you can use huggingface to load the model.
