### ISSUE TITLE
How to use from_pretrained offline

### ISSUE THREAD

**Issue by kuroro-jya** [facebookresearch/fairseq#4427]
## 🐛 Bug

Hi, could I ask how to load pretrained model offline. My GPU is only available in the offline environment, and I have already finished training the checkpoint through fairseq.

### To Reproduce
  d1_bart = BARTModel.from_pretrained(
        d1_path, 
        checkpoint_file=args.d1_model_path.split("/")[-1], #point to my best checkpoint
        data_name_or_path=d1_data_bin,
    )

### error

Traceback (most recent call last):
  File "/scratch/ij84/ym1752/packages/lewis/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/scratch/ij84/ym1752/packages/lewis/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/scratch/ij84/ym1752/packages/lewis/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/ij84/ym1752/packages/lewis/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/scratch/ij84/ym1752/packages/lewis/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/scratch/ij84/ym1752/packages/lewis/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/scratch/ij84/ym1752/packages/lewis/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/scratch/ij84/ym1752/packages/lewis/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x147a52d1c070>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/ij84/ym1752/packages/lewis/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/scratch/ij84/ym1752/packages/lewis/lib/python3.10/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/scratch/ij84/ym1752/packages/lewis/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='dl.fbaipublicfiles.com', port=443): Max retries exceeded with url: /fairseq/gpt2_bpe/encoder.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x147a52d1c070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/ij84/ym1752/fairseq/lewis/get_synthesized_data.py", line 66, in <module>
    d1_bart = BARTModel.from_pretrained(
  File "/scratch/ij84/ym1752/fairseq/fairseq/models/bart/model.py", line 137, in from_pretrained
    return BARTHubInterface(x["args"], x["task"], x["models"][0])
  File "/scratch/ij84/ym1752/fairseq/fairseq/models/bart/hub_interface.py", line 30, in __init__
    super().__init__(cfg, task, [model])
  File "/scratch/ij84/ym1752/fairseq/fairseq/hub_utils.py", line 108, in __init__
    self.bpe = encoders.build_bpe(cfg.bpe)
  File "/scratch/ij84/ym1752/fairseq/fairseq/registry.py", line 61, in build_x
    return builder(cfg, *extra_args, **extra_kwargs)
  File "/scratch/ij84/ym1752/fairseq/fairseq/data/encoders/gpt2_bpe.py", line 32, in __init__
    encoder_json = file_utils.cached_path(cfg.gpt2_encoder_json)
  File "/scratch/ij84/ym1752/fairseq/fairseq/file_utils.py", line 174, in cached_path
    return get_from_cache(url_or_filename, cache_dir)
  File "/scratch/ij84/ym1752/fairseq/fairseq/file_utils.py", line 299, in get_from_cache
    response = request_wrap_timeout(
  File "/scratch/ij84/ym1752/fairseq/fairseq/file_utils.py", line 251, in request_wrap_timeout
    return func(timeout=timeout)
  File "/scratch/ij84/ym1752/packages/lewis/lib/python3.10/site-packages/requests/api.py", line 102, in head
    return request('head', url, **kwargs)
  File "/scratch/ij84/ym1752/packages/lewis/lib/python3.10/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/scratch/ij84/ym1752/packages/lewis/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/scratch/ij84/ym1752/packages/lewis/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/scratch/ij84/ym1752/packages/lewis/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dl.fbaipublicfiles.com', port=443): Max retries exceeded with url: /fairseq/gpt2_bpe/encoder.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x147a52d1c070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

### Environment
 - OS (e.g., Linux):Linux
 - How you installed fairseq (`pip`, source):pip
 - Python version:3.10.4

**Comment by gmryu** [comment]
You might have already solved it.
Just in case, the problem here is loaded fairseq checkpoint does not have bpe/tokenizer/vocabulary files. 
This BARTModel needs a bpe and by default it is "gpt2" that leads to online resources.
Designate one downloaded bpe's file path to the bpe argument and everything should be fine.
