### ISSUE TITLE
If I changed data set, how can I use the parameter "--finetune-from-model"?

### ISSUE THREAD

**Issue by michelleqyhqyh** [facebookresearch/fairseq#4469]
### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd

CUDA_VISIBLE_DEVICES=7 fairseq-train data/bt-zh2en_12+8 --arch transformer --optimizer adam --adam-betas '(0.9, 0.997)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --eval-bleu --eval-bleu-args '{"beam": 5, "max_len_a": 1.2, "max_len_b": 10}' --eval-bleu-detok moses --eval-bleu-remove-bpe --eval-bleu-print-samples --best-checkpoint-metric bleu --maximize-best-checkpoint-metric --no-progress-bar --log-interval 100 --finetune-from-model ./train/top12-new-param/bak/checkpoint_best.pt --save-dir ./train/bt-zh2en_12+8-new-param-restore --keep-interval-updates 100 --save-interval-updates 5000 --tensorboard-logdir ./train/bt-zh2en_12+8-new-param-restore/tensorboard-log 2>&1 | tee ./train/bt-zh2en_12+8-new-param-restore/top12-screen.log

2. See error:
2022-06-09 15:04:01 | INFO | fairseq_cli.train | max tokens per GPU = 4096 and max sentences per GPU = None
2022-06-09 15:04:01 | INFO | fairseq.checkpoint_utils | loading pretrained model from ./train/top12-new-param/bak/checkpoint_best.pt: optimizer, lr scheduler, meters, dataloader will be reset
Traceback (most recent call last):
  File "/home/qyh/anaconda3/envs/cuda110/lib/python3.6/site-packages/fairseq/trainer.py", line 284, in load_checkpoint
    state["model"], strict=True, args=self.args
  File "/home/qyh/anaconda3/envs/cuda110/lib/python3.6/site-packages/fairseq/models/fairseq_model.py", line 99, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/home/qyh/anaconda3/envs/cuda110/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for TransformerModel:
	size mismatch for encoder.embed_tokens.weight: copying a param with shape torch.Size([37344, 512]) from checkpoint, the shape in current model is torch.Size([38008, 512]).
	size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([25144, 512]) from checkpoint, the shape in current model is torch.Size([25800, 512]).
	size mismatch for decoder.output_projection.weight: copying a param with shape torch.Size([25144, 512]) from checkpoint, the shape in current model is torch.Size([25800, 512]).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qyh/anaconda3/envs/cuda110/bin/fairseq-train", line 8, in <module>
    sys.exit(cli_main())
  File "/home/qyh/anaconda3/envs/cuda110/lib/python3.6/site-packages/fairseq_cli/train.py", line 352, in cli_main
    distributed_utils.call_main(args, main)
  File "/home/qyh/anaconda3/envs/cuda110/lib/python3.6/site-packages/fairseq/distributed_utils.py", line 301, in call_main
    main(args, **kwargs)
  File "/home/qyh/anaconda3/envs/cuda110/lib/python3.6/site-packages/fairseq_cli/train.py", line 114, in main
    disable_iterator_cache=task.has_sharded_data("train"),
  File "/home/qyh/anaconda3/envs/cuda110/lib/python3.6/site-packages/fairseq/checkpoint_utils.py", line 193, in load_checkpoint
    reset_meters=reset_meters,
  File "/home/qyh/anaconda3/envs/cuda110/lib/python3.6/site-packages/fairseq/trainer.py", line 293, in load_checkpoint
    "please ensure that the architectures match.".format(filename)
Exception: Cannot load model parameters from checkpoint ./train/top12-new-param/bak/checkpoint_best.pt; please ensure that the architectures match.

3. Issure: 
(1). At the begining, I trained the model  ./train/top12-new-param/bak/checkpoint_best.pt with dataset "data/top12";
(2). Now I hope to used it as "--finetune-from-model", and I changed dataset to " data/bt-zh2en_12+8",but the bug appeared;
(3). Then I changed the above cmd as : (Actually, I just change "data/bt-zh2en_12+8" to "data/top12")
CUDA_VISIBLE_DEVICES=7 fairseq-train data/top12 --arch transformer --optimizer adam --adam-betas '(0.9, 0.997)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 8000 --dropout 0.1 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --eval-bleu --eval-bleu-args '{"beam": 5, "max_len_a": 1.2, "max_len_b": 10}' --eval-bleu-detok moses --eval-bleu-remove-bpe --eval-bleu-print-samples --best-checkpoint-metric bleu --maximize-best-checkpoint-metric --no-progress-bar --log-interval 100 --finetune-from-model ./train/top12-new-param/bak/checkpoint_best.pt --save-dir ./train/bt-zh2en_12+8-new-param-restore --keep-interval-updates 100 --save-interval-updates 5000 --tensorboard-logdir ./train/bt-zh2en_12+8-new-param-restore/tensorboard-log 2>&1 | tee ./train/bt-zh2en_12+8-new-param-restore/top12-screen.log
        Then It worked. So I think the parameter "--finetune-from-model" needs the original dataset?

(4). But how can I used my new data "data/bt-zh2en_12+8" and the model "./train/top12-new-param/bak/checkpoint_best.pt " to do finetune?

**Comment by gmryu** [comment]
You probably did wrong with `fairseq-preprocess`

From the given error log, it tells you that vocab size of the checkpoint is 37344/25144 at encoder/decoder. However the dicts in new data requires 38008/25800.
```
size mismatch for encoder.embed_tokens.weight: copying a param with shape torch.Size([37344, 512]) from checkpoint, the shape in current model is torch.Size([38008, 512]).
size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([25144, 512]) from checkpoint, the shape in current model is torch.Size([25800, 512]).
size mismatch for decoder.output_projection.weight: copying a param with shape torch.Size([25144, 512]) from checkpoint, the shape in current model is torch.Size([25800, 512]).
```


You have to run the 2nd `fairseq-preprocess` with `--srcdict {path to zh's dict}` and `--tgtdict {path to en's dict}`
Even the raw data is dealt by the same sentencepiece/tokenizer before, there is possibility that they give different dicts.

-- 

Frankly speaking, I believe the above is all.
Yet if these does not work, would you do a another trial to identify the reason? 
(says create 2 texts with several lines in it, preprocess with the same hand-written dict, make a tiny checkpoint by learning one and load it for the other.)
