### ISSUE TITLE
Pretrain HuBert Model error

### ISSUE THREAD

**Issue by NiniAndy** [facebookresearch/fairseq#4491]
#### Code
python  hydra_train.py  --config-dir "fairseq/examples/hubert/config/pretrain/" --config-name hubert_base_librispeech

#### What is your question?
When the code try to init Trainer in the hubert model,  I meet the following errors. How can I fix it, thanks.

#### Code
python  hydra_train.py  --config-dir "fairseq/examples/hubert/config/pretrain/" --config-name hubert_base_librispeech

#### What have you tried?
Traceback (most recent call last):
  File "/data/NAS_PLUS/zhuang/CodeBase/001_fairseq/fairseq_cli/hydra_train.py", line 27, in hydra_main
    _hydra_main(cfg)
  File "/data/NAS_PLUS/zhuang/CodeBase/001_fairseq/fairseq_cli/hydra_train.py", line 56, in _hydra_main
    distributed_utils.call_main(cfg, pre_main, **kwargs)
  File "/data/NAS_PLUS/zhuang/CodeBase/001_fairseq/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "/data/NAS_PLUS/zhuang/CodeBase/001_fairseq/fairseq_cli/train.py", line 147, in main
    trainer = Trainer(cfg, task, model, criterion, quantizer)
  File "/data/NAS_PLUS/zhuang/CodeBase/001_fairseq/fairseq/trainer.py", line 164, in __init__
    if self.data_parallel_rank == 0:
  File "/data/NAS_PLUS/zhuang/CodeBase/001_fairseq/fairseq/trainer.py", line 197, in data_parallel_rank
    return distributed_utils.get_data_parallel_rank()
  File "/data/NAS_PLUS/zhuang/CodeBase/001_fairseq/fairseq/distributed/utils.py", line 463, in get_data_parallel_rank
    return get_rank(get_data_parallel_group())
  File "/data/NAS_PLUS/zhuang/CodeBase/001_fairseq/fairseq/distributed/utils.py", line 405, in get_rank
    return dist.get_rank(group=group)
  File "/home/zhuang/anaconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 688, in get_rank
    default_pg = _get_default_group()
  File "/home/zhuang/anaconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 347, in _get_default_group
    raise RuntimeError("Default process group has not been initialized, "
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

Process finished with exit code 1

#### What's your environment?

 - fairseq Version 0.12.1
 - PyTorch Version 1.11
 - Linux
 - How you installed fairseq  source
 - Build command you used pip install --editable ./
 - Python version: 3.7
 - CUDA/cuDNN version: 11.3

**Comment by hamidun123** [comment]
I have the same question

**Comment by hamidun123** [comment]
I have find the solution.
You only need delete the paramater "distributed_training.distributed_port" and set "distributed_training.distributed_world_size"="number of your gpus"
