### ISSUE TITLE
PyPI install fails with "FileNotFoundError: [Errno 2] No such file or directory: 'fairseq/version.txt'"

### ISSUE THREAD

**Issue by PJ-Finlay** [facebookresearch/fairseq#4501]
## 🐛 Bug

I'm trying to install fairseq from PyPI and the install is failing to find 'fairseq/version.txt'.

I was able to install successfully by cloning the code from GitHub and running `pip install .` in the root directory. My guess is that the installer is expecting to be in the root directory of the code to find `fairseq/version.txt` and breaks installing from PyPI.

```
$ pip install fairseq
Collecting fairseq
  Using cached fairseq-0.12.1.tar.gz (9.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/home/argosopentech/temp/env/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/argosopentech/temp/env/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/argosopentech/temp/env/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-iwbeosu0/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/tmp/pip-build-env-iwbeosu0/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-iwbeosu0/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 27, in <module>
          version = write_version_py()
        File "setup.py", line 18, in write_version_py
          with open(os.path.join("fairseq", "version.txt")) as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'fairseq/version.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### Environment

 - fairseq Version: 0.12.1
 - PyTorch Version: 1.11.0
 - OS: Ubuntu 22.04
 - Python version: 3.10.4

**Comment by dianaml0** [comment]
Thank you for reporting this issue, taking a look!

**Comment by Akash-Chak** [comment]
I am facing similar problems, and what more I cannot install it with `pip install --editable .`  or `pip install .`  , these commands are prompting below mentioned error
```
(flask_app) D:\project\fairseq>pip install .
Processing d:\project\fairseq
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: 'd:\python_enviroment\flask_app\scripts\python.exe' 'd:\python_enviroment\flask_app\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\rajak\AppData\Local\Temp\tmpd08gmu28'
       cwd: C:\Users\rajak\AppData\Local\Temp\pip-req-build-0e1k_6zh
  Complete output (16 lines):
  Traceback (most recent call last):
    File "d:\python_enviroment\flask_app\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 280, in <module>
      main()
    File "d:\python_enviroment\flask_app\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "d:\python_enviroment\flask_app\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\rajak\AppData\Local\Temp\pip-build-env-5u8cfgnw\overlay\Lib\site-packages\setuptools\build_meta.py", line 177, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "C:\Users\rajak\AppData\Local\Temp\pip-build-env-5u8cfgnw\overlay\Lib\site-packages\setuptools\build_meta.py", line 159, in _get_build_requires
      self.run_setup()
    File "C:\Users\rajak\AppData\Local\Temp\pip-build-env-5u8cfgnw\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 262, in <module>
      os.symlink(os.path.join("..", "examples"), fairseq_examples)
  OSError: [WinError 1314] A required privilege is not held by the client: '..\\examples' -> 'fairseq\\examples'
  ----------------------------------------
WARNING: Discarding file:///D:/project/fairseq. Command errored out with exit status 1: 'd:\python_enviroment\flask_app\scripts\python.exe' 'd:\python_enviroment\flask_app\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\rajak\AppData\Local\Temp\tmpd08gmu28' Check the logs for full command output.
ERROR: Command errored out with exit status 1: 'd:\python_enviroment\flask_app\scripts\python.exe' 'd:\python_enviroment\flask_app\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\rajak\AppData\Local\Temp\tmpd08gmu28' Check the logs for full command output.
WARNING: You are using pip version 21.1.1; however, version 22.1.2 is available.
You should consider upgrading via the 'd:\python_enviroment\flask_app\scripts\python.exe -m pip install --upgrade pip' command.
```
Any help?

**Enviroment**

- OS: Windows 10
- Python:3.8.10
- Pytorch:1.11.0

**Comment by gmryu** [comment]
That OSError looks like a requirement of administration.
Right click and run your console/command prompt as an administrator should fix the 2nd problem.

**Comment by Akash-Chak** [comment]
@gmryu  I have tried to run the same using command prompt as an administrator and faced different error, just pasting the last portion of the long message of error code, 
```
av2vec2
      running build_ext
      cythoning fairseq/data/data_utils_fast.pyx to fairseq/data\data_utils_fast.cpp
      cythoning fairseq/data/token_block_utils_fast.pyx to fairseq/data\token_block_utils_fast.cpp
      building 'fairseq.libbleu' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fairseq
  Building wheel for antlr4-python3-runtime (setup.py) ... done
  Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.8-py3-none-any.whl size=141231 sha256=acd74062e1b52200de57c479609aefb3ee5dfc173c47ff4b6843f703ea558c64
  Stored in directory: c:\users\rajak\appdata\local\pip\cache\wheels\c8\d0\ab\d43c02eaddc5b9004db86950802442ad9a26f279c619e28da0
Successfully built antlr4-python3-runtime
Failed to build fairseq
ERROR: Could not build wheels for fairseq, which is required to install pyproject.toml-based projects 
```
I am also getting similar results when I am trying to install older version of the same like `fairseq==0.10.0`  and I have also installed latest Microsoft Visual C++ so that is not the problem either. I have also upgraded pip,setuptools,wheel and other dependencies so they are not causing the issue as well (just assuming).

**Comment by gmryu** [comment]
@Akash-Chak How about using a different console? says ubuntsu or anaconda3(windows) and create a new virtual environment.
You will still use git clone to download fairseq and install it.
Truth be told, your error is different from this issue and feels like caused by a complex environment.
As you said you have lastest Visual C++ 14.0 but the error said it can not be found.

**Comment by dianaml0** [comment]
@PJ-Finlay I'll create a new release with the fix, let me know if you still have any issues after that

**Comment by PJ-Finlay** [comment]
It works for me now thanks!

**Comment by indiejoseph** [comment]
If anyone still encountered this issue, could try:

pip install pip==24.0

**Comment by aslin3** [comment]
> I anyone still encountered this issue, could try:
> 
> pip install pip==24.0

niubility!

**Comment by LCF2764** [comment]
> If anyone still encountered this issue, could try:
> 
> pip install pip==24.0

tql!, niubility!!!

**Comment by brightyang** [comment]
> If anyone still encountered this issue, could try:
> 
> pip install pip==24.0

thx,niubilitiest!!!

**Comment by ootsuka-repos** [comment]
pip install pip==24.0
pip install fairseq
version 3.9.18 OK

**Comment by zyzfred** [comment]
> If anyone still encountered this issue, could try:
> 
> pip install pip==24.0

Literally niubility
