### ISSUE TITLE
How to embed batches with another pre-trained model on-the-fly during training?

### ISSUE THREAD

**Issue by st-vincent1** [facebookresearch/fairseq#4607]
I'm implementing a model which maps pre-trained sentence embeddings from BERT to some text output.

My current implementation loads pre-embedded sentences from a `.pkl` file when my task is initialised, and later uses this as a reference table when retrieving samples with `__getitem__`  in my dataset. This works very well for smaller (<1M samples) datasets.

However, for large datasets, I can't pickle the input embeddings as the tensor grows beyond 100 GB. I've realised I need to do this on the fly. So now instead of loading the embeddings, I load the BERT model and its tokenizer, and read in the raw input text into memory instead. Then, `__getitem__` calls the function implemented for BERT which produces the embeddings:

```python
    def produce_single_embedding(self, input_lists: List[List[str]], index: int):
        items = [lst[index] for lst in input_lists] # retrieve raw text input
        encoded_input = self.tokenizer(items,
                                       add_special_tokens=True,
                                       padding=True,
                                       truncation=True,
                                       return_tensors='pt').to(self.device) # encode input and move to GPU
        (...)
        with torch.no_grad():
            # Get last hidden states of model and then extract the cls embedding ([0][:,0,:])
            cls = self.model(encoded_input['input_ids'],
                             attention_mask=encoded_input['attention_mask'])[0][:, 0, :].to(self.device)
        (...)
        return cls.cpu() # Move back to CPU as fairseq needs this data to be on CPU
```

(I realise a better idea would be do do this step with a full batch in `collater`, and it's a todo after I fix the current issue.)

The problem is, when I run `fairseq-train`, I get the following traceback:
```python
Traceback (most recent call last):
  File "/home/sebastian/Documents/Projects/fairseq_own_model_sandbox/fairseq/fairseq_cli/train.py", line 564, in <module>
    cli_main()
  File "/home/sebastian/Documents/Projects/fairseq_own_model_sandbox/fairseq/fairseq_cli/train.py", line 557, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/sebastian/Documents/Projects/fairseq_own_model_sandbox/fairseq/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "/home/sebastian/Documents/Projects/fairseq_own_model_sandbox/fairseq/fairseq_cli/train.py", line 190, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/home/sebastian/miniconda3/envs/fairseq/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/sebastian/Documents/Projects/fairseq_own_model_sandbox/fairseq/fairseq_cli/train.py", line 312, in train
    for i, samples in enumerate(progress):
  File "/home/sebastian/Documents/Projects/fairseq_own_model_sandbox/fairseq/fairseq/logging/progress_bar.py", line 272, in __iter__
    for i, obj in enumerate(self.iterable, start=self.n):
  File "/home/sebastian/Documents/Projects/fairseq_own_model_sandbox/fairseq/fairseq/data/iterators.py", line 57, in __next__
    x = next(self._itr)
  File "/home/sebastian/Documents/Projects/fairseq_own_model_sandbox/fairseq/fairseq/data/iterators.py", line 614, in _chunk_iterator
    for x in itr:
  File "/home/sebastian/Documents/Projects/fairseq_own_model_sandbox/fairseq/fairseq/data/iterators.py", line 57, in __next__
    x = next(self._itr)
  File "/home/sebastian/Documents/Projects/fairseq_own_model_sandbox/fairseq/fairseq/data/iterators.py", line 747, in __next__
    raise item
  File "/home/sebastian/Documents/Projects/fairseq_own_model_sandbox/fairseq/fairseq/data/iterators.py", line 677, in run
    for item in self._source:
  File "/home/sebastian/miniconda3/envs/fairseq/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/home/sebastian/miniconda3/envs/fairseq/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1347, in _next_data
    return self._process_data(data)
  File "/home/sebastian/miniconda3/envs/fairseq/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1373, in _process_data
    data.reraise()
  File "/home/sebastian/miniconda3/envs/fairseq/lib/python3.10/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/sebastian/miniconda3/envs/fairseq/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/sebastian/miniconda3/envs/fairseq/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/sebastian/miniconda3/envs/fairseq/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/sebastian/Documents/Projects/fairseq_own_model_sandbox/fairseq/fairseq/data/cue_dataset.py", line 314, in __getitem__
    cxt_item = self.cxt(index) # we assume that cxt is a predefined mapping
  File "/home/sebastian/Documents/Projects/fairseq_own_model_sandbox/fairseq/fairseq/tasks/cue_translation.py", line 107, in <lambda>
    cxt = lambda idx: cxt_class.produce_single_embedding(context_lists=context_lists, index=idx)
  File "/home/sebastian/Documents/Projects/fairseq_own_model_sandbox/fairseq/examples/cue_sandbox/sentence_embeddings.py", line 28, in produce_single_embedding
    return_tensors='pt').to(self.device)
  File "/home/sebastian/miniconda3/envs/fairseq/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 829, in wrapper
    return func(*args, **kwargs)
  File "/home/sebastian/miniconda3/envs/fairseq/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 746, in to
    self.data = {k: v.to(device=device) for k, v in self.data.items()}
  File "/home/sebastian/miniconda3/envs/fairseq/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 746, in <dictcomp>
    self.data = {k: v.to(device=device) for k, v in self.data.items()}
  File "/home/sebastian/miniconda3/envs/fairseq/lib/python3.10/site-packages/torch/cuda/__init__.py", line 207, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
```

When I use CPU for the BERT encoding function it works fine, but I'm creating a huge bottleneck so I need to use the GPU instead.

Is there a way to use BERT this way during training without the errors?

My setup:
 - fairseq Version (e.g., 1.0 or main): main
 - PyTorch Version (e.g., 1.0): 1.12
 - OS (e.g., Linux): 20.04 Ubuntu
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source): pip install --editable ./
 - Python version: 3.10
 - CUDA/cuDNN version: 11.6
 - GPU models and configuration: 1x16GB GPU

**Comment by gmryu** [comment]
I have no answer.  The best I can tell is you can google RuntimeError: Cannot re-initialize CUDA in forked subprocess  for more information.

So far from https://bytemeta.vip/repo/pytorch/pytorch/issues/77159 , I assume the RuntimeError happens because you create a gpu tensor inside dataloader.
The way around may be 
- either using "spawn" with `torch.multiprocessing`
- or probably keeping the bert on cpu so as to skip to.("gpu").

**Comment by st-vincent1** [comment]
Thanks @gmryu , after taking a look at that error itself indeed adding the following line alongside loading the BERT model: `torch.multiprocessing.set_start_method('spawn', force=True)` helped alleviate this issue. Running on CPU works too (even without adding that line) but as I said before, it is *very* slow.

After this fix, this on-the-fly encoding used with `fairseq-train` causes a 10x slowdown (per epoch) w.r.t. pre-loaded vectors. I just moved this encoding step to the `collater` and the slowdown is now just 3x (per epoch).

This is still pretty bad so I'm going to go back to loading embeddings from a file to an indexed dataset (`TensorDataset`). In #4587 I decided to save/load my dataset with pickle, but my dataset in practice is too big for this to work. According to this [thread](https://discuss.pytorch.org/t/best-way-to-load-a-lot-of-training-data/80847), one could save each individual tensor to its own named file and then define `__getitem__` to retrieve the tensor by loading that file. Is this still recommended for datasets of >5M samples (which will result in 5M individual files)?

**Comment by st-vincent1** [comment]
Closing as managed to find an efficient and working workaround for the above using `torch.utils.data.FloatStorage` as described [here](https://stackoverflow.com/a/64408659/17385758). The massive embedding tensor is saved to a .bin file and then read in directly as a `torch.utils.data.TensorDataset`.
