### ISSUE TITLE
Can I delete some words in the dictionary before preprocessing and training of the model?

### ISSUE THREAD

**Issue by tianshuailu** [facebookresearch/fairseq#4660]
## ❓ Questions and Help

Hi I am doing some MT work with mBART model, when preprocessing of some training data, but got the following error, and after I deleted the duplicated words, the error was fixed, but I'm curious is it ok to just delete the words in the dictionary before preprocessing?

> Traceback (most recent call last):
  File "/home/user/ltian/anaconda3/bin/fairseq-preprocess", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-preprocess')())
  File "/srv/scratch3/ltian/NMT-Adapt/NMTAdapt1/fairseq_cli/preprocess.py", line 360, in cli_main
    main(args)
  File "/srv/scratch3/ltian/NMT-Adapt/NMTAdapt1/fairseq_cli/preprocess.py", line 92, in main
    src_dict = task.load_dictionary(args.srcdict)
  File "/srv/scratch3/ltian/NMT-Adapt/NMTAdapt1/fairseq/tasks/fairseq_task.py", line 54, in load_dictionary
    return Dictionary.load(filename)
  File "/srv/scratch3/ltian/NMT-Adapt/NMTAdapt1/fairseq/data/dictionary.py", line 214, in load
    d.add_from_file(f)
  File "/srv/scratch3/ltian/NMT-Adapt/NMTAdapt1/fairseq/data/dictionary.py", line 225, in add_from_file
    self.add_from_file(fd)
  File "/srv/scratch3/ltian/NMT-Adapt/NMTAdapt1/fairseq/data/dictionary.py", line 255, in add_from_file
    .format(word)
RuntimeError: Duplicate word found when loading Dictionary: '<unk>'. Duplicate words can overwrite earlier ones by adding the #fairseq:overwrite flag at the end of the corresponding row in the dictionary file. If using the Camembert model, please download an updated copy of the model file.

The first few lines of the dictionary:
![image](https://user-images.githubusercontent.com/22446406/185754011-8e25aa15-15c3-4e6a-b9fb-0b08d2cbe040.png)

And actually I think the first three words should not be there, so I'll probably generate the dictionary from the data again.

**Comment by gmryu** [comment]
dict.xxx.txt can be changed freely before the first preprocessing/pretraining.

Once a model trained with the dict.xxx.txt, the model's input vocab size is determined.
Afterwards, changing dict.xxx.txt will result a mismatch between that model's vocab and the new dict vocab.
If the vocab size is different, the previous trained model cannot be loaded.

And Yes, that `<unk> </s> <s>` is not necessary for fairseq and the fact it does not have <pad> feels alittle awkward.

**Comment by tianshuailu** [comment]
> 

Thanks for your help again. Really appreciate it!
