### ISSUE TITLE
multiple nodes DDP with hydra_train: Socket Timeout

### ISSUE THREAD

**Issue by Rongjiehuang** [facebookresearch/fairseq#4718]
### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd '....'

python3 -m torch.distributed.launch \
  --nnodes=$nnodes \
  --node_rank=$node_id \
  --master_addr="${CHIEF_IP}" \
  --master_port=$MASTER_PORT \
  --nproc_per_node $world_size \
  /apdcephfs/private_nlphuang/Experiments/fairseq/fairseq_cli/hydra_train.py \
  distributed_training.distributed_world_size=$all_world_size \
  common.user_dir=/apdcephfs/private_nlphuang/Experiments/fairseq/research/mae_ast/ \
  task.data=${data_dir} \
  checkpoint.save_dir=$model_dir \
  optimization.max_update=550000 \
  dataset.max_tokens=2588608 \
  --config-dir /apdcephfs/private_nlphuang/Experiments/fairseq/research/mae_ast/config/pretrain/ \
  --config-name mae_perturbation_ast_random

2. See error

2022-09-14 00:14:37.444 /usr/local/lib64/python3.6/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
2022-09-14 00:14:37.444 and will be removed in future. Use torchrun.
2022-09-14 00:14:37.444 Note that --use_env is set by default in torchrun.
2022-09-14 00:14:37.444 If your script expects `--local_rank` argument to be set, please
2022-09-14 00:14:37.444 change it to read from `os.environ['LOCAL_RANK']` instead. See
2022-09-14 00:14:37.444 https://pytorch.org/docs/stable/distributed.html#launch-utility for
2022-09-14 00:14:37.444 further instructions
2022-09-14 00:14:37.444 FutureWarning,
2022-09-14 00:14:37.444 WARNING:torch.distributed.run:
2022-09-14 00:14:37.444 *****************************************
2022-09-14 00:14:37.444 Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
2022-09-14 00:14:37.444 *****************************************
2022-09-14 00:34:51.751 Traceback (most recent call last):
2022-09-14 00:34:51.751 File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
2022-09-14 00:34:51.751 "__main__", mod_spec)
2022-09-14 00:34:51.751 File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
2022-09-14 00:34:51.751 exec(code, run_globals)
2022-09-14 00:34:51.751 File "/usr/local/lib64/python3.6/site-packages/torch/distributed/launch.py", line 193, in <module>
2022-09-14 00:34:51.751 main()
2022-09-14 00:34:51.751 File "/usr/local/lib64/python3.6/site-packages/torch/distributed/launch.py", line 189, in main
2022-09-14 00:34:51.751 launch(args)
2022-09-14 00:34:51.751 File "/usr/local/lib64/python3.6/site-packages/torch/distributed/launch.py", line 174, in launch
2022-09-14 00:34:51.751 run(args)
2022-09-14 00:34:51.751 File "/usr/local/lib64/python3.6/site-packages/torch/distributed/run.py", line 713, in run
2022-09-14 00:34:51.751 )(*cmd_args)
2022-09-14 00:34:51.751 File "/usr/local/lib64/python3.6/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
2022-09-14 00:34:51.751 return launch_agent(self._config, self._entrypoint, list(args))
2022-09-14 00:34:51.751 File "/usr/local/lib64/python3.6/site-packages/torch/distributed/launcher/api.py", line 252, in launch_agent
2022-09-14 00:34:51.751 result = agent.run()
2022-09-14 00:34:51.751 File "/usr/local/lib64/python3.6/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
2022-09-14 00:34:51.751 result = f(*args, **kwargs)
2022-09-14 00:34:51.751 File "/usr/local/lib64/python3.6/site-packages/torch/distributed/elastic/agent/server/api.py", line 709, in run
2022-09-14 00:34:51.751 result = self._invoke_run(role)
2022-09-14 00:34:51.751 File "/usr/local/lib64/python3.6/site-packages/torch/distributed/elastic/agent/server/api.py", line 837, in _invoke_run
2022-09-14 00:34:51.751 self._initialize_workers(self._worker_group)
2022-09-14 00:34:51.751 File "/usr/local/lib64/python3.6/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
2022-09-14 00:34:51.751 result = f(*args, **kwargs)
2022-09-14 00:34:51.751 File "/usr/local/lib64/python3.6/site-packages/torch/distributed/elastic/agent/server/api.py", line 678, in _initialize_workers
2022-09-14 00:34:51.751 self._rendezvous(worker_group)
2022-09-14 00:34:51.751 File "/usr/local/lib64/python3.6/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
2022-09-14 00:34:51.751 result = f(*args, **kwargs)
2022-09-14 00:34:51.751 File "/usr/local/lib64/python3.6/site-packages/torch/distributed/elastic/agent/server/api.py", line 541, in _rendezvous
2022-09-14 00:34:51.751 workers = self._assign_worker_ranks(store, group_rank, group_world_size, spec)
2022-09-14 00:34:51.751 File "/usr/local/lib64/python3.6/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
2022-09-14 00:34:51.751 result = f(*args, **kwargs)
2022-09-14 00:34:51.751 File "/usr/local/lib64/python3.6/site-packages/torch/distributed/elastic/agent/server/api.py", line 610, in _assign_worker_ranks
2022-09-14 00:34:51.751 role_infos = self._share_and_gather(store, group_rank, group_world_size, spec)
2022-09-14 00:34:51.751 File "/usr/local/lib64/python3.6/site-packages/torch/distributed/elastic/agent/server/api.py", line 648, in _share_and_gather
2022-09-14 00:34:51.751 store, agent_config_enc, group_rank, group_world_size, key_prefix
2022-09-14 00:34:51.751 File "/usr/local/lib64/python3.6/site-packages/torch/distributed/elastic/utils/store.py", line 53, in synchronize
2022-09-14 00:34:51.751 agent_data = get_all(store, key_prefix, world_size)
2022-09-14 00:34:51.751 File "/usr/local/lib64/python3.6/site-packages/torch/distributed/elastic/utils/store.py", line 31, in get_all
2022-09-14 00:34:51.751 data = store.get(f"{prefix}{idx}")
2022-09-14 00:34:51.751 RuntimeError: Socket Timeout
2022-09-14 00:34:51.916 user exit code: 1

### Environment

 - fairseq Version (e.g., 1.0 or main): 1.0.0a0
 - PyTorch Version (e.g., 1.0) 1.10.0
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source):  source
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by Rongjiehuang** [comment]
I try to pretrain the self-supervised speech model (e.g., Hubert) using 2 nodes, each with 4 V100 GPUs (8 GPUs in total). However: 

- When I use Pytorch 1.7.0, It reports that hydra_train does not support `--local_rank` from **torch.distribute.lunch**.
- When I upgrade Pytorch to 1.10.0 and use the command **torchrun**, the Socket Timeout issue occurs.

Can someone help me figure out the issue? Thanks in advance. @gmryu @myleott

**Comment by gmryu** [comment]
@Rongjiehuang  How do you actually run `torchrun`?
If you have 2 nodes, you must have excute torchrun twice (I mean you issue the command for each node).
So what does the script look like?
