### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte

### ISSUE THREAD

**Issue by benam2** [facebookresearch/fairseq#4728]
Got this error while trying to run https://github.com/s3prl/s3prl project.

```
.
- This IS NOT expected if you are initializing Wav2Vec2Model from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
[Featurizer for <class 's3prl.upstream.wav2vec2_hug.expert.UpstreamExpert'>] - The input upstream is only for initialization and not saved in this nn.Module
[Featurizer for <class 's3prl.upstream.wav2vec2_hug.expert.UpstreamExpert'>] - Take a list of 13 features and weighted sum them.
Traceback (most recent call last):
  File "/home/ai-labs/Desktop/ASR/fairseq/fairseq/data/dictionary.py", line 236, in add_from_file
    self.add_from_file(fd)
  File "/home/ai-labs/Desktop/ASR/fairseq/fairseq/data/dictionary.py", line 246, in add_from_file
    lines = f.readlines()
  File "/home/ai-labs/.conda/envs/asr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_downstream.py", line 203, in <module>
    main()
  File "run_downstream.py", line 198, in main
    runner = Runner(args, config)
  File "/home/ai-labs/Desktop/ASR/s3prl/s3prl/downstream/runner.py", line 52, in __init__
    self.downstream = self._get_downstream()
  File "/home/ai-labs/Desktop/ASR/s3prl/s3prl/downstream/runner.py", line 133, in _get_downstream
    **vars(self.args)
  File "/home/ai-labs/Desktop/ASR/s3prl/s3prl/downstream/asr/expert.py", line 82, in __init__
    self.dictionary = Dictionary.load(self.datarc.get("dict_path", str(Path(__file__).parent / "char.dict")))
  File "/home/ai-labs/Desktop/ASR/fairseq/fairseq/data/dictionary.py", line 225, in load
    d.add_from_file(f)
  File "/home/ai-labs/Desktop/ASR/fairseq/fairseq/data/dictionary.py", line 242, in add_from_file
    "rebuild the dataset".format(f)
Exception: Incorrect encoding detected in ./downstream/asr/char.dict, please rebuild the dataset
```

Any help please?

**Comment by matakahas** [comment]
I have a similar question - I was following the language model example here (https://github.com/facebookresearch/fairseq/tree/main/examples/language_model) and the attempt to train a basic LM fails with the message `UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 12: invalid start byte`.

I was able to do pre-processing and binarization just fine, and I'm putting the binarized data (named `train`/`valid`/`test`) along with the dictionary (`dict.txt`) under `data-bin/wikitext-103`. Any help is appreciated!
