### ISSUE TITLE
An error while training simultaneous translation model (transformer_monotonic_vaswani_wmt_en_de_big)

### ISSUE THREAD

**Issue by YanzhiTian** [facebookresearch/fairseq#4750]
#### What is your question?
Hi, I'd like to use fairseq to train a simultaneous translation model with waitk policy. 
And I want to use transformer_monotonic_vaswani_wmt_en_de_big model.
However, there is an error:
  Traceback (most recent call last):
    File "/home/usr/miniconda3/envs/iwslt2022/bin/fairseq-train", line 8, in <module>
      sys.exit(cli_main())
    File "/home/usr/fairseq/fairseq_cli/train.py", line 542, in cli_main
      args = options.parse_args_and_arch(parser, modify_parser=modify_parser)
    File "/home/usr/fairseq/fairseq/options.py", line 153, in parse_args_and_arch
      raise RuntimeError()
  RuntimeError

It seems that the model  transformer_monotonic_vaswani_wmt_en_de_big hasn't been registered.

#### Code
Here is my training bash.
CUDA_VISIBLE_DEVICES=4,5 nohup fairseq-train ${data_dir}/data-bin  \
    --source-lang zh --target-lang en  \
    --save-dir ${model_dir}/monotonic  \
    --task simul_text_to_text  \ 
    --waitk-laggings 3  \
    --max-update 200000  \
    --save-interval-updates 2000 --keep-interval-updates 5 \
    --patience 20 --no-epoch-checkpoints --keep-best-checkpoints 5 \
    --arch transformer_monotonic_vaswani_wmt_en_de_big  \
    --optimizer adam  \
    --adam-betas '(0.9, 0.98)'  \
    --lr-scheduler inverse_sqrt  \
    --warmup-init-lr 1e-07  \
    --warmup-updates 4000  \
    --lr 0.00025  \
    --stop-min-lr 1e-09  \
    --clip-norm 0  \
    --dropout 0.3  \
    --weight-decay 0.0001 \
    --criterion label_smoothed_cross_entropy  \
    --label-smoothing 0.1  \
    --max-tokens 4000  --update-freq 4 \
    --no-progress-bar \
    --fp16 --fp16-scale-tolerance 0.25 \
    --scoring sacrebleu --sacrebleu-tokenizer 13a \
    --eval-bleu \
    --eval-bleu-args '{"beam": 5, "max_len_a": 1, "max_len_b": 50}' \
    --eval-bleu-remove-bpe \
    --eval-bleu-print-samples \
    --best-checkpoint-metric bleu --maximize-best-checkpoint-metric \
    --tensorboard-logdir waitk

#### What's your environment?

 - fairseq Version (e.g., 1.0 or main): 1.0
 - PyTorch Version (e.g., 1.0): 1.12
 - OS (e.g., Linux): ubuntu
 - How you installed fairseq (`pip`, source): pip
 - Build command you used (if compiling from source):  python setup.py build_ext --inplace
 - Python version: 3.8
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by YanzhiTian** [comment]
Got it!
Add "export PYTHONPATH=/home/usr/fairseq" before.
