### ISSUE TITLE
Installation with main branch not working

### ISSUE THREAD

**Issue by adaniefei** [facebookresearch/fairseq#4760]
## 🐛 Bug

(Not sure if it's a bug.)
Ran fairseq on both linux and windows OS last month. Tried to set up the fairseq on a brand-new machine today and couldn't install it using `pip install --editable ./` if cloned from the main branch.

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. `git clone https://github.com/pytorch/fairseq`
2. `pip install --editable ./`

```
...
      creating build\lib.win-amd64-cpython-38\fairseq\config\model\wav2vec
      copying fairseq\config\model\wav2vec\vq_wav2vec_gumbel.yaml -> build\lib.win-amd64-cpython-38\fairseq\config\model\wav2vec
      creating build\lib.win-amd64-cpython-38\fairseq\config\model\wav2vec2
      copying fairseq\config\model\wav2vec2\wav2vec2_base.yaml -> build\lib.win-amd64-cpython-38\fairseq\config\model\wav2vec2
      copying fairseq\config\model\wav2vec2\wav2vec2_large.yaml -> build\lib.win-amd64-cpython-38\fairseq\config\model\wav2vec2
      running build_ext
      C:\Users\Fei\AppData\Local\Temp\pip-build-env-i8oarmc3\overlay\Lib\site-packages\torch\utils\cpp_extension.py:411: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      C:\Users\Fei\AppData\Local\Temp\pip-build-env-i8oarmc3\overlay\Lib\site-packages\torch\utils\cpp_extension.py:346: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      Traceback (most recent call last):
        File "c:\users\fei\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "c:\users\fei\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "c:\users\fei\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\Fei\AppData\Local\Temp\pip-build-env-i8oarmc3\overlay\Lib\site-packages\setuptools\build_meta.py", line 412, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "C:\Users\Fei\AppData\Local\Temp\pip-build-env-i8oarmc3\overlay\Lib\site-packages\setuptools\build_meta.py", line 397, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\Fei\AppData\Local\Temp\pip-build-env-i8oarmc3\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 252, in <module>
        File "<string>", line 164, in do_setup
        File "C:\Users\Fei\AppData\Local\Temp\pip-build-env-i8oarmc3\overlay\Lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Fei\AppData\Local\Temp\pip-build-env-i8oarmc3\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\Fei\AppData\Local\Temp\pip-build-env-i8oarmc3\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\Fei\AppData\Local\Temp\pip-build-env-i8oarmc3\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "C:\Users\Fei\AppData\Local\Temp\pip-build-env-i8oarmc3\overlay\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\Fei\AppData\Local\Temp\pip-build-env-i8oarmc3\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\Fei\AppData\Local\Temp\pip-build-env-i8oarmc3\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "C:\Users\Fei\AppData\Local\Temp\pip-build-env-i8oarmc3\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Fei\AppData\Local\Temp\pip-build-env-i8oarmc3\overlay\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\Fei\AppData\Local\Temp\pip-build-env-i8oarmc3\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\Fei\AppData\Local\Temp\pip-build-env-i8oarmc3\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "C:\Users\Fei\AppData\Local\Temp\pip-build-env-i8oarmc3\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Fei\AppData\Local\Temp\pip-build-env-i8oarmc3\overlay\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\Fei\AppData\Local\Temp\pip-build-env-i8oarmc3\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\Fei\AppData\Local\Temp\pip-build-env-i8oarmc3\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "C:\Users\Fei\AppData\Local\Temp\pip-build-env-i8oarmc3\overlay\Lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
          _build_ext.build_ext.run(self)
        File "C:\Users\Fei\AppData\Local\Temp\pip-build-env-i8oarmc3\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
          self.build_extensions()
        File "C:\Users\Fei\AppData\Local\Temp\pip-build-env-i8oarmc3\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 434, in build_extensions
          self._check_cuda_version(compiler_name, compiler_version)
        File "C:\Users\Fei\AppData\Local\Temp\pip-build-env-i8oarmc3\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 808, in _check_cuda_version
          torch_cuda_version = packaging.version.parse(torch.version.cuda)
        File "C:\Users\Fei\AppData\Local\Temp\pip-build-env-i8oarmc3\overlay\Lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 49, in parse
          return Version(version)
        File "C:\Users\Fei\AppData\Local\Temp\pip-build-env-i8oarmc3\overlay\Lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 264, in __init__
          match = self._regex.search(version)
      TypeError: expected string or bytes-like object
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fairseq
Failed to build fairseq
ERROR: Could not build wheels for fairseq, which is required to install pyproject.toml-based projects
```

### Environment

 - fairseq Version: main
 - PyTorch Version: 1.12.1+cu113
 - OS: Windows
 - How you installed fairseq: pip
 - Build command you used: pip install --editable ./
 - Python version: 3.8
 - CUDA/cuDNN version: 11.3
 - GPU models and configuration: 3090 Ti
 - Any other relevant information: 

### Additional context

**v 0.12.2 release works!**

**Comment by shuvohishab** [comment]
@adaniefei Hi!
Have you entered into the root directory? (I meant `cd fairseq`)
From the above error, I'm guessing that you are not in the root directory of fairseq. Because `pyproject.toml` file exists in the root directory of `fairseq`.

**Comment by adaniefei** [comment]
> @adaniefei Hi! Have you entered into the root directory? (I meant `cd fairseq`) From the above error, I'm guessing that you are not in the root directory of fairseq. Because `pyproject.toml` file exists in the root directory of `fairseq`.

Hi @shuvohishab , thanks for the reply!
I didn't inlcude cd fairseq in the steps and yes I did enter the root of fairseq for the next step of installation.

**Comment by lash-1997** [comment]
@adaniefei Fairseq was not seem to support the WIN system.
(https://github.com/facebookresearch/fairseq/issues/2411)

**Comment by lash-1997** [comment]
win was not support by fairseq

https://github.com/pytorch/fairseq/issues/2411

**Comment by tytcc** [comment]
Hi @adaniefei, I met the same error. Did u solve the problem?

**Comment by BUZZARDGTA** [comment]
You can try installing Visual Studio, and select the first "Desktop development with C++" option there:
https://visualstudio.microsoft.com/visual-cpp-build-tools/
