### ISSUE TITLE
Hugging face impletenation result in cuda device error.

### ISSUE THREAD

**Issue by knoriy** [facebookresearch/fairseq#4766]
## 🐛 Bug

Using GPU and huggingface `load_model_ensemble_and_task_from_hf_hub` results in:
```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
```
Forcing all tensors and models on a device still returns the same error. Am I missing something?

### To Reproduce

```python
from fairseq.checkpoint_utils import load_model_ensemble_and_task_from_hf_hub
from fairseq.models.text_to_speech.hub_interface import TTSHubInterface


models, cfg, task = load_model_ensemble_and_task_from_hf_hub(
    "facebook/fastspeech2-en-200_speaker-cv4",
    arg_overrides={"vocoder": "hifigan", "fp16": False}
)
model = models[0]
TTSHubInterface.update_cfg_with_data_cfg(cfg, task.data_cfg)
generator = task.build_generator(models, cfg)

text = "Hello, this is a test run."

sample = TTSHubInterface.get_model_input(task, text)
wav, rate = TTSHubInterface.get_prediction(task, model, generator, sample)
```

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd 'python file.py'

Error in full:
```
Fetching 9 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:00<00:00, 1002.25it/s]
2022-10-07 18:52:27 | INFO | fairseq.tasks.speech_to_text | dictionary size (vocab.txt): 74
2022-10-07 18:52:28 | INFO | fairseq.models.text_to_speech.vocoder | loaded HiFiGAN checkpoint from /fsx/home-knoriy/.cache/fairseq/models--facebook--fastspeech2-en-200_speaker-cv4/snapshots/e0218c23f36ee17ddef548a1ec04efe6ced9370c/hifigan.bin
2022-10-07 18:52:29 | INFO | fairseq.models.text_to_speech.vocoder | loaded HiFiGAN checkpoint from /fsx/home-knoriy/.cache/fairseq/models--facebook--fastspeech2-en-200_speaker-cv4/snapshots/e0218c23f36ee17ddef548a1ec04efe6ced9370c/hifigan.bin
Traceback (most recent call last):
  File "/fsx/knoriy/code/text-to-speech/fastspeech2.py", line 53, in <module>
    wav, rate = TTSHubInterface.get_prediction(task, model, generator, sample)
  File "/fsx/home-knoriy/miniconda3/envs/tts/lib/python3.9/site-packages/fairseq/models/text_to_speech/hub_interface.py", line 132, in get_prediction
    prediction = generator.generate(model, sample)
  File "/fsx/home-knoriy/miniconda3/envs/tts/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/fsx/home-knoriy/miniconda3/envs/tts/lib/python3.9/site-packages/fairseq/speech_generator.py", line 162, in generate
    finalized = [
  File "/fsx/home-knoriy/miniconda3/envs/tts/lib/python3.9/site-packages/fairseq/speech_generator.py", line 165, in <listcomp>
    "waveform": self.get_waveform(
  File "/fsx/home-knoriy/miniconda3/envs/tts/lib/python3.9/site-packages/fairseq/speech_generator.py", line 33, in get_waveform
    return None if self.vocoder is None else self.vocoder(feat).squeeze(0)
  File "/fsx/home-knoriy/miniconda3/envs/tts/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fsx/home-knoriy/miniconda3/envs/tts/lib/python3.9/site-packages/fairseq/models/text_to_speech/vocoder.py", line 201, in forward
    return model(x.unsqueeze(0).transpose(1, 2)).detach().squeeze(0)
  File "/fsx/home-knoriy/miniconda3/envs/tts/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fsx/home-knoriy/miniconda3/envs/tts/lib/python3.9/site-packages/fairseq/models/text_to_speech/hifigan.py", line 155, in forward
    x = self.conv_pre(x)
  File "/fsx/home-knoriy/miniconda3/envs/tts/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1148, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/fsx/home-knoriy/miniconda3/envs/tts/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 307, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/fsx/home-knoriy/miniconda3/envs/tts/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 303, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
```

#### Code sample
```python
from fairseq.checkpoint_utils import load_model_ensemble_and_task_from_hf_hub
from fairseq.models.text_to_speech.hub_interface import TTSHubInterface


models, cfg, task = load_model_ensemble_and_task_from_hf_hub(
    "facebook/fastspeech2-en-200_speaker-cv4",
    arg_overrides={"vocoder": "hifigan", "fp16": False}
)
model = models[0]
TTSHubInterface.update_cfg_with_data_cfg(cfg, task.data_cfg)
generator = task.build_generator(models, cfg)

text = "Hello, this is a test run."

sample = TTSHubInterface.get_model_input(task, text)
wav, rate = TTSHubInterface.get_prediction(task, model, generator, sample)
```

### Expected behavior

Audio data, which contains a person saying, "Hello, this is a test run."

### Environment

 - fairseq Version (e.g., 1.0 or main): 0.12.2
 - PyTorch Version (e.g., 1.0): 1.12.1
 - OS (e.g., Linux): ubuntu20.04
 - How you installed fairseq (`pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.9.0
 - CUDA/cuDNN version: 11.6
 - GPU models and configuration: Nvidia A100

### Additional context

I've tested this with several other models with a similar error, CPU mode works fine.

**Comment by gmryu** [comment]
It is probably the input tensors in `sample` are on cpu by default.
You may try:
```
print(sample) # to see what is inside, 

# probably there is a "net_input" with "src_tokens" etc. inside?
# for all tensors you found inside and are likely used by the model, put them onto gpu.
batch["net_input"]["src_tokens"]=batch["net_input"]["src_tokens"].cuda()
```

**Comment by knoriy** [comment]
@gmryu thank you for the reply.

I've tried this and still get the same error. 

```python
sample['net_input']['src_tokens'] = sample['net_input']['src_tokens'].cuda()
sample['net_input']['src_lengths'] = sample['net_input']['src_lengths'].cuda()
sample['speaker'] = sample['speaker'].cuda()
```
Output:
```
>>> {'net_input': {'src_tokens': tensor([[27,  6,  9, 41, 13, 40, 16,  7, 16, 15,  6,  5, 20,  7,  5,  8, 31,  4,
>>>          2]], device='cuda:0', dtype=torch.int32), 'src_lengths': tensor([18], device='cuda:0'), 'prev_output_tokens': None}, 
>>>          'target_lengths': None, 'speaker': tensor([[74]], device='cuda:0')}
```

I believe this could be caused by the `generator` or `task`. as they return an object as shown below:
```
<fairseq.tasks.text_to_speech.TextToSpeechTask object at 0x7fd0cc94dfd0>
<fairseq.speech_generator.NonAutoregressiveSpeechGenerator object at 0x7fd16a64f820>
```

Is there a way to place these onto the device?

**Comment by XiepengLi** [comment]
> 
```
model = models[0].cuda()
TTSHubInterface.update_cfg_with_data_cfg(cfg, task.data_cfg)
generator = task.build_generator([model], cfg)
# next(model.parameters()).device

sample = TTSHubInterface.get_model_input(task, text)
sample["net_input"]["src_tokens"] = sample["net_input"]["src_tokens"].cuda()
sample["net_input"]["src_lengths"] = sample["net_input"]["src_lengths"].cuda()
sample["speaker"] = sample["speaker"].cuda()

wav, rate = TTSHubInterface.get_prediction(task, model, generator, sample)
ipd.Audio(wav.cpu(), rate=rate)
```

**Comment by knoriy** [comment]
Further looking into how this is implemented, the model does not need to be sent to the device. The issue arises when the model is sent to device:
```python
class Synthosiser():
    def __init__(self, model_name:str) -> None:
        self.models, self.cfg, self.task = load_model_ensemble_and_task_from_hf_hub(
            model_name,
            arg_overrides={"vocoder": "hifigan", "fp16": False}
        )

        self.model = self.models[0]

        TTSHubInterface.update_cfg_with_data_cfg(self.cfg, self.task.data_cfg)
        self.generator = self.task.build_generator(self.models, self.cfg)

        self.english_spelling_normalizer = EnglishSpellingNormalizer('/fsx/knoriy/code/text-to-speech/data/english.json')

    def get_audio(self, text):
        sample = TTSHubInterface.get_model_input(self.task, text)

        sample['net_input']['src_tokens'] = sample['net_input']['src_tokens'].to(device)
        sample['net_input']['src_lengths'] = sample['net_input']['src_lengths'].to(device)
        sample['speaker'] = sample['speaker'].to(device) if sample['speaker'] != None else torch.tensor([[0]]).to(device)

        wav, rate = TTSHubInterface.get_prediction(self.task, self.model.to(device), self.generator, sample)

        return text, wav, rate
    def __call__(self, text, dest):
        dest = pathlib.Path(dest)
        if not dest.parent.is_dir():
            dest.parent.mkdir()

        text = self.english_spelling_normalizer(text)
        text, wav, rate = self.get_audio(text)
        return text, wav, rate
```

**Comment by Supermax197** [comment]
model.cuda()
