### ISSUE TITLE
windows UnicodeDecodeError 

### ISSUE THREAD

**Issue by LaHeriody** [facebookresearch/fairseq#4883]
as I ran [Evaluating Pre-trained Models](https://fairseq.readthedocs.io/en/latest/getting_started.html) in the document
`curl https://dl.fbaipublicfiles.com/fairseq/models/wmt14.v2.en-fr.fconv-py.tar.bz2 | tar xvjf -`
`MODEL_DIR=wmt14.en-fr.fconv-py
fairseq-interactive \
    --path $MODEL_DIR/model.pt $MODEL_DIR \
    --beam 5 --source-lang en --target-lang fr \
    --tokenizer moses \
    --bpe subword_nmt --bpe-codes $MODEL_DIR/bpecodes`
it reports 
`2022-11-30 15:15:59 | INFO | fairseq.tasks.translation | [en] dictionary: 43771 types
2022-11-30 15:15:59 | INFO | fairseq.tasks.translation | [fr] dictionary: 43807 types
2022-11-30 15:15:59 | INFO | fairseq_cli.interactive | loading model(s) from wmt14.en-fr.fconv-py/model.pt
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\Scripts\fairseq-interactive-script.py", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-interactive')())
  File "e:\github_repository\fairseq\fairseq_cli\interactive.py", line 313, in cli_main
    distributed_utils.call_main(convert_namespace_to_omegaconf(args), main)
  File "e:\github_repository\fairseq\fairseq\distributed\utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "e:\github_repository\fairseq\fairseq_cli\interactive.py", line 173, in main
    bpe = task.build_bpe(cfg.bpe)
  File "e:\github_repository\fairseq\fairseq\tasks\fairseq_task.py", line 631, in build_bpe
    return encoders.build_bpe(args)
  File "e:\github_repository\fairseq\fairseq\registry.py", line 61, in build_x
    return builder(cfg, *extra_args, **extra_kwargs)
  File "e:\github_repository\fairseq\fairseq\data\encoders\subword_nmt_bpe.py", line 37, in __init__
    self.bpe = apply_bpe.BPE(
  File "D:\ProgramData\Anaconda3\lib\site-packages\subword_nmt\apply_bpe.py", line 48, in __init__
    self.bpe_codes = [tuple(item.strip('\r\n ').split(' ')) for (n, item) in enumerate(codes.read().rstrip('\n').split('\n')) if (n < merges or merges == -1)]
UnicodeDecodeError: 'gbk' codec can't decode byte 0x81 in position 164221: illegal multibyte sequence`
I have no idea about that.

environment:
 - fairseq Version (e.g., 1.0 or main): main
 - PyTorch Version (e.g., 1.0):  torch 1.13.0 \ torchaudio  0.13.0 \ torchvision  0.14.0
 - OS (e.g., Linux): windows
 - How you installed fairseq (`pip`, source): 
 `git clone https://github.com/pytorch/fairseq
cd fairseq
pip install --editable ./`
 - Python version: 3.9.12

**Comment by LaHeriody** [comment]
by the way, can fairseq run normally on windows now? I mean are functions are supported?
