### ISSUE TITLE
Can't load NLLB MoE model with torch.load

### ISSUE THREAD

**Issue by fiqas** [facebookresearch/fairseq#4885]
## 🐛 Bug

I'm trying to open and investigate NLLB MoE model (405GB), but can't load it into torch.
Smaller dense models seem to load fine, can access the checkpoint's parameters etc.

### To Reproduce

1. Run cmd '....'

```
>> python3
>> import torch
>> checkpoint = torch.load("nllb200moe54bmodel", map_location=torch.device('cpu'))
```

2. See error

```
  File "/data/user/model_info.py", line 18, in main
    checkpoint = torch.load(args.model, map_location=torch.device('cpu'))
  File "/home/user/.conda/envs/nllb/lib/python3.9/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/user/.conda/envs/nllb/lib/python3.9/site-packages/torch/serialization.py", line 762, in _legacy_load
    return legacy_load(f)
  File "/home/user/.conda/envs/nllb/lib/python3.9/site-packages/torch/serialization.py", line 687, in legacy_load
    tar.extract('storages', path=tmpdir)
  File "/home/user/.conda/envs/nllb/lib/python3.9/tarfile.py", line 2077, in extract
    tarinfo = self.getmember(member)
  File "/home/user/.conda/envs/nllb/lib/python3.9/tarfile.py", line 1799, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'storages' not found"
```

#### Code sample

```
import torch
checkpoint = torch.load("nllb200moe54bmodel", map_location=torch.device('cpu'))
```

### Expected behavior

It should load with no error and parameters should be accessible.

### Environment

 - fairseq Version: nllb branch
 - PyTorch Version: '1.10.1+cu113'
 - OS (e.g., Linux): Ubuntu 22.04.1 LTS
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source):
 
```
git clone https://github.com/facebookresearch/fairseq.git
cd fairseq
git checkout nllb
pip install -e .
python setup.py build_ext --inplace
```
 
 - Python version:  3.9.13
 - CUDA/cuDNN version: 11.6
 - GPU models and configuration: CPU only just to load the model into memory
 - Any other relevant information:

**Comment by fiqas** [comment]
Any progress on that? Can you confirm your upload is okay or is it the code issue?

**Comment by layerkugou** [comment]
good  thankyou

**Comment by fiqas** [comment]
Any update on that?

I tried loading the NLLB MoE model through buffer and it gets this error instead:

```
>>> import io
>>> import torch
>>> f = open('../snkashya/nllb200moe54bmodel', 'rb')
>>> buffer = io.BytesIO(f.read())
>>> torch.load(buffer)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/miniconda3/lib/python3.9/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/miniconda3/lib/python3.9/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'm'.
```

I'm working on a 2TB RAM machine, so OOM isn't the case here.

**Comment by untrix** [comment]
The file nllb200moe54bmodel is a tar file. Extract it using 'tar -xf nllb200moe54bmodel' and it will create a folder called model_moe_54b with lots of checkpoints files inside it. I think each checkpoint_2_300000-rank-*.pt files holds weights of one expert (there are 256 in all) and the checkpoint_2_300000-shared.pt file holds the rest of the weights.

torch.load('/data/model_moe_54b/checkpoint_2_300000-shared.pt', map_location='cpu')
