### ISSUE TITLE
TypeError: Can't instantiate abstract class TrainModule with abstract methods requirements

### ISSUE THREAD

**Issue by sanjibnarzary** [facebookresearch/fairseq#4919]
### Before asking:
1. search the issues. [x]
2. search the docs. [x]

#### Trying to train NLLB but got an error?
```
TypeError: Can't instantiate abstract class TrainModule with abstract methods requirements
```

### Complete Error
```
examples/nllb/modeling/train/train_script.py:287: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="conf", config_name="base_config")
/home/sn/miniconda3/envs/nllb/lib/python3.8/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/next/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
Error executing job with overrides: ['cfg=bilingual', 'cfg.fairseq_root=/home/sn/phd/experiments/2022-2023/nllb/fairseq', 'cfg.output_dir=/home/sn/outdir/nllb', 'cfg.dropout=0.1']
Traceback (most recent call last):
  File "examples/nllb/modeling/train/train_script.py", line 294, in <module>
    main()
  File "/home/sn/miniconda3/envs/nllb/lib/python3.8/site-packages/hydra/main.py", line 90, in decorated_main
    _run_hydra(
  File "/home/sn/miniconda3/envs/nllb/lib/python3.8/site-packages/hydra/_internal/utils.py", line 389, in _run_hydra
    _run_app(
  File "/home/sn/miniconda3/envs/nllb/lib/python3.8/site-packages/hydra/_internal/utils.py", line 452, in _run_app
    run_and_report(
  File "/home/sn/miniconda3/envs/nllb/lib/python3.8/site-packages/hydra/_internal/utils.py", line 216, in run_and_report
    raise ex
  File "/home/sn/miniconda3/envs/nllb/lib/python3.8/site-packages/hydra/_internal/utils.py", line 213, in run_and_report
    return func()
  File "/home/sn/miniconda3/envs/nllb/lib/python3.8/site-packages/hydra/_internal/utils.py", line 453, in <lambda>
    lambda: hydra.run(
  File "/home/sn/miniconda3/envs/nllb/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/sn/miniconda3/envs/nllb/lib/python3.8/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/sn/miniconda3/envs/nllb/lib/python3.8/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "examples/nllb/modeling/train/train_script.py", line 289, in main
    train_module = TrainModule(config)
TypeError: Can't instantiate abstract class TrainModule with abstract methods requirements
```
#### Code
```
export OUTPUT_DIR=/tmp/nllb
export DROP=0.1
python examples/nllb/modeling/train/train_script.py   \
  cfg=bilingual  \
  cfg.fairseq_root=$(pwd)  \
  cfg.output_dir=$OUTPUT_DIR   \
  cfg.dropout=$DROP
```

#### What's your environment?

 - fairseq Version (e.g., nllb): nllb
 - PyTorch Version (e.g., 1.10): 1.10.1+cu113
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed fairseq (`pip`,`source`):
 - Build command you used (if compiling from source): `pip install --editable .`
 - Python version: 3.8
 - CUDA/cuDNN version: 11.3
 - GPU models and configuration: Tesla V100
 - Any other relevant information:

**Comment by edchengg** [comment]
any updates on this? I encountered the same issue. @elbayadm

**Comment by robotsp** [comment]
The same issue here. Did you solve the problem? @sanjibnarzary @edchengg @elbayadm

**Comment by martinbombin** [comment]
Hi, I solved by adding this to the fairseq/examples/nllb/modeling/train/train_script.py

![Captura de pantalla de 2023-03-07 11-34-23](https://user-images.githubusercontent.com/34379073/223400366-aa7afb3a-ced7-4ad7-9c60-bba765809e0f.png)

But not sure if it will work, I have loading problems due to a vocabulary mismatch in last steps.
