### ISSUE TITLE
fairseq-train not recognizing dictionary path's created by fairseq-preprocess

### ISSUE THREAD

**Issue by FayZ676** [facebookresearch/fairseq#4928]
## 🐛 Bug

I run the following preprocessing script
```
fairseq-preprocess --destdir data-bin/captions \
  --source-lang prompt --target-lang completion \
  --trainpref caption_datasets/howard/fairseq/train \
  --validpref caption_datasets/howard/fairseq/validation \
  --testpref caption_datasets/howard/fairseq/test
``` 
and get the following files in `data-bin/captions/`
<img width="1610" alt="Screen Shot 2022-12-28 at 12 23 01 PM" src="https://user-images.githubusercontent.com/94952795/209865833-bca7e618-11bc-4f05-a656-70fcfe8cdb04.png">

But when I run the following train script
```
CUDA_VISIBLE_DEVICES=0 \
fairseq-train data-bin/captions \
	--finetune-from-model en_dense_lm_125m/model.pt \
	--arch transformer_lm_gpt \
	--task language_modeling --tokens-per-sample 512 \
	--batch-size 32 \
	--optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
	--max-epoch 1 \
	--fp16
```

Fairseq doesn't recognize the dictionary files and I get the following error
```
Traceback (most recent call last):
  File "/home/faizi/miniconda3/envs/fairseq/bin/fairseq-train", line 8, in <module>
    sys.exit(cli_main())
  File "/home/faizi/projects/model-testing/fairseq/fairseq_cli/train.py", line 574, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/faizi/projects/model-testing/fairseq/fairseq/distributed/utils.py", line 404, in call_main
    main(cfg, **kwargs)
  File "/home/faizi/projects/model-testing/fairseq/fairseq_cli/train.py", line 87, in main
    task = tasks.setup_task(cfg.task)
  File "/home/faizi/projects/model-testing/fairseq/fairseq/tasks/__init__.py", line 47, in setup_task
    return task.setup_task(cfg, **kwargs)
  File "/home/faizi/projects/model-testing/fairseq/fairseq/tasks/language_modeling.py", line 171, in setup_task
    dictionary, output_dictionary = cls.setup_dictionary(args, **kwargs)
  File "/home/faizi/projects/model-testing/fairseq/fairseq/tasks/language_modeling.py", line 155, in setup_dictionary
    dictionary = Dictionary.load(os.path.join(paths[0], "dict.txt"))
  File "/home/faizi/projects/model-testing/fairseq/fairseq/data/dictionary.py", line 226, in load
    d.add_from_file(f)
  File "/home/faizi/projects/model-testing/fairseq/fairseq/data/dictionary.py", line 239, in add_from_file
    raise fnfe
  File "/home/faizi/projects/model-testing/fairseq/fairseq/data/dictionary.py", line 236, in add_from_file
    with open(PathManager.get_local_path(f), "r", encoding="utf-8") as fd:
FileNotFoundError: [Errno 2] No such file or directory: 'data-bin/captions/dict.txt'
```

### Environment

 - fairseq Version (e.g., 1.0 or main): 0.12.2
 - PyTorch Version (e.g., 1.0): 1.13.1
 - OS (e.g., Linux): Ubuntu 22.04
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version: 11.7
 - GPU models and configuration: 4x 3090's
 - Any other relevant information:

**Comment by cordercorder** [comment]
language_modeling task only needs monolingual corpus for training. If you want to use language_modeling task, you can add `--only-source` to `fairseq-preprocess` and remove `--source-lang` and `--target-lang`.  Below is an example:

``` bash
fairseq-preprocess --destdir data-bin/captions \
  --only-source \
  --trainpref caption_datasets/howard/fairseq/train \
  --validpref caption_datasets/howard/fairseq/validation \
  --testpref caption_datasets/howard/fairseq/test
```

Additionally, the names of files to be preprocessed should also change to make `fairseq-preprocess` run well. Please make sure that the file path such as `caption_datasets/howard/fairseq/train`, `caption_datasets/howard/fairseq/validation` and `caption_datasets/howard/fairseq/test` are valid.

**Comment by FayZ676** [comment]
Thanks a lot @cordercorder. I ran the following scripts based on your feedback and managed to resolve the error. Let me know if I missed anything, otherwise I'll close the issue :)

## Preprocessing
```
fairseq-preprocess --destdir data-bin/captions \
	--only-source \
	--srcdict en_dense_lm_125m/dict.txt \
	--trainpref caption_datasets/howard/fairseq/train.txt \
	--validpref caption_datasets/howard/fairseq/validation.txt \
	--testpref caption_datasets/howard/fairseq/test.txt
```

## Fine Tuning
```
CUDA_VISIBLE_DEVICES=0,1 \
fairseq-train data-bin/captions \
	--finetune-from-model en_dense_lm_125m/model.pt \
	--task language_modeling --tokens-per-sample 512 \
	--arch transformer_lm_gpt \
	--batch-size 4 \
	--optimizer adam --adam-eps 1e-06 --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
	--max-epoch 1 \
	--fp16
```
