### ISSUE TITLE
omegaconf.errors.ConfigAttributeError: Key 'input_feat_per_channel' is not in struct

### ISSUE THREAD

**Issue by srksaurabh1** [facebookresearch/fairseq#4932]
## 🐛 Bug

I Have been training the wav2vec2 model. I have done pertaining and fine-tuning. Right now I want to run the inference for this which was earlier speech_recogntion, which has now been merged into speect_to_text. 
I am trying to run the inference. But I am getting the error, that 'input_feat_per_channel' key is not in my model's configuration file.

### To Reproduce
```
fairseq-interactive data_path \
--config-yam config_path+config.yaml \
--task speech_to_text \
--path path_to_checkpoint.pt \
--max-tokens 50000 --beam 4 --scoring wer
```
#### My code
```
fairseq-interactive /home/saurabh/python/fairseq/fairseq/examples/my_exp/small_dataset/train \
--config-yaml /home/saurabh/python/fairseq/fairseq/examples/wav2vec/config/pretraining/wav2vec2_base_librispeech.yaml \
--task speech_to_text \
--path /home/saurabh/python/fairseq/fairseq/examples/my_exp/saved_model/pre_train/checkpoint/checkpoint_best.pt \
--max-tokens 50000 --beam 5 --scoring were
```

#### Error which I am getting

```
2023-01-04 12:37:49 | INFO | fairseq_cli.interactive | loading model(s) from /home/saurabh/python/fairseq/fairseq/examples/vakyansh-wav2vec2-experimentation/checkpoints/finetuning/checkpoint_best.pt
Traceback (most recent call last):
  File "/home/saurabh/python/fairseq/bin/fairseq-interactive", line 8, in <module>
    sys.exit(cli_main())
  File "/home/saurabh/python/fairseq/fairseq/fairseq_cli/interactive.py", line 313, in cli_main
    distributed_utils.call_main(convert_namespace_to_omegaconf(args), main)
  File "/home/saurabh/python/fairseq/fairseq/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "/home/saurabh/python/fairseq/fairseq/fairseq_cli/interactive.py", line 145, in main
    models, _model_args = checkpoint_utils.load_model_ensemble(
  File "/home/saurabh/python/fairseq/fairseq/fairseq/checkpoint_utils.py", line 367, in load_model_ensemble
    ensemble, args, _task = load_model_ensemble_and_task(
  File "/home/saurabh/python/fairseq/fairseq/fairseq/checkpoint_utils.py", line 473, in load_model_ensemble_and_task
    model = task.build_model(cfg.model, from_checkpoint=True)
  File "/home/saurabh/python/fairseq/fairseq/fairseq/tasks/speech_to_text.py", line 126, in build_model
    args.input_feat_per_channel = self.data_cfg.input_feat_per_channel
  File "/home/saurabh/python/fairseq/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 285, in __setattr__
    raise e
  File "/home/saurabh/python/fairseq/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 282, in __setattr__
    self.__set_impl(key, value)
  File "/home/saurabh/python/fairseq/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 266, in __set_impl
    self._set_item_impl(key, value)
  File "/home/saurabh/python/fairseq/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 398, in _set_item_impl
    self._validate_set(key, value)
  File "/home/saurabh/python/fairseq/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 143, in _validate_set
    self._validate_set_merge_impl(key, value, is_assign=True)
  File "/home/saurabh/python/fairseq/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 176, in _validate_set_merge_impl
    target = self._get_node(key)
  File "/home/saurabh/python/fairseq/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 383, in _get_node
    self._validate_get(key)
  File "/home/saurabh/python/fairseq/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 135, in _validate_get
    self._format_and_raise(
  File "/home/saurabh/python/fairseq/lib/python3.10/site-packages/omegaconf/base.py", line 95, in _format_and_raise
    format_and_raise(
  File "/home/saurabh/python/fairseq/lib/python3.10/site-packages/omegaconf/_utils.py", line 694, in format_and_raise
    _raise(ex, cause)
  File "/home/saurabh/python/fairseq/lib/python3.10/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ConfigAttributeError: Key 'input_feat_per_channel' is not in struct
	full_key: model.input_feat_per_channel
	reference_type=Any
	object_type=dict
```

### Environment

 - fairseq Version (e.g., 1.0 or main): 0.12.1+d11b8fb
 - PyTorch Version (e.g., 1.0): 1.13.0
 - OS (e.g., Linux): Ubuntu 22.04
 - How you installed fairseq (`pip`, source): pip + source
 - Python version: 3.10.6
 - GPU models and configuration: NVIDIA GM108M [GeForce 940MX]

**Comment by 9seven** [comment]
Same problem has been bothered me. Please let me know if it is already solved!!!
