### ISSUE TITLE
Exception: Could not infer language pair, please provide it explicitly

### ISSUE THREAD

**Issue by FayZ676** [facebookresearch/fairseq#4934]
## 🐛 Bug

I am trying to finetune the `dense_125m` model from the [moe_lm example](https://github.com/facebookresearch/fairseq/tree/main/examples/moe_lm) on custom data as a test before stepping up to finetune the larger dense models on custom data. I have had some help through the issues and have managed to get to the inference step.
### I am able to preprocess my data:
```
fairseq-preprocess --destdir data-bin/captions \
	--only-source \
	--srcdict en_dense_lm_125m/dict.txt \
	--trainpref caption_datasets/howard/fairseq/train.txt \
	--validpref caption_datasets/howard/fairseq/validation.txt \
	--testpref caption_datasets/howard/fairseq/test.txt
```
### I am also able to fine tune on my data:
```
CUDA_VISIBLE_DEVICES=0,1,2,3 \
fairseq-train data-bin/captions \
	--finetune-from-model en_dense_lm_125m/model.pt \
	--task language_modeling --tokens-per-sample 512 \
	--arch transformer_lm_gpt \
	--batch-size 32 \
	--optimizer adam --adam-eps 1e-06 --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
	--max-epoch 1 \
	--lr 0.01 \
	--fp16
```
### But I am unable to run inference with either `fairseq-generate` or `fairseq-interactive`:
```
# when trying fairseq-generate
fairseq-generate data-bin/captions \
  --path checkpoints/checkpoint_best.pt \
  --max-sentences 1 \
	--beam 5

# when trying fairseq-interactive
fairseq-interactive data-bin/captions \
  --path checkpoints/checkpoint_best.pt \
  --max-sentences 1 \
	--beam 5
```

### I get the following error:
```
Traceback (most recent call last):
  File "/home/faizi/miniconda3/envs/fairseq/bin/fairseq-generate", line 8, in <module>
    sys.exit(cli_main())
  File "/home/faizi/projects/model-testing/fairseq/fairseq_cli/generate.py", line 413, in cli_main
    main(args)
  File "/home/faizi/projects/model-testing/fairseq/fairseq_cli/generate.py", line 50, in main
    return _main(cfg, sys.stdout)
  File "/home/faizi/projects/model-testing/fairseq/fairseq_cli/generate.py", line 83, in _main
    task = tasks.setup_task(cfg.task)
  File "/home/faizi/projects/model-testing/fairseq/fairseq/tasks/__init__.py", line 47, in setup_task
    return task.setup_task(cfg, **kwargs)
  File "/home/faizi/projects/model-testing/fairseq/fairseq/tasks/translation.py", line 303, in setup_task
    raise Exception(
Exception: Could not infer language pair, please provide it explicitly
```

### Environment

 - fairseq Version (e.g., 1.0 or main): 0.12.2
 - PyTorch Version (e.g., 1.0): 1.13.1
 - OS (e.g., Linux): Ubuntu 22.04
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source): `pip install --editable ./`
 - Python version: 3.8.13
 - CUDA/cuDNN version: 11.7
 - GPU models and configuration: 4x NVIDIA 3090

**Comment by FayZ676** [comment]
I was able to get passed the above error by specifying `language_modeling` in `fairseq-interactive`, since it seemed to be using `translation` by default. The translation task requires two dictionary's for the language pair, hence the error. The `language_modeling` task requires a single `dict.txt` file, so specifying it relieves the error.
