### ISSUE TITLE
Dataclass error while importing Fairseq in Python 3.11

### ISSUE THREAD

**Issue by usaraj** [facebookresearch/fairseq#5012]
## 🐛 Bug

FaValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):
1, pip install fairseq==0.12.2
2. from fairseq import *

Trace:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/a1bharat/fairseq/fairseq/__init__.py", line 20, in <module>
    from fairseq.distributed import utils as distributed_utils
  File "/home/a1bharat/fairseq/fairseq/distributed/__init__.py", line 7, in <module>
    from .legacy_distributed_data_parallel import LegacyDistributedDataParallel
  File "/home/a1bharat/fairseq/fairseq/distributed/legacy_distributed_data_parallel.py", line 23, in <module>
    from fairseq.distributed import utils
  File "/home/a1bharat/fairseq/fairseq/distributed/utils.py", line 22, in <module>
    from fairseq.dataclass.configs import DistributedTrainingConfig, FairseqConfig
  File "/home/a1bharat/fairseq/fairseq/dataclass/__init__.py", line 6, in <module>
    from .configs import FairseqDataclass
  File "/home/a1bharat/fairseq/fairseq/dataclass/configs.py", line 906, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1220, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1210, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory

### Environment

 - fairseq Version ( main):
 - PyTorch Version (e.g., 1.0): 1.13.1
 - OS (e.g., Linux): Ubuntu
 - How you installed fairseq (`pip`, source): pip install successful
 - Build command you used (if compiling from source): git clone followed by pip install ./
 - Python version: 3.11
 - CUDA/cuDNN version:  11.6
 - GPU models and configuration: NVIDIA 
 - Any other relevant information:

**Comment by VarunGumma** [comment]
Is Pytorch supporting python 3.11?

**Comment by EmreOzkose** [comment]
Hi, is there any progress on this issue?

**Comment by EmreOzkose** [comment]
I created another conda environment with python 3.9, and didn't face with this error.

**Comment by VarunGumma** [comment]
@EmreOzkose Yes, Pytorch2.0 supports Python 3.11

**Comment by Birch-san** [comment]
https://github.com/facebookresearch/fairseq/blob/176cd934982212a4f75e0669ee81b834ee71dbb0/fairseq/dataclass/configs.py#L1129

I assume it wants something like this:

```diff
@dataclass
class FairseqConfig(FairseqDataclass):
-     common: CommonConfig = CommonConfig()
+     common: CommonConfig = field(default_factory=CommonConfig)
```

**Comment by conan1024hao** [comment]
same problem

**Comment by ashesfall** [comment]
Experiencing this with 3.11.2.

**Comment by Muskan19577** [comment]
I am also facing the same issue. any way to resolve this?

**Comment by ashesfall** [comment]
@Muskan19577 I had to move back to python 3.9

**Comment by thyripian** [comment]
I have this same issue running Python 3.11.3, and the config.py modifications suggested did not resolve the issue.  Looks like the issues migrated to the hydra module, based on the traceback. Please advise. Traceback below.

![fairseq_error_traceback](https://github.com/facebookresearch/fairseq/assets/110140474/ab33e2b0-bfb5-4e68-87a5-eb3c8f7819c7)

**Comment by bit-scientist** [comment]
getting the same ValeError iwth Python 3.11.4. Any suggestions?

**Comment by One-sixth** [comment]
The official fix is too slow, I made a fix version myself.
You can install it using the following command.
v0.12.3.
I conducted a simple test and found no abnormalities.
```
pip install git+https://github.com/One-sixth/fairseq.git
```

**Comment by kabyanil** [comment]
This issue still exists on the official release. I'm using Python 3.11.

**Comment by zhiqu22** [comment]
> This issue still exists on the official release. I'm using Python 3.11.

Same error with Python 3.11.5

**Comment by MrGutarLed** [comment]
Same error with Python 3.11

**Comment by JingThree3** [comment]
Same error with Python 3.11.6 😥

**Comment by aikow** [comment]
The changes to dataclasses are an [official change](https://docs.python.org/3/whatsnew/3.11.html#dataclasses) that was introduced in python 3.11, meaning all 3.11.x and higher won't work. This _will_ need to get changed in fairseq's codebase, and isnt dependent on the exact python 3.11.x version

**Comment by Y-H-Joe** [comment]
```
Python 3.11.4 (main, Jul  5 2023, 14:15:25) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fairseq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/users/nus/zyh/anaconda3/lib/python3.11/site-packages/fairseq/__init__.py", line 20, in <module>
    from fairseq.distributed import utils as distributed_utils
  File "/home/users/nus/zyh/anaconda3/lib/python3.11/site-packages/fairseq/distributed/__init__.py", line 7, in <module>
    from .fully_sharded_data_parallel import (
  File "/home/users/nus/zyh/anaconda3/lib/python3.11/site-packages/fairseq/distributed/fully_sharded_data_parallel.py", line 10, in <module>
    from fairseq.dataclass.configs import DistributedTrainingConfig
  File "/home/users/nus/zyh/anaconda3/lib/python3.11/site-packages/fairseq/dataclass/__init__.py", line 6, in <module>
    from .configs import FairseqDataclass
  File "/home/users/nus/zyh/anaconda3/lib/python3.11/site-packages/fairseq/dataclass/configs.py", line 1104, in <module>
    @dataclass
     ^^^^^^^^^
  File "/home/users/nus/zyh/anaconda3/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/home/users/nus/zyh/anaconda3/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/nus/zyh/anaconda3/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/nus/zyh/anaconda3/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory
```

**Comment by CircuitCM** [comment]
I'm confused. Why is this still not fixed? Will it break backwards compatibility?

**Comment by liyaodev** [comment]
I have encountered these problems, and here is my solution:
**Windows11 environment**

```shell
pip install git+https://github.com/liyaodev/fairseq.git
```
or, download [fairseq-0.12.3.1-cp311-cp311-linux_x86_64.whl](https://github.com/liyaodev/fairseq/releases/tag/v0.12.3.1)
```shell
pip install./fairseq-0.12.3.1-cp311-cp311-linux_x86_64.whl
```

**WSL2(Ubuntu22.04) environment(my local use)**

```shell
pip install git+https://github.com/liyaodev/fairseq.git
```
or, download [fairseq-0.12.3.1-cp311-cp311-linux_x86_64.whl](https://github.com/liyaodev/fairseq/releases/tag/v0.12.3.1)
```shell
pip install./fairseq-0.12.3.1-cp311-cp311-linux_x86_64.whl
```

there's a little tip, best use `hydra-core==1.3.2 omegaconf==2.3.0`

**Comment by VarunGumma** [comment]
Alternately, you can use [my fork of fairseq](https://github.com/VarunGumma/fairseq) which supports `Python 3.11`, Knowledge Distillation, Adapters a few more interesting fixes.

**Comment by vxnuaj** [comment]
!!! this issue needs attention.

Can't use python 3.11.2,

ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory

**Comment by 4ka0** [comment]
This same error is being output with Python 3.12.0.

**Comment by Fmstrat** [comment]
Figured since it's April now, I'd throw in my two cents. Still not working.

**Comment by yjyuanjin** [comment]
> https://github.com/facebookresearch/fairseq/blob/176cd934982212a4f75e0669ee81b834ee71dbb0/fairseq/dataclass/configs.py#L1129
> 
> I assume it wants something like this:
> 
> ```diff
> @dataclass
> class FairseqConfig(FairseqDataclass):
> -     common: CommonConfig = CommonConfig()
> +     common: CommonConfig = field(default_factory=CommonConfig)
> ```

Thanks, it work for me. I change all the error place like your suggestion.

**Comment by last-fisherman** [comment]
@liyaodev, could you please tell me what the exact name of the package you mentioned would be for Windows?

**Comment by liyaodev** [comment]
> @liyaodev, could you please tell me what the exact name of the package you mentioned would be for Windows?

Windows 11 Professional

**Comment by snoop2head** [comment]
Not working in CentOS, Python 3.11

**Comment by tavyscrolls** [comment]
So uh, still not working in Python 3.12 😅 Compile from source fixes tho

**Comment by ZeaMays14142** [comment]
problem still up and critical

**Comment by ZeaMays14142** [comment]
> I have encountered these problems, and here is my solution: **Windows11 environment**
> 
> ```shell
> pip install git+https://github.com/liyaodev/fairseq.git
> ```
> 
> or, download [fairseq-0.12.3.1-cp311-cp311-linux_x86_64.whl](https://github.com/liyaodev/fairseq/releases/tag/v0.12.3.1)
> 
> ```shell
> pip install./fairseq-0.12.3.1-cp311-cp311-linux_x86_64.whl
> ```
> 
> **WSL2(Ubuntu22.04) environment(my local use)**
> 
> ```shell
> pip install git+https://github.com/liyaodev/fairseq.git
> ```
> 
> or, download [fairseq-0.12.3.1-cp311-cp311-linux_x86_64.whl](https://github.com/liyaodev/fairseq/releases/tag/v0.12.3.1)
> 
> ```shell
> pip install./fairseq-0.12.3.1-cp311-cp311-linux_x86_64.whl
> ```
> 
> there's a little tip, best use `hydra-core==1.3.2 omegaconf==2.3.0`

does this still work?

**Comment by neph-64** [comment]
This is what I get.
````
Traceback (most recent call last):
  File "C:\Users\neph\rvc-tts-webui\app.py", line 12, in <module>
    from fairseq import checkpoint_utils
  File "C:\Users\neph\rvc-tts-webui\venv\Lib\site-packages\fairseq\__init__.py", line 20, in <module>
    from fairseq.distributed import utils as distributed_utils
  File "C:\Users\neph\rvc-tts-webui\venv\Lib\site-packages\fairseq\distributed\__init__.py", line 7, in <module>
    from .fully_sharded_data_parallel import (
  File "C:\Users\neph\rvc-tts-webui\venv\Lib\site-packages\fairseq\distributed\fully_sharded_data_parallel.py", line 10, in <module>
    from fairseq.dataclass.configs import DistributedTrainingConfig
  File "C:\Users\neph\rvc-tts-webui\venv\Lib\site-packages\fairseq\dataclass\__init__.py", line 6, in <module>
    from .configs import FairseqDataclass
  File "C:\Users\neph\rvc-tts-webui\venv\Lib\site-packages\fairseq\dataclass\configs.py", line 1104, in <module>
    @dataclass
     ^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\dataclasses.py", line 1268, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\dataclasses.py", line 1258, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\dataclasses.py", line 994, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\dataclasses.py", line 852, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory
(venv) PS C:\Users\neph\rvc-tts-webui> pip install git+https://github.com/liyaodev/fairseq.git
Collecting git+https://github.com/liyaodev/fairseq.git
  Cloning https://github.com/liyaodev/fairseq.git to c:\users\neph\appdata\local\temp\pip-req-build-ktcozen9
  Running command git clone --filter=blob:none --quiet https://github.com/liyaodev/fairseq.git 'C:\Users\neph\AppData\Local\Temp\pip-req-build-ktcozen9'
  Resolved https://github.com/liyaodev/fairseq.git to commit b963eac7a04c539ad59fb1e23277f2ff7ee29e74
  Running command git submodule update --init --recursive -q
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "C:\Users\neph\rvc-tts-webui\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\neph\rvc-tts-webui\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\neph\rvc-tts-webui\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\neph\AppData\Local\Temp\pip-build-env-1tdzldxr\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\neph\AppData\Local\Temp\pip-build-env-1tdzldxr\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\neph\AppData\Local\Temp\pip-build-env-1tdzldxr\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 246, in <module>
      OSError: [WinError 1314] Dem Client fehlt ein erforderliches Recht: '..\\examples' -> 'fairseq\\examples'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
````

**Comment by sh1zooo** [comment]
the problem is still relevant and really critical

**Comment by sh1zooo** [comment]
This is my first answer on any forum, besides, my English is bad. Sorry, guys.
Somehow it worked.
1. Run cmd as administrator(!) - (Running cmd as an administrator fixes the error [WinError 1314])
2. Write this to the console:
```
git clone https://github.com/pytorch/fairseq
cd fairseq
pip install --editable ./
```

3. Next, you may encounter the error "1 required argument is missing, containing only the keyword: 'recursive_guard'". You will need to change the Python version to 3.12.3 or lower. In version 3.12.4, this error will be displayed

**Comment by JackismyShephard** [comment]
> > I have encountered these problems, and here is my solution: **Windows11 environment**
> > ```shell
> > pip install git+https://github.com/liyaodev/fairseq.git
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or, download [fairseq-0.12.3.1-cp311-cp311-linux_x86_64.whl](https://github.com/liyaodev/fairseq/releases/tag/v0.12.3.1)
> > ```shell
> > pip install./fairseq-0.12.3.1-cp311-cp311-linux_x86_64.whl
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **WSL2(Ubuntu22.04) environment(my local use)**
> > ```shell
> > pip install git+https://github.com/liyaodev/fairseq.git
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or, download [fairseq-0.12.3.1-cp311-cp311-linux_x86_64.whl](https://github.com/liyaodev/fairseq/releases/tag/v0.12.3.1)
> > ```shell
> > pip install./fairseq-0.12.3.1-cp311-cp311-linux_x86_64.whl
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > there's a little tip, best use `hydra-core==1.3.2 omegaconf==2.3.0`
> 
> does this still work?

This does not work for me on Windows 11. I am getting `OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\Jacki\AppData\Local\Temp\pip-build-env-x3uaf2ep\overlay\Lib\site-packages\torch\lib\shm`

**Comment by Geremia** [comment]
@[yjyuanjin](https://github.com/facebookresearch/fairseq/issues/5012#issuecomment-2056584837) Your patch didn't work for me.
I'm using Python 3.11 on Linux.

**Comment by FruitPigFoot** [comment]
> The official fix is too slow, I made a fix version myself. You can install it using the following command. v0.12.3. I conducted a simple test and found no abnormalities.
> 
> ```
> pip install git+https://github.com/One-sixth/fairseq.git
> ```

I'm on Ubuntu linux python 3.11.9(conda venv) and pip installing it worked

**Comment by zxpoqas123** [comment]
> I have encountered these problems, and here is my solution: **Windows11 environment**
> 
> ```shell
> pip install git+https://github.com/liyaodev/fairseq.git
> ```
> 
> or, download [fairseq-0.12.3.1-cp311-cp311-linux_x86_64.whl](https://github.com/liyaodev/fairseq/releases/tag/v0.12.3.1)
> 
> ```shell
> pip install./fairseq-0.12.3.1-cp311-cp311-linux_x86_64.whl
> ```
> 
> **WSL2(Ubuntu22.04) environment(my local use)**
> 
> ```shell
> pip install git+https://github.com/liyaodev/fairseq.git
> ```
> 
> or, download [fairseq-0.12.3.1-cp311-cp311-linux_x86_64.whl](https://github.com/liyaodev/fairseq/releases/tag/v0.12.3.1)
> 
> ```shell
> pip install./fairseq-0.12.3.1-cp311-cp311-linux_x86_64.whl
> ```
> 
> there's a little tip, best use `hydra-core==1.3.2 omegaconf==2.3.0`

python 3.11, problem solved! Many thanks.

**Comment by zh-zhang1984** [comment]
> ```diff
> field(default_factory=CommonConfig)
> ```

When I use this, the problem solved but there comes up with anther issue: 
`train.py: error: unrecognized arguments:   --warmup-ratio= 0.01`

**Comment by etale-cohomology** [comment]
I was able to make this work with Python 3.12.

Simply comment out (around line 852):

```
	if f._field_type is _FIELD and f.default.__class__.__hash__ is None:
		raise ValueError(f'mutable default {type(f.default)} for field '
						 f'{f.name} is not allowed: use default_factory')
```

in `{PYTHON_BASE}/lib/python3.12/dataclasses.py`, where `PYTHON_BASE` is wherever your Python is installed.

Don't let Python's pedantry make you waste time.

**Comment by Jiazheng411** [comment]
The issue still exists now
