### ISSUE TITLE
该报错怎么解决：ValueError: Cannot register duplicate model architecture (w2l_conv_glu_enc)

### ISSUE THREAD

**Issue by zhanghaobucunzai** [facebookresearch/fairseq#5026]
## 🐛 Bug

Traceback (most recent call last):
  File "train.py", line 14, in <module>
    cli_main()
  File "/home/swx/fairseq-main/fairseq_cli/train.py", line 560, in cli_main
    parser = options.get_training_parser()
  File "/home/swx/fairseq-main/fairseq/options.py", line 38, in get_training_parser
    parser = get_parser("Trainer", default_task)
  File "/home/swx/fairseq-main/fairseq/options.py", line 234, in get_parser
    utils.import_user_module(usr_args)
  File "/home/swx/fairseq-main/fairseq/utils.py", line 503, in import_user_module
    import_models(models_path, f"{module_name}.models")
  File "/home/swx/fairseq-main/fairseq/models/__init__.py", line 218, in import_models
    importlib.import_module(namespace + "." + model_name)
  File "/usr/local/python3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/swx/fairseq-main/examples/speech_recognition/models/w2l_conv_glu_enc.py", line 173, in <module>
    @register_model_architecture("asr_w2l_conv_glu_encoder", "w2l_conv_glu_enc")
  File "/home/swx/fairseq-main/fairseq/models/__init__.py", line 194, in register_model_arch_fn
    "Cannot register duplicate model architecture ({})".format(arch_name)
ValueError: Cannot register duplicate model architecture (w2l_conv_glu_enc)

**Comment by Sakura-rain** [comment]
I got the same question

**Comment by woqiang0515** [comment]
Have resolve this problems?
