### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by zjwang21** [facebookresearch/fairseq#5032]
### Before asking:
1. search the issues.     yes
2. search the docs.      yes

#### What is your question?
I tried to train roberta with custom criterion and data, after 5 epochs, it gives error that no space left on device. 
Besides, I know that in multi-gpus environment, fairseq uses ddp default. But where dose fairseq use DDP to wrap the model?
#### Code
`Traceback (most recent call last):
  File "/mnt/cache/wangzhijun2/anaconda3/envs/mixbert/lib/python3.9/multiprocessing/queues.py", line 245, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/mnt/cache/wangzhijun2/anaconda3/envs/mixbert/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/mnt/cache/wangzhijun2/anaconda3/envs/mixbert/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 358, in reduce_storage
    fd, size = storage._share_fd_cpu_()
RuntimeError: unable to write to file </torch_4740_2273530805_10039>: No space left on device (28)
`

#### What have you tried?
With MLM criterion, it worked.
#### What's your environment?

 - fairseq Version (e.g., 1.0 or main): main
 - PyTorch Version (e.g., 1.0): 1.12.1 + cu102
 - OS (e.g., Linux):  linux   CenOS-7
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source):
 - Python version: 3.9
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: single node 8 V100 32G GPUS
 - Any other relevant information:

**Comment by alongLFB** [comment]
我刚才也碰到了这个问题，查询了下，好像是 这个安装的依赖东西太多了，tmp盘不够大 快要占满了。pip install的时候文件包会预先下载到tmp盘. 因此要么清空 tmp 目录 要么就可以临时将 /tmp 变大。来尝试进行解决。
