### ISSUE TITLE
omegaconf.errors.MissingMandatoryValue: Missing mandatory value: model         full_key: model         reference_type=Optional[FairseqConfig]         object_type=FairseqConfig

### ISSUE THREAD

**Issue by Minspeech** [facebookresearch/fairseq#5073]
[root@localhost wav2vec2.0]# HYDRA_FULL_ERROR=1 CUDA_VISIBLE_DEVICES=0,1 fairseq-hydra-train     --config-dir /work/la/fairseq/examples/wav2vec/config/pretraining/     --config-name wav2vec2_large_minnanyu0    
Traceback (most recent call last):
  File "/root/anaconda3/envs/fairseq/bin/fairseq-hydra-train", line 8, in <module>
    sys.exit(cli_main())
  File "/work/la/fairseq/fairseq_cli/hydra_train.py", line 87, in cli_main
    hydra_main()
  File "/root/anaconda3/envs/fairseq/lib/python3.8/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/root/anaconda3/envs/fairseq/lib/python3.8/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra
    run_and_report(
  File "/root/anaconda3/envs/fairseq/lib/python3.8/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/root/anaconda3/envs/fairseq/lib/python3.8/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/root/anaconda3/envs/fairseq/lib/python3.8/site-packages/hydra/_internal/utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "/root/anaconda3/envs/fairseq/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 107, in run
    return run_job(
  File "/root/anaconda3/envs/fairseq/lib/python3.8/site-packages/hydra/core/utils.py", line 129, in run_job
    ret.return_value = task_function(task_cfg)
  File "/work/la/fairseq/fairseq_cli/hydra_train.py", line 27, in hydra_main
    _hydra_main(cfg)
  File "/work/la/fairseq/fairseq_cli/hydra_train.py", line 31, in _hydra_main
    add_defaults(cfg)
  File "/work/la/fairseq/fairseq/dataclass/initialize.py", line 42, in add_defaults
    field_cfg = cfg.get(k)
  File "/root/anaconda3/envs/fairseq/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 357, in get
    self._format_and_raise(key=key, value=None, cause=e)
  File "/root/anaconda3/envs/fairseq/lib/python3.8/site-packages/omegaconf/base.py", line 95, in _format_and_raise
    format_and_raise(
  File "/root/anaconda3/envs/fairseq/lib/python3.8/site-packages/omegaconf/_utils.py", line 694, in format_and_raise
    _raise(ex, cause)
  File "/root/anaconda3/envs/fairseq/lib/python3.8/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.MissingMandatoryValue: Missing mandatory value: model
        full_key: model
        reference_type=Optional[FairseqConfig]
        object_type=FairseqConfig

**Comment by shijie-dev** [comment]
不知道，，，好难受

**Comment by shijie-dev** [comment]
Have you solved it?

**Comment by shijie-dev** [comment]
I feel terrible
