### ISSUE TITLE
when use asr infer it get something wrong

### ISSUE THREAD

**Issue by lisea2017** [facebookresearch/fairseq#5172]
> python examples/mms/asr/infer/mms_infer.py --model "./examples/mms/mms1b_l1107.pt" --lang eng --audio "./examples/mms/example.wav"

Traceback (most recent call last):
  File "/data1/ai/fairseq/examples/speech_recognition/new/infer.py", line 21, in <module>
    from examples.speech_recognition.new.decoders.decoder_config import (
  File "/data1/ai/fairseq/examples/speech_recognition/__init__.py", line 1, in <module>
    from . import criterions, models, tasks  # noqa
  File "/data1/ai/fairseq/examples/speech_recognition/criterions/__init__.py", line 15, in <module>
    importlib.import_module(
  File "/data1/miniconda3/envs/fairseq/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/data1/ai/fairseq/examples/speech_recognition/criterions/cross_entropy_acc.py", line 13, in <module>
    from fairseq import utils
  File "/data1/ai/fairseq/fairseq/__init__.py", line 33, in <module>
    import fairseq.criterions  # noqa
  File "/data1/ai/fairseq/fairseq/criterions/__init__.py", line 18, in <module>
    (
TypeError: cannot unpack non-iterable NoneType object
CompletedProcess(args='\n        PYTHONPATH=. PREFIX=INFER HYDRA_FULL_ERROR=1 python examples/speech_recognition/new/infer.py -m --config-dir examples/mms/asr/config/ --config-name infer_common decoding.type=viterbi dataset.max_tokens=1440000 distributed_training.distributed_world_size=1 "common_eval.path=\'./examples/mms/mms1b_l1107.pt\'" task.data=/tmp/tmpkwc5qdz4 dataset.gen_subset="eng:dev" common_eval.post_process=letter decoding.results_path=/tmp/tmpkwc5qdz4 \n        ', returncode=1)
Traceback (most recent call last):
  File "/data1/ai/fairseq/examples/mms/asr/infer/mms_infer.py", line 64, in <module>
    process(args)
  File "/data1/ai/fairseq/examples/mms/asr/infer/mms_infer.py", line 54, in process
    with open(tmpdir/"hypo.word") as fr:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpkwc5qdz4/hypo.word'

**Comment by lisea2017** [comment]
Now it is working fine, but it takes a very long time. What's the situation?
![image](https://github.com/facebookresearch/fairseq/assets/133492104/0a7045a1-c2c8-4622-9c85-706d6f15c6c1)

**Comment by SukhbatDavaanym** [comment]
I get the same result as yours in the first comment such as : 
 .... . .. . .. . .
 https://github.com/facebookresearch/fairseq/issues/5172#issuecomment-1567935596. 
 How did you make it work? can you explain please

**Comment by jianhuihi** [comment]
same

**Comment by davidvisleer** [comment]
Seems related to #5117, 
take a look at this [comment](https://github.com/facebookresearch/fairseq/issues/5117#issuecomment-1567637590)

**Comment by lisea2017** [comment]
> I get the same result as yours in the first comment such as : .... . .. . .. . . [#5172 (comment)](https://github.com/facebookresearch/fairseq/issues/5172#issuecomment-1567935596). How did you make it work? can you explain please

You can try entering the fairseq directory and then use pip install --editable ./

**Comment by androstj** [comment]
Seems like it has been resolved. I will close this issue.
