### ISSUE TITLE
pip install --editable commands fails on Windows 11

### ISSUE THREAD

**Issue by hamin123** [facebookresearch/fairseq#5182]
## 🐛 Bug

CUDA is available, and nvcc --version command give CUD build as 11.7, however pip install --editable ./ fails with error given below.

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd 'pip install --editable ./'
2. See error

### Environment

 - fairseq Version (e.g. main): main
 - PyTorch Version : 
 - OS (e.g., Linux): Windows 11
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version: 11.7
 - GPU models and configuration:
 - Any other relevant information:

### Additional context

Obtaining file:///G:/fairseq
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7'
      Traceback (most recent call last):
        File "C:\Users\GNG\.conda\envs\metamms\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\GNG\.conda\envs\metamms\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\GNG\.conda\envs\metamms\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "C:\Users\GNG\AppData\Local\Temp\pip-build-env-1i71plwt\overlay\Lib\site-packages\setuptools\build_meta.py", line 450, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "C:\Users\GNG\AppData\Local\Temp\pip-build-env-1i71plwt\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\GNG\AppData\Local\Temp\pip-build-env-1i71plwt\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\GNG\AppData\Local\Temp\pip-build-env-1i71plwt\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 246, in <module>
      OSError: [WinError 1314] A required privilege is not held by the client: '..\\examples' -> 'fairseq\\examples'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by theshyPika** [comment]
hello, the same question I have met. I installed both windows11 SDK and MSVC v143- vs 2022 C++ these two components by Visual Studio Installer and finally solved the error. If install one of them only will throw new exception information. For Windows user.

**Comment by AnkiDord** [comment]
> hello, the same question I have met. I installed both windows11 SDK and MSVC v143- vs 2022 C++ these two components by Visual Studio Installer and finally solved the error. If install one of them only will throw new exception information. For Windows user.

Hello，I had installed both windows11 SDK and MSVC v143- vs 2022 C++ on my computer. But I still have the same problem。

**Comment by cainslayer** [comment]
I have a **temporary** method to make the installation succeeded in **Windows**.
We can look into the setup.py, here is the code:

``` python
if __name__ == "__main__":
    try:
        # symlink examples into fairseq package so package_data accepts them
        fairseq_examples = os.path.join("fairseq", "examples")
        if "build_ext" not in sys.argv[1:] and not os.path.exists(fairseq_examples):
            os.symlink(os.path.join("..", "examples"), fairseq_examples)

        package_data = {
            "fairseq": (
                get_files(fairseq_examples)
                + get_files(os.path.join("fairseq", "config"))
            )
        }
        do_setup(package_data)
    finally:
        if "build_ext" not in sys.argv[1:] and os.path.islink(fairseq_examples):
            os.unlink(fairseq_examples)
```

This code do 3 things:
1. Symlink fairseq\example into ..\example
2. execute `get_files` and pass to installation
3. Unlink ..\example

We can print these paths respectively:
``` python
print(os.path.abspath(os.path.join("..", "examples")));
print(os.path.abspath(os.path.join("fairseq", "examples")));
```
D:\git\examples
D:\git\fairseq\fairseq\examples

Therefore these code is for some **compatibility**. But in windows, it is perhaps meaningless.
**We can just pass the 'example' folder to installation, and don't make symlink.**
**Here is steps:**

1. clone the project

2. modify code
You can just substitute the origin code with the following:
``` python
if __name__ == "__main__":
    try:
        print(os.path.abspath(os.path.join("..", "examples")));
        print(os.path.abspath(os.path.join("fairseq", "examples")));
        # symlink examples into fairseq package so package_data accepts them
        fairseq_examples = os.path.join("fairseq", "examples")
        if "build_ext" not in sys.argv[1:] and not os.path.exists(fairseq_examples):
            #os.symlink(os.path.join("..", "examples"), fairseq_examples)
            pass

        package_data = {
            "fairseq": (
                #get_files(fairseq_examples)
                get_files("examples")
                + get_files(os.path.join("fairseq", "config"))
            )
        }
        do_setup(package_data)
    finally:
        if "build_ext" not in sys.argv[1:] and os.path.islink(fairseq_examples):
            #os.unlink(fairseq_examples)
            pass
```

3. install the package
``` bash
pip install .
```
