### ISSUE TITLE
ValueError: cannot register model architecture (w2l_conv_glu_enc)

### ISSUE THREAD

**Issue by vivektyagiibm** [facebookresearch/fairseq#5224]
## 🐛 Bug

I have installed fairseq following the instructions on your site 
git clone https://github.com/pytorch/fairseq
cd fairseq
pip install --editable ./

Then I follow the instructions at https://github.com/facebookresearch/fairseq/tree/main/examples/speech_recognition to train a Tranformers speech recognition model in Librispeech. 

I have prepared the Librispeech data using command 
pwd
/home/vivek/fairseq/
./examples/speech_recognition/datasets/prepare-librispeech.sh Libri_raw-data Libri_processed_data 

and it creates dirs under Libri_processed_data 

The I try to train the model using the command

python train.py Libri_processed_data  --save-dir Libri_model --max-epoch 80 --task speech_recognition --arch vggtransformer_2 --optimizer adadelta --lr 1.0 --adadelta-eps 1e-8 --adadelta-rho 0.95 --clip-norm 10.0  --max-tokens 5000 --log-format json --log-interval 1 --criterion cross_entropy_acc --user-dir examples/speech_recognition/

However it crashes with the error: 

base) vivek@vivek-deeplearning:~/fairseq$ python train.py Libri_processed_data/ --save-dir Libri_model/ --max-epoch 80 --task speech_recognition --arch vggtransformer --optimizer adadelta --lr 1.0 --adadelta-eps 1e-8 --adadelta-rho 0.95 --clip-norm 10.0  --max-tokens 5000 --log-format json --log-interval 1 --criterion cross_entropy_acc --user-dir examples/speech_recognition/
2023-06-28 23:54:58 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
Traceback (most recent call last):
  File "/home/vivek/fairseq/train.py", line 14, in <module>
    cli_main()
  File "/home/vivek/fairseq/fairseq_cli/train.py", line 558, in cli_main
    parser = options.get_training_parser()
  File "/home/vivek/fairseq/fairseq/options.py", line 38, in get_training_parser
    parser = get_parser("Trainer", default_task)
  File "/home/vivek/fairseq/fairseq/options.py", line 234, in get_parser
    utils.import_user_module(usr_args)
  File "/home/vivek/fairseq/fairseq/utils.py", line 503, in import_user_module
    import_models(models_path, f"{module_name}.models")
  File "/home/vivek/fairseq/fairseq/models/__init__.py", line 218, in import_models
    importlib.import_module(namespace + "." + model_name)
  File "/home/vivek/anaconda3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/vivek/fairseq/examples/speech_recognition/models/w2l_conv_glu_enc.py", line 174, in <module>
    def w2l_conv_glu_enc(args):
  File "/home/vivek/fairseq/fairseq/models/__init__.py", line 193, in register_model_arch_fn
    raise ValueError(
ValueError: Cannot register duplicate model architecture (w2l_conv_glu_enc)

 

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

I have prepared the Librispeech data using command 
pwd
/home/vivek/fairseq/
./examples/speech_recognition/datasets/prepare-librispeech.sh Libri_raw-data Libri_processed_data 

and it creates dirs under Libri_processed_data 

The I try to train the model using the command

python train.py Libri_processed_data  --save-dir Libri_model --max-epoch 80 --task speech_recognition --arch vggtransformer_2 --optimizer adadelta --lr 1.0 --adadelta-eps 1e-8 --adadelta-rho 0.95 --clip-norm 10.0  --max-tokens 5000 --log-format json --log-interval 1 --criterion cross_entropy_acc --user-dir examples/speech_recognition/

However it crashes with the error: 

base) vivek@vivek-deeplearning:~/fairseq$ python train.py Libri_processed_data/ --save-dir Libri_model/ --max-epoch 80 --task speech_recognition --arch vggtransformer --optimizer adadelta --lr 1.0 --adadelta-eps 1e-8 --adadelta-rho 0.95 --clip-norm 10.0  --max-tokens 5000 --log-format json --log-interval 1 --criterion cross_entropy_acc --user-dir examples/speech_recognition/
2023-06-28 23:54:58 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
Traceback (most recent call last):
  File "/home/vivek/fairseq/train.py", line 14, in <module>
    cli_main()
  File "/home/vivek/fairseq/fairseq_cli/train.py", line 558, in cli_main
    parser = options.get_training_parser()
  File "/home/vivek/fairseq/fairseq/options.py", line 38, in get_training_parser
    parser = get_parser("Trainer", default_task)
  File "/home/vivek/fairseq/fairseq/options.py", line 234, in get_parser
    utils.import_user_module(usr_args)
  File "/home/vivek/fairseq/fairseq/utils.py", line 503, in import_user_module
    import_models(models_path, f"{module_name}.models")
  File "/home/vivek/fairseq/fairseq/models/__init__.py", line 218, in import_models
    importlib.import_module(namespace + "." + model_name)
  File "/home/vivek/anaconda3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/vivek/fairseq/examples/speech_recognition/models/w2l_conv_glu_enc.py", line 174, in <module>
    def w2l_conv_glu_enc(args):
  File "/home/vivek/fairseq/fairseq/models/__init__.py", line 193, in register_model_arch_fn
    raise ValueError(
ValueError: Cannot register duplicate model architecture (w2l_conv_glu_enc)

#### Code sample
pls see above

### Expected behavior
Please improve the documentation of https://github.com/facebookresearch/fairseq/tree/main/examples/speech_recognition

we don't know what the args are to train.py and what they do. 

Also is it necessary to have complex decorators for register models etc. 
A straightforward Transformers for speech recognition code with model code,  train code and decoder code will be ideal for analysis purpose instead of a lot of boiler plate decorator code for registering model etc. Thank you for taking this request into consideration.  

Expected behaviour: a normal training of the model should take place and model should  be saved in the -save-dir Libri_model/  dir. (that what I'm assuming from the command above )

### Environment

 - fairseq Version (e.g., 1.0 or main):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by ussenuk** [comment]
Having the same problem

**Comment by ussenuk** [comment]
@vivektyagiibm The error message indicates that the script is trying to register a model architecture with the name w2l_conv_glu_enc, but there is already a model architecture with that name registered. This is causing a ValueError to be raised.

One possible solution to this issue is to check if the model architecture with the name w2l_conv_glu_enc is already registered before trying to register it again. You can do this by adding a conditional statement before the registration code that checks if the architecture is already registered. If it is, you can skip the registration step.

This function is used to register a new model architecture. It takes two arguments: model_name and arch_name. The model_name argument specifies the name of the model, while the arch_name argument specifies the name of the architecture.

Go to ``fairseq\models\__init__.py`` :The function first checks if the given model_name is already registered in the MODEL_REGISTRY. If it is not, a ValueError is raised.

Next, the function checks if the given arch_name is already registered in the ARCH_MODEL_REGISTRY. If it is, a ValueError is raised to prevent duplicate architectures from being registered.

If both checks pass, the architecture is registered by adding it to the ARCH_MODEL_REGISTRY, ARCH_MODEL_NAME_REGISTRY, and ARCH_MODEL_INV_REGISTRY dictionaries. The function also stores the architecture configuration function in the ARCH_CONFIG_REGISTRY dictionary.

To implement the solution I mentioned earlier, you can modify this function to add a conditional statement before the second check (the one that checks for duplicate architectures). Here’s an example of how you can do this:

def register_model_arch_fn(fn):
        if model_name not in MODEL_REGISTRY:
            raise ValueError(
                "Cannot register model architecture for unknown model type ({})".format(
                    model_name
                )
            )
        if arch_name in ARCH_MODEL_REGISTRY:
            #raise ValueError(
                #"Cannot register duplicate model architecture ({})".format(arch_name)
            #)
            return fn
        if not callable(fn):
            raise ValueError(
                "Model architecture must be callable ({})".format(arch_name)
            )
        ARCH_MODEL_REGISTRY[arch_name] = MODEL_REGISTRY[model_name]
        ARCH_MODEL_NAME_REGISTRY[arch_name] = model_name
        ARCH_MODEL_INV_REGISTRY.setdefault(model_name, []).append(arch_name)
        ARCH_CONFIG_REGISTRY[arch_name] = fn
        return fn
return register_model_arch_fn

**Comment by vivektyagiibm** [comment]
@ussenuk thanks for your reply and it's great. 
My point is that if it's a tutorial script, it should work with the provided command. 
Actually, I avoided this problem by simple commenting out the model registry decorators and the code went pas this error but then crashed for some other error related to json. 

So it means these example scripts are broken at multiple points and that's not good. the general "~/fairseq/fairseq_cli/train.py" has 100s of arg and there's no documentation of the expected values that we should provide them and what these options do. Think of unix man command. Even a simple documentation of the ~/fairseq/fairseq_cli/train.py options will help, so that a user can modify the default argument (or the faulty arguments baked in the example script)

**Comment by ussenuk** [comment]
@vivektyagiibm I agree with you , most of the fairseq/examples are broken at multiple point
