### ISSUE TITLE
model.w2v_path not available during prepare_audio_v2.sh in wav2vec-U 2.0

### ISSUE THREAD

**Issue by EomSooHwan** [facebookresearch/fairseq#5281]
#### What is your question?

I am trying to replicate wav2vec-U 2.0 (Towards End-to-end Unsupervised Speech Recognition) and am still in the data preparation step. During the `prepare_audio_v2.sh`, however, the code could not run `wav2vec_extract_features.py` because of the following error.

```
DEBUG:hydra.core.utils: Setting JobRuntime: name=UNKNOWN_NAME
DEBUG: hydra.core.utils: Setting JobRuntime: name=utils
DEBUG:hydra.core.utils: Setting JobRuntime: name=utils
Traceback (most recent call last):
File "/mnt/hdd/es yoon/workspace/ICLR24/fairseq/examples/wav2vec/unsupervised/scripts/wav2vec_extrac t_features.py", line 120, in <module>
    main()
File "/mnt/hdd/esyoon/workspace/ICLR24/fairseq/examples/wav2vec/unsupervised/scripts/wav2vec_extract_features.py", line 108, in main
    generator, num = get_iterator(args)
File "/mnt/hdd/es yoon/workspace/ICLR24/fairseq/examples/wav2vec/unsupervised/scripts/wav2vec_extrac t_features.py", line 77, in get_iterator
    reader = Wav2Vec FeatureReader (args.checkpoint, args.layer)
File "/mnt/hdd/es yoon/workspace/ICLR24/fairseq/examples/wav2vec/unsupervised/scripts/wav2vec_extrac t_features.py", line 38, in init
    model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task(
File "/mnt/hdd/esyoon/workspace/ICLR24/Fairseq/fairseq/checkpoint_utils.py", line 484, in load_model_ensemble_and_task
    model = task.build_model(cfg.model, from checkpoint=True)
File "/mnt/hdd/es yoon/workspace/ICLR24/fairseq/fairseq/tasks/audio_pretraining.py", line 224, in bu ild_model
    model = super().build_model(model_cfg, from checkpoint)
File "/mnt/hdd/es yoon/workspace/ICLR24/fairseq/fairseq/tasks/fairseq_task.py", line 355, in build_model
    model = models.build_model(cfg, self, from_checkpoint)
File "/mnt/hdd/es yoon/workspace/ICLR24/fairseq/fairseq/models/__init__.py", line 90, in build_model
    cfg = merge_with_parent(dc(), cfg, from checkpoint)
File "/mnt/hdd/esyoon/workspace/ICLR24/fairseq/fairseq/dataclass/utils.py", line 505, in merge_with _parent
    remove_missing_rec (cfg, dc)
File "/mnt/hdd/esyoon/workspace/ICLR24/fairseq/fairseq/dataclass/utils.py", line 499, in remove_missing_rec
    elif OmegaConf. is_config(src_keys[k]);
File "/mnt/hdd/es yoon/anaconda/envs/cr24/lib/python3.3/site-packages/omegaconf/dictconfig.py", l ine 321, in __getitem__
    self._format_and_raise (key=key, value=None, cause=e)
File "/mnt/hdd/es yoon/anaconda3/envs/iclr24/lib/python3.8/site-packages/omegaconf/base.py", line 95 in _format_and_raise
    format_and_raise(
File "/mnt/hdd/es yoon/anaconda3/envs/iclr24/lib/python3.8/site-packages/omegaconf/_utils.py", line 694, in format_and_raise
    raise(ex, cause)
File "/mnt/hdd/es yoon/anaconda/envs/iclr24/lib/python3.8/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex # set end OC_CAUSE=1 for full backtrace
omegaconf.errors. MissingMandatoryValue: Missing mandatory value: model.w2v_path
        full_key: model.w2v_path
        reference_type=Any
        object_type=dict
```

#### What have you tried?

I have searched for similar issue, but I could not find the exact solution about `Missing mandatory value: model.w2v_path` for w2v-u

#### What's your environment?

 - fairseq Version (e.g., 1.0 or main): main
 - PyTorch Version (e.g., 1.0): 2.0.1+cu117
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source): same as in README
 - Python version: 3.8
 - CUDA/cuDNN version: 11.6 (according to `nvidia-smi`)
 - GPU models and configuration: Quadro RTX 8000 
 - Any other relevant information:

**Comment by EomSooHwan** [comment]
I followed the args_override part of this issue and I think it's now working.
[#4691 ](https://github.com/facebookresearch/fairseq/issues/4691#issuecomment-1248512669)

**Comment by Maverick7t** [comment]
@EomSooHwan how did you solved this i am getting same error

**Comment by EomSooHwan** [comment]
@Maverick7t Sorry, I don't remember exactly, but I think the main key of the solution was to use overriding as in https://github.com/facebookresearch/fairseq/issues/4691#issuecomment-1248512669 so that model.w2v_path is correctly loaded.

**Comment by Maverick7t** [comment]
> @Maverick7t Sorry, I don't remember exactly, but I think the main key of the solution was to use overriding as in [#4691 (comment)](https://github.com/facebookresearch/fairseq/issues/4691#issuecomment-1248512669) so that model.w2v_path is correctly loaded.

i did as they said in that #4691 but still getting the same error

**Comment by KikeLeon03** [comment]
I am getting the same error running `prepare_audio.sh`

@Maverick7t  what w2v model are you using? I am using `wav2vec_small_960h.pt`

**Comment by KikeLeon03** [comment]
Okay @Maverick7t  try other model, I changed my model from w2v2 `wav2vec_small_960h.pt` to [this model](https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_small.pt)

Seems to work, hope it helps
