### ISSUE TITLE
Cannot run mms_infer.py for transcription

### ISSUE THREAD

**Issue by zhhl9101** [facebookresearch/fairseq#5284]
### Hello MMS,
When run mms_infer.py, got issue like that:

#### (base) zhang@local-gpu:~/fairseq$ python examples/mms/asr/infer/mms_infer.py --model ../mms1b_fl102.pt --lang "cmn-script_simplified" --audio ../17_IOS33_000.wav
">>>preparing tmp manifest dir ...
">>>loading model & running inference ...
Traceback (most recent call last):
  File "/home/suzha/miniconda3/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/checkpoint/zhang/INFER/None'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/suzha/miniconda3/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/checkpoint/zhang/INFER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/suzha/miniconda3/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/checkpoint/zhang'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhang/fairseq/examples/speech_recognition/new/infer.py", line 499, in <module>
    cli_main()
  File "/home/zhang/fairseq/examples/speech_recognition/new/infer.py", line 495, in cli_main
    hydra_main()  # pylint: disable=no-value-for-parameter
  File "/home/suzha/miniconda3/lib/python3.9/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/home/suzha/miniconda3/lib/python3.9/site-packages/hydra/_internal/utils.py", line 354, in _run_hydra
    run_and_report(
  File "/home/suzha/miniconda3/lib/python3.9/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/home/suzha/miniconda3/lib/python3.9/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/home/suzha/miniconda3/lib/python3.9/site-packages/hydra/_internal/utils.py", line 355, in <lambda>
    lambda: hydra.multirun(
  File "/home/suzha/miniconda3/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 136, in multirun
    return sweeper.sweep(arguments=task_overrides)
  File "/home/suzha/miniconda3/lib/python3.9/site-packages/hydra/_internal/core_plugins/basic_sweeper.py", line 140, in sweep
    sweep_dir.mkdir(parents=True, exist_ok=True)
  File "/home/suzha/miniconda3/lib/python3.9/pathlib.py", line 1327, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/home/suzha/miniconda3/lib/python3.9/pathlib.py", line 1327, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/home/suzha/miniconda3/lib/python3.9/pathlib.py", line 1327, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/home/suzha/miniconda3/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/checkpoint'
Traceback (most recent call last):
  File "/home/zhang/fairseq/examples/mms/asr/infer/mms_infer.py", line 63, in <module>
    process(args)
  File "/home/zhang/fairseq/examples/mms/asr/infer/mms_infer.py", line 53, in process
    with open(tmpdir/"hypo.word") as fr:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpnf499w7t/hypo.word'

**Comment by marosjev-cde** [comment]
hello @zhhl9101 ,

check this issue: https://github.com/facebookresearch/fairseq/issues/5117. It was already addressed here.

**Comment by zhhl9101** [comment]
> hello @zhhl9101 ,
> 
> check this issue: #5117. It was already addressed here.

Thanks, the isuue is linked there. however, i can not find solution for me.
#5117 has more than 90 comments, which one can solve my problem ?

**Comment by zhhl9101** [comment]
Add open(tmpdir/"hypo.word", 'w').close() before the line 48 in "fairseq\examples\mms\asr\infer\mms_infer.py"

**Comment by spanta28** [comment]
Sorry to bother you here. I am unable to run mms asr transcribe . I am using python3.11 and facing a range of issues from hypo.word not found, AttributeError: 'PosixPath' object has no attribute 'find' and what not.

Going through the issues, there is no landing solutions except lot of comments..
https://github.com/facebookresearch/fairseq/issues/5284 (already tried that solution and lead to my error posted below)
https://github.com/facebookresearch/fairseq/issues/5117 (has no solution)

There are just way too many threads relating to mms asr transcribe issues but no working solutions posted, if there is one set of installation instructions that actually work and are documented somewhere that be great. 

Here is my error:

>>> os.environ["TMPDIR"] ='/Users/spanta/Downloads/fairseq-main/temp_dir'

>>> os.environ["PYTHONPATH"] = "."

>>> os.environ["PREFIX"] = "INFER"

>>> os.environ["HYDRA_FULL_ERROR"] = "1"

>>> os.environ["USER"] = "micro"

>>> os.system('python3.11 examples/mms/asr/infer/mms_infer.py --model "/Users/spanta/Downloads/fairseq/models_new/[mms1b_fl102.pt](http://mms1b_fl102.pt/)" --lang "tel" --audio "/Users/spanta/Documents/test_wav/1.wav"')

>>> preparing tmp manifest dir ...

>>> loading model & running inference ...

/Users/spanta/Downloads/fairseq-main/examples/speech_recognition/new/infer.py:440: UserWarning: 

The version_base parameter is not specified.

Please specify a compatability version level, or None.

Will assume defaults for version 1.1

  @hydra.main(config_path=config_path, config_name="infer")

Traceback (most recent call last):

  File "/Users/spanta/Downloads/fairseq-main/examples/speech_recognition/new/infer.py", line 499, in <module>

    cli_main()

  File "/Users/spanta/Downloads/fairseq-main/examples/speech_recognition/new/infer.py", line 495, in cli_main

    hydra_main()  # pylint: disable=no-value-for-parameter

    ^^^^^^^^^^^^

  File "/opt/homebrew/lib/python3.11/site-packages/hydra/main.py", line 94, in decorated_main

    _run_hydra(

  File "/opt/homebrew/lib/python3.11/site-packages/hydra/_internal/utils.py", line 355, in _run_hydra

    hydra = run_and_report(

            ^^^^^^^^^^^^^^^

  File "/opt/homebrew/lib/python3.11/site-packages/hydra/_internal/utils.py", line 223, in run_and_report

    raise ex

  File "/opt/homebrew/lib/python3.11/site-packages/hydra/_internal/utils.py", line 220, in run_and_report

    return func()

           ^^^^^^

  File "/opt/homebrew/lib/python3.11/site-packages/hydra/_internal/utils.py", line 356, in <lambda>

    lambda: Hydra.create_main_hydra2(

            ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/homebrew/lib/python3.11/site-packages/hydra/_internal/hydra.py", line 61, in create_main_hydra2

    config_loader: ConfigLoader = ConfigLoaderImpl(

                                  ^^^^^^^^^^^^^^^^^

  File "/opt/homebrew/lib/python3.11/site-packages/hydra/_internal/config_loader_impl.py", line 48, in __init__

    self.repository = ConfigRepository(config_search_path=config_search_path)

                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/homebrew/lib/python3.11/site-packages/hydra/_internal/config_repository.py", line 65, in __init__

    self.initialize_sources(config_search_path)

  File "/opt/homebrew/lib/python3.11/site-packages/hydra/_internal/config_repository.py", line 72, in initialize_sources

    scheme = self._get_scheme(search_path.path)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/homebrew/lib/python3.11/site-packages/hydra/_internal/config_repository.py", line 143, in _get_scheme

    idx = path.find("://")

          ^^^^^^^^^

AttributeError: 'PosixPath' object has no attribute 'find'

0
