### ISSUE TITLE
Backwards compatibility with latest sinusoidal embedding change

### ISSUE THREAD

**Issue by timur-sch** [facebookresearch/fairseq#5286]
Hey there,
I am currently trying to reproduce the en-de MustC example for joint speech_text_to_speech translation. Training the models works fine , however upon trying to evaluate the results of the model by using the suggested command

```
python ./fairseq_cli/generate.py \
        ${MANIFEST_ROOT} \
        --task speech_text_joint_to_text \
        --max-tokens 25000 \
        --nbest 1 \
        --results-path ${infer_results} \
        --batch-size 512 \
        --path ${model} \
        --gen-subset tst-COMMON_st \
        --config-yaml config.yaml \
        --scoring sacrebleu \
        --beam 5 --lenpen 1.0 \
        --user-dir examples/speech_text_joint_to_text \
        --load-speech-only
```

I get the following error message:
```

Traceback (most recent call last):
  File "/work/asr3/rossenbach/schuemann/envs/fairseq_22_env/bin/fairseq-generate", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-generate')())
  File "/work/asr3/rossenbach/schuemann/envs/fairseq_22_env/lib/python3.10/site-packages/fairseq_cli/generate.py", line 413, in cli_main
    main(args)
  File "/work/asr3/rossenbach/schuemann/envs/fairseq_22_env/lib/python3.10/site-packages/fairseq_cli/generate.py", line 48, in main
    return _main(cfg, h)
  File "/work/asr3/rossenbach/schuemann/envs/fairseq_22_env/lib/python3.10/site-packages/fairseq_cli/generate.py", line 96, in _main
    models, saved_cfg = checkpoint_utils.load_model_ensemble(
  File "/work/asr3/rossenbach/schuemann/envs/fairseq_22_env/lib/python3.10/site-packages/fairseq/checkpoint_utils.py", line 367, in load_model_ensemble
    ensemble, args, _task = load_model_ensemble_and_task(
  File "/work/asr3/rossenbach/schuemann/envs/fairseq_22_env/lib/python3.10/site-packages/fairseq/checkpoint_utils.py", line 484, in load_model_ensemble_and_task
    model.load_state_dict(
  File "/work/asr3/rossenbach/schuemann/envs/fairseq_22_env/lib/python3.10/site-packages/fairseq/models/fairseq_model.py", line 128, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/work/asr3/rossenbach/schuemann/envs/fairseq_22_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DualInputS2TTransformerModel:
        Missing key(s) in state_dict: "encoder.spch_encoder.encoder.embed_positions._float_tensor", "decoder.text_decoder.embed_positions._float_tensor"
```

I am assuming this is due to one of the latest commits _31fba013a070eaff69dec8642e68e7134d60ab0f_ deleting the `_float_tensor` from the `state_dict`. According to the description of the commit this should have backwards compatibility as the `_float_tensor` is only needed to track if the embedding is on CPU/GPU. However this does not seem to be the case here, or I am missing something entirely. I will try to revert to one of the last commits and see if this issue is resolved. Still, help in regards to if this issue is on my part or a mistake in the commit would be appreciated.

Best regards.

**Comment by timur-sch** [comment]
Update: Reverting the git and retraining the Model did solve this issue for me. So there seems to be an issue with the commit.
