### ISSUE TITLE
mms asr transcribe issues no solution

### ISSUE THREAD

**Issue by spanta28** [facebookresearch/fairseq#5348]
I am unable to run mms asr transcribe . I am using python3.11 and facing a range of issues from hypo.word not found, AttributeError: 'PosixPath' object has no attribute 'find' and what not.

Going through the issues, there are no landing solutions except lot of comments..
https://github.com/facebookresearch/fairseq/issues/5284 (already tried that solution and lead to my error posted below)
https://github.com/facebookresearch/fairseq/issues/5117 (has no solution)

There are just way too many threads relating to mms asr transcribe issues but no working solutions posted, if there is one set of installation instructions that actually work and are documented somewhere that be great. 

Here is my error:

>>> os.environ["TMPDIR"] ='/Users/spanta/Downloads/fairseq-main/temp_dir'

>>> os.environ["PYTHONPATH"] = "."

>>> os.environ["PREFIX"] = "INFER"

>>> os.environ["HYDRA_FULL_ERROR"] = "1"

>>> os.environ["USER"] = "micro"

>>> os.system('python3.11 examples/mms/asr/infer/mms_infer.py --model "/Users/spanta/Downloads/fairseq/models_new/[mms1b_fl102.pt](http://mms1b_fl102.pt/)" --lang "tel" --audio "/Users/spanta/Documents/test_wav/1.wav"')

>>> preparing tmp manifest dir ...

>>> loading model & running inference ...

/Users/spanta/Downloads/fairseq-main/examples/speech_recognition/new/infer.py:440: UserWarning: 

The version_base parameter is not specified.

Please specify a compatability version level, or None.

Will assume defaults for version 1.1

  @hydra.main(config_path=config_path, config_name="infer")

Traceback (most recent call last):

  File "/Users/spanta/Downloads/fairseq-main/examples/speech_recognition/new/infer.py", line 499, in <module>

    cli_main()

  File "/Users/spanta/Downloads/fairseq-main/examples/speech_recognition/new/infer.py", line 495, in cli_main

    hydra_main()  # pylint: disable=no-value-for-parameter

    ^^^^^^^^^^^^

  File "/opt/homebrew/lib/python3.11/site-packages/hydra/main.py", line 94, in decorated_main

    _run_hydra(

  File "/opt/homebrew/lib/python3.11/site-packages/hydra/_internal/utils.py", line 355, in _run_hydra

    hydra = run_and_report(

            ^^^^^^^^^^^^^^^

  File "/opt/homebrew/lib/python3.11/site-packages/hydra/_internal/utils.py", line 223, in run_and_report

    raise ex

  File "/opt/homebrew/lib/python3.11/site-packages/hydra/_internal/utils.py", line 220, in run_and_report

    return func()

           ^^^^^^

  File "/opt/homebrew/lib/python3.11/site-packages/hydra/_internal/utils.py", line 356, in <lambda>

    lambda: Hydra.create_main_hydra2(

            ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/homebrew/lib/python3.11/site-packages/hydra/_internal/hydra.py", line 61, in create_main_hydra2

    config_loader: ConfigLoader = ConfigLoaderImpl(

                                  ^^^^^^^^^^^^^^^^^

  File "/opt/homebrew/lib/python3.11/site-packages/hydra/_internal/config_loader_impl.py", line 48, in __init__

    self.repository = ConfigRepository(config_search_path=config_search_path)

                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/homebrew/lib/python3.11/site-packages/hydra/_internal/config_repository.py", line 65, in __init__

    self.initialize_sources(config_search_path)

  File "/opt/homebrew/lib/python3.11/site-packages/hydra/_internal/config_repository.py", line 72, in initialize_sources

    scheme = self._get_scheme(search_path.path)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/homebrew/lib/python3.11/site-packages/hydra/_internal/config_repository.py", line 143, in _get_scheme

    idx = path.find("://")

          ^^^^^^^^^

AttributeError: 'PosixPath' object has no attribute 'find'

0

**Comment by spanta28** [comment]
I am able to run the code here: https://huggingface.co/spaces/mms-meta/MMS/blob/main/asr.py

**Comment by lazerliu** [comment]
the same error while infering data2vec-asr, have you fixed it in fairseq?

**Comment by s2485523800** [comment]
> the same error while infering data2vec-asr, have you fixed it in fairseq?

hi , i find same error while using fairseq , have you already solvd this problem?

**Comment by xinyiwan** [comment]
Exact same error here with python 3.9.5.
