### ISSUE TITLE
Error when installing fairseq

### ISSUE THREAD

**Issue by ChristopheYe** [facebookresearch/fairseq#5552]
Hi everyone, 

I am running into the following error when trying to install fairseq

pip install fairseq

This is the error in question : 

FileNotFoundError: [Errno 2] No such file or directory: 'fairseq/version.txt'

Thanks for your help.

**Comment by lukatop** [comment]
Same here, I was using python3.9 with pip 24.2 and tried to install fairseq, but getting the same error.

**Comment by CooperWanng** [comment]
same problem
“crtdbg.h”: No such file or directory
python 3.10.6
pip 23.2.1
win 11

**Comment by nnonno** [comment]
pull the repo and install from source. make sure your pip version is lower than 24.1
`pip install --force pip==24.0`
`git clone https://github.com/pytorch/fairseq`
`cd fairseq`
`pip install ./`

Myenv:
python: 3.10.12
pip 24.0
ubuntu 22.04lts

**Comment by juzi24707** [comment]
After uninstalling the hydra-core package, reinstall fairseq, as there is a dependency conflict between these two packages.

**Comment by inconnu11** [comment]
I set pip version == 24.0 and pip install fairseq. It says **fairseq/clib/libbleu/module.cpp:9:10: fatal error: Python.h: 没有那个文件或目录**



`
      running build_ext
      building 'fairseq.libbleu' extension
      creating build/temp.linux-x86_64-cpython-310/fairseq/clib/libbleu
      x86_64-linux-gnu-g++ -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/include/python3.10 -c fairseq/clib/libbleu/libbleu.cpp -o build/temp.linux-x86_64-cpython-310/fairseq/clib/libbleu/libbleu.o -std=c++11 -O3
      x86_64-linux-gnu-g++ -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/include/python3.10 -c fairseq/clib/libbleu/module.cpp -o build/temp.linux-x86_64-cpython-310/fairseq/clib/libbleu/module.o -std=c++11 -O3
      fairseq/clib/libbleu/module.cpp:9:10: fatal error: Python.h: 没有那个文件或目录
          9 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-g++' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fairseq
Failed to build fairseq
ERROR: Could not build wheels for fairseq, which is required to install pyproject.toml-based projects

[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python -m pip install --upgrade pip
`

**Comment by inconnu11** [comment]
If I install from the source like **pip install ./**, it shows like below:

`
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-xh2t6bkj/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-xh2t6bkj/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-xh2t6bkj/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 12, in <module>
        File "/tmp/pip-build-env-xh2t6bkj/overlay/local/lib/python3.10/dist-packages/torch/__init__.py", line 367, in <module>
          from torch._C import *  # noqa: F403
      ImportError: /tmp/pip-build-env-xh2t6bkj/overlay/local/lib/python3.10/dist-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkComplete_12_4, version libnvJitLink.so.12
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python -m pip install --upgrade pip
`

**Comment by zillionare** [comment]
same here. Working on macos

**Comment by sasilver75** [comment]
Same problem here. 

If I then try to install directly, I get 

```
(venv) sam@pop-os:~/code/ucsc/203/fairseq$ pip install ./
Processing /home/sam/code/ucsc/203/fairseq
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/home/sam/code/ucsc/203/fairseq/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/sam/code/ucsc/203/fairseq/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/sam/code/ucsc/203/fairseq/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-g0sbpqzv/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-g0sbpqzv/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-g0sbpqzv/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 12, in <module>
        File "/tmp/pip-build-env-g0sbpqzv/overlay/lib/python3.9/site-packages/torch/__init__.py", line 367, in <module>
          from torch._C import *  # noqa: F403
      ImportError: /tmp/pip-build-env-g0sbpqzv/overlay/lib/python3.9/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkComplete_12_4, version libnvJitLink.so.12
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Python 3.9.18
PopOS 22.04 LTS
Pip 24.3.1

**Comment by emmalily1245** [comment]
I feel that this project has many problems in installation, almost every project using fairseq requires to use a inner fairseq as it appendix
